/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <TelephonyUI/TPBottomBar.h>

@class TPPushButton;

@interface TPBottomButtonBar : TPBottomBar
{
    id _delegate;
    TPPushButton *_button;
}

- (id)button;	// IMP=0x32636f08
- (void)dealloc;	// IMP=0x32636eb0
- (id)initForEndCallWithFrame:(struct CGRect)fp8;	// IMP=0x326371d0
- (id)initForIncomingCallWaitingWithFrame:(struct CGRect)fp8;	// IMP=0x32636cf0
- (id)initForTTYWithFrame:(struct CGRect)fp8;	// IMP=0x3263707c
- (void)setButton:(id)fp8;	// IMP=0x32636f10

@end

