/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <TelephonyUI/TPBottomBar.h>

@class TPLockKnobView, TPLockTextView, UIView;

@interface TPBottomLockBar : TPBottomBar
{
    id _delegate;
    id _representedObject;
    TPLockKnobView *_knobView;
    UIView *_trackArrow;
    TPLockTextView *_labelView;
    float _knobTrackInsetLeft;
    float _fontSize;
}

+ (id)_backgroundImage;	// IMP=0x3263a42c
+ (struct CGSize)defaultSize;	// IMP=0x3263a3c0
- (void)dealloc;	// IMP=0x3263a770
- (void)downInKnob;	// IMP=0x3263a868
- (float)fontSize;	// IMP=0x3263abe0
- (void)freezeKnobInUnlockedPosition;	// IMP=0x3263ae8c
- (id)initForIncomingCallWithFrame:(struct CGRect)fp8;	// IMP=0x3263a714
- (id)initWithFrame:(struct CGRect)fp8 knobColor:(int)fp24;	// IMP=0x3263a624
- (id)initWithFrame:(struct CGRect)fp8 knobImage:(id)fp24;	// IMP=0x3263a4c0
- (id)knob;	// IMP=0x3263a814
- (void)knobDragged:(float)fp8;	// IMP=0x3263abe8
- (float)knobTrackInsetLeft;	// IMP=0x3263b0c8
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3263afe8
- (void)relock;	// IMP=0x3263adf4
- (void)removeFromSuperview;	// IMP=0x3263b070
- (id)representedObject;	// IMP=0x3263afe0
- (void)setDelegate:(id)fp8;	// IMP=0x3263af90
- (void)setFontSize:(float)fp8;	// IMP=0x3263abd8
- (void)setLabel:(id)fp8;	// IMP=0x3263a934
- (void)setRepresentedObject:(id)fp8;	// IMP=0x3263af98
- (void)slideBack:(BOOL)fp8;	// IMP=0x3263ac64
- (void)startAnimating;	// IMP=0x3263a81c
- (void)stopAnimating;	// IMP=0x3263a844
- (void)unlock;	// IMP=0x3263af44
- (void)upInKnob;	// IMP=0x3263a8cc

@end

