/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class TPLCDSubImageView, TPLCDTextView;

@interface TPLCDView : UIImageView
{
    TPLCDTextView *_textView;
    TPLCDTextView *_secondLineTextView;
    TPLCDTextView *_labelView;
    TPLCDSubImageView *_imageView;
    unsigned int _layoutAsLabelled:1;
}

+ (id)backgroundImage;	// IMP=0x32635534
+ (float)defaultHeight;	// IMP=0x326354d4
+ (float)labelFontSize;	// IMP=0x3263557c
+ (void)preloadImages;	// IMP=0x326354a4
+ (float)textFontSize;	// IMP=0x32635570
- (struct CGRect)_labelFrame;	// IMP=0x3263699c
- (struct CGRect)_text1Frame;	// IMP=0x32636bb4
- (struct CGRect)_text2Frame;	// IMP=0x32636a98
- (void)blinkLabel;	// IMP=0x32635e34
- (void)dealloc;	// IMP=0x32635730
- (id)initWithDefaultSize;	// IMP=0x32635588
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32635628
- (id)label;	// IMP=0x32635e14
- (void)layoutSubviews;	// IMP=0x326365bc
- (id)secondLineText;	// IMP=0x32635c80
- (void)setContentsAlpha:(float)fp8;	// IMP=0x326357b0
- (void)setLabel:(id)fp8;	// IMP=0x32635ca0
- (void)setLayoutAsLabelled:(BOOL)fp8;	// IMP=0x32636528
- (void)setSecondLineText:(id)fp8;	// IMP=0x32635a64
- (void)setShadowColor:(struct CGColor *)fp8;	// IMP=0x326364dc
- (void)setSubImage:(id)fp8;	// IMP=0x3263603c
- (void)setText:(id)fp8;	// IMP=0x326357fc
- (id)subImage;	// IMP=0x326364bc
- (id)text;	// IMP=0x32635a08
- (struct CGRect)textFrame;	// IMP=0x32635a28

@end

