/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class NSString;

@interface TPPushButton : UIThreePartButton
{
    NSString *_plusSeparatedTitle;
    int _tpcolor;
    float _titleImagePadding;
    float _titleImageRightMargin;
    float _titleVerticalOffset;
    float _iconVerticalOffset;
    float _iconAlpha;
}

+ (id)answerButtonImage;	// IMP=0x3263753c
+ (id)declineButtonImage;	// IMP=0x326375d0
+ (float)defaultHeight;	// IMP=0x326374e8
+ (float)defaultHeightForColor:(int)fp8;	// IMP=0x32637518
+ (void)preloadImagesForColor:(int)fp8;	// IMP=0x3263752c
- (CDAnonymousStruct1)_buttonSlices;	// IMP=0x3263766c
- (void)dealloc;	// IMP=0x32637b4c
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;	// IMP=0x32637e94
- (void)drawImageAtPoint:(struct CGPoint)fp8 fraction:(float)fp16;	// IMP=0x32637d80
- (void)drawTitleAtPoint:(struct CGPoint)fp8 width:(float)fp16;	// IMP=0x32638444
- (id)initWithTitle:(id)fp8 icon:(id)fp12 color:(int)fp16 frame:(struct CGRect)fp20;	// IMP=0x326376ac
- (float)minTitleMargin;	// IMP=0x32637664
- (int)pushButtonColor;	// IMP=0x32637c58
- (void)setIconAlpha:(float)fp8;	// IMP=0x32637d48
- (void)setIconVerticalOffset:(float)fp8;	// IMP=0x32637d10
- (void)setPlusSeparatedTitle:(id)fp8;	// IMP=0x32637ba4
- (void)setPushButtonColor:(int)fp8;	// IMP=0x32637c00
- (void)setTitleImagePadding:(float)fp8;	// IMP=0x32637c68
- (void)setTitleImageRightMargin:(float)fp8;	// IMP=0x32637ca0
- (void)setTitleVerticalOffset:(float)fp8;	// IMP=0x32637cd8
- (float)titleImagePadding;	// IMP=0x32637c60

@end

