/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <TelephonyUI/TPBottomLockBar.h>

@interface TPTopLockBar : TPBottomLockBar
{
}

+ (id)_backgroundImage;	// IMP=0x3263da4c
- (id)initWithFrame:(struct CGRect)fp8 knobImage:(id)fp24;	// IMP=0x3263dad4
- (float)knobTrackInsetLeft;	// IMP=0x3263db8c

@end

