/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UITableCell;

@interface _UITableCellGrabber : UIControl
{
    UITableCell *_cell;
    struct CGPoint _downPoint;
}

- (void)_controlMouseDown:(struct __GSEvent *)fp8;	// IMP=0x323eaf94
- (void)_controlMouseDragged:(struct __GSEvent *)fp8;	// IMP=0x323eaf9c
- (void)_controlMouseUp:(struct __GSEvent *)fp8;	// IMP=0x323eaf98
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x323eaf24
- (BOOL)cancelMouseTracking;	// IMP=0x323eafa0
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x323ebfa8
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323eae60
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x323eaf64
- (id)initWithCell:(id)fp8;	// IMP=0x323ead40
- (BOOL)shouldTrack;	// IMP=0x323eaf1c

@end

