/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface _UITableDeleteAnimationSupport : NSObject
{
    NSMutableArray *_cellsToDeleteAfterAnimation;
    int _deleteCount;
    unsigned int _enabledStateBeforeDeleteAnimation:1;
    unsigned int _reserved:30;
}

@end

