/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMHTMLAnchorElement.h"

@interface DOMHTMLAnchorElement (UIWebViewAdditions)
- (id)calloutSubtitle;	// IMP=0x32438060
- (id)calloutTitle;	// IMP=0x32437f70
@end

