/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMHTMLInputElement.h"

@interface DOMHTMLInputElement (UIWebViewAdditions)
- (id)calloutSubtitle;	// IMP=0x32438aa0
- (id)calloutTitle;	// IMP=0x324388d0
- (BOOL)canBecomeFirstResponder;	// IMP=0x32438840
- (Class)formPeripheralClass;	// IMP=0x32438818
- (BOOL)isLikelyToBeginPageLoad;	// IMP=0x32438be0
- (BOOL)isSecure;	// IMP=0x3243876c
- (BOOL)isTextControl;	// IMP=0x324387a8
- (id)text;	// IMP=0x32438750
- (id)textTraits;	// IMP=0x324384cc
@end

