/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMHTMLOptionElement.h"

@interface DOMHTMLOptionElement (UIWebViewEditingExtensions)
- (Class)formPeripheralClass;	// IMP=0x32438cd0
- (id)title;	// IMP=0x32438cf8
@end

