/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIBezierPath.h>

@interface UIBezierPath (TableExtras)
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withTopCornerRadius:(float)fp24 withBottomCornerRadius:(float)fp28;	// IMP=0x32447824
@end

