/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage, UITextTraits;

@interface UIKeyboard : UIView
{
    UIImage *m_snapshot;
    UITextTraits *m_defaultTextTraits;
}

+ (id)activeKeyboard;	// IMP=0x3249d330
+ (struct CGSize)defaultSize;	// IMP=0x3249d3d4
+ (struct CGSize)defaultSizeForOrientation:(int)fp8;	// IMP=0x3249d474
+ (void)initImplementationNow;	// IMP=0x3249d384
+ (struct CGSize)keypadSize;	// IMP=0x3249d510
+ (struct CGSize)keypadSizeForOrientation:(int)fp8;	// IMP=0x3249d558
+ (id)preferenceName;	// IMP=0x3249d340
+ (void)preheatArtwork;	// IMP=0x3249e2c8
+ (void)removeAllDynamicDictionaries;	// IMP=0x3249d3ac
+ (struct CGSize)suggestionBarSize;	// IMP=0x3249d41c
+ (struct CGSize)suggestionBarSizeForOrientation:(int)fp8;	// IMP=0x3249d4b8
- (void)acceptAutocorrection;	// IMP=0x3249da5c
- (void)activate;	// IMP=0x3249deb0
- (void)clearSnapshot;	// IMP=0x3249dd90
- (void)configureForTests;	// IMP=0x3249dce8
- (void)deactivate;	// IMP=0x3249e0c0
- (void)dealloc;	// IMP=0x3249d2bc
- (id)defaultTextTraits;	// IMP=0x3249dbe0
- (id)delegate;	// IMP=0x3249dd48
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3249e1b4
- (void)geometryChangeDone:(BOOL)fp8;	// IMP=0x3249d8e0
- (void)hideSuggestionBar;	// IMP=0x3249d980
- (id)initWithDefaultSize;	// IMP=0x3249d230
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3249d190
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x3249e258
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x3249e260
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x3249e25c
- (void)movedFromSuperview:(id)fp8;	// IMP=0x3249e178
- (int)orientation;	// IMP=0x3249d7d8
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3249d82c
- (int)preferredKeyboardType;	// IMP=0x3249d6f8
- (void)prepareForGeometryChange;	// IMP=0x3249d898
- (void)removeAutocorrectPrompt;	// IMP=0x3249da14
- (BOOL)returnKeyEnabled;	// IMP=0x3249db44
- (void)setCaretBlinks:(BOOL)fp8;	// IMP=0x3249daa4
- (void)setCaretVisible:(BOOL)fp8;	// IMP=0x3249daf4
- (void)setDefaultReturnKeyType:(int)fp8;	// IMP=0x3249dc88
- (void)setDefaultTextTraits:(id)fp8;	// IMP=0x3249dc04
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x3249d5a0
- (void)setPreferredKeyboardType:(int)fp8;	// IMP=0x3249d740
- (void)setReturnKeyEnabled:(BOOL)fp8;	// IMP=0x3249db90
- (void)setStringValue:(id)fp8;	// IMP=0x3249d620
- (void)showPreferredLayout;	// IMP=0x3249d790
- (void)showSuggestionBar;	// IMP=0x3249d938
- (id)stringValue;	// IMP=0x3249d6a0
- (BOOL)suggestionBarVisible;	// IMP=0x3249d9c8
- (void)takeSnapshot;	// IMP=0x3249ddbc

@end

