/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIKeyboardLayout.h>

@interface UIKeyboardLayoutQWERTY : UIKeyboardLayout
{
}

- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324a8074
- (void)registerReturnKeyViewsForSublayout:(id)fp8;	// IMP=0x324a80e8

@end

