/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UINavigationItem.h>

@interface UINavigationItem (Static)
- (id)_buttonViewWithNavBar:(id)fp8;	// IMP=0x323d59f0
- (void)_removeTitleAndButtonViews;	// IMP=0x323d5a48
- (id)_titleView;	// IMP=0x323d5984
@end

