/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UINavigationBarBackground : UIView
{
    int _barStyle;
}

- (int)barStyle;	// IMP=0x323d69e0
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323d73a0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323d6904
- (void)setBarStyle:(int)fp8;	// IMP=0x323d6994

@end

