/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIProgressIndicator : UIView
{
    float _duration;
    struct {
        unsigned int style:3;
        unsigned int animating:1;
        unsigned int reserved:28;
    } _progressIndicatorFlags;
}

+ (void)_loadResourcesForStyle:(int)fp8;	// IMP=0x3240d8e8
+ (struct CGSize)defaultSizeForStyle:(int)fp8;	// IMP=0x3240da88
+ (struct CGSize)size;	// IMP=0x3240dabc
- (void)_didMoveFromWindow:(id)fp8 toWindow:(id)fp12;	// IMP=0x3240ddac
- (void)dealloc;	// IMP=0x3240db54
- (void)setAnimationDuration:(float)fp8;	// IMP=0x3240dd54
- (void)setStyle:(int)fp8;	// IMP=0x3240daf8
- (void)startAnimation;	// IMP=0x3240dba8
- (void)stopAnimation;	// IMP=0x3240dd14

@end

