/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPreferencesTableCell.h>

@interface UIPreferencesTableCell (SyntheticEvents)
- (id)_automationID;	// IMP=0x32446db8
- (id)_automationValue;	// IMP=0x32446e88
@end

