/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIScrollAnimation : UIAnimation
{
    struct CGPoint _startPoint;
    struct CGPoint _endPoint;
}

- (void)setEndPoint:(struct CGPoint)fp8;	// IMP=0x323fcebc
- (void)setProgress:(float)fp8;	// IMP=0x323fcfd0
- (void)setStartPoint:(struct CGPoint)fp8;	// IMP=0x323fceb0

@end

