/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, NSSet, UISectionIndex, UISectionTable;

@interface UISectionList : UIView
{
    UISectionTable *_table;
    UISectionIndex *_index;
    NSMutableArray *_titles;
    NSSet *_indexTitlesAsSet;
    int _sectionCount;
    float _listWidth;
    struct {
        unsigned int nonIndexedTitlesShownFirst:1;
    } _sectionListFlags;
}

+ (float)defaultIndexWidth;	// IMP=0x323faaf4
- (id)_indexTitlesAsSet;	// IMP=0x323faf7c
- (id)allTitles;	// IMP=0x323fab80
- (int)closestSectionForTitle:(id)fp8;	// IMP=0x323faeb0
- (void)dealloc;	// IMP=0x323fa9cc
- (id)indexTitles;	// IMP=0x323fabe0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323fa970
- (id)initWithFrame:(struct CGRect)fp8 showSectionIndex:(BOOL)fp24;	// IMP=0x323fa7cc
- (float)marginForIndexControl:(BOOL)fp8;	// IMP=0x323fab1c
- (void)noteIndexTitlesDidChange;	// IMP=0x323facb0
- (int)numberOfSections;	// IMP=0x323fae48
- (void)reloadData;	// IMP=0x323facd4
- (void)setAllowsScrollIndicators:(BOOL)fp8;	// IMP=0x323fabfc
- (void)setDataSource:(id)fp8;	// IMP=0x323faa4c
- (void)setNonIndexedTitlesShownLast:(BOOL)fp8;	// IMP=0x323fac78
- (void)setSectionListStyle:(int)fp8;	// IMP=0x323fac90
- (void)setShouldHideHeaderInShortLists:(BOOL)fp8;	// IMP=0x323fac20
- (BOOL)showsSectionHeaders;	// IMP=0x323fac44
- (BOOL)showsSectionIndex;	// IMP=0x323fac68
- (id)table;	// IMP=0x323faff8
- (id)titleForSection:(int)fp8;	// IMP=0x323fae50

@end

