/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UISegmentedControl.h>

@interface UISegmentedControl (Static)
- (void)_clearSelectedSegment;	// IMP=0x324102fc
- (void)_createSegmentAtIndex:(int)fp8 position:(unsigned int)fp12 withInfo:(id)fp16;	// IMP=0x32410208
- (void)_insertSegment:(int)fp8 withInfo:(id)fp12 animated:(BOOL)fp16;	// IMP=0x324118c4
- (void)_removeSegmentAnimationFinished:(id)fp8 finished:(id)fp12 context:(void *)fp16;	// IMP=0x3241033c
@end

