/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface UIShadowView : UIView
{
    UIImage *_image;
}

+ (id)bottomShadowImage;	// IMP=0x32457e5c
+ (id)topShadowImage;	// IMP=0x32457e40
- (void)dealloc;	// IMP=0x32457d6c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32457dc4
- (BOOL)ignoresMouseEvents;	// IMP=0x32457d64
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32457cdc
- (void)setShadowImage:(id)fp8 forEdge:(int)fp12 inside:(BOOL)fp16;	// IMP=0x32457e78

@end

