/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIRemoveControl.h>

@interface UITableCellRemoveControl : UIRemoveControl
{
    float _verticalOffset;
}

- (float)_verticalOffsetFromTarget;	// IMP=0x323eaab0
- (id)initWithTarget:(id)fp8;	// IMP=0x323eaa14

@end

