/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPushButton.h>

@interface UIThreePartButton : UIPushButton
{
    CDAnonymousStruct4 _bkgndSlices;
}

+ (struct __GSFont *)defaultFont;	// IMP=0x3241a7e4
- (CDAnonymousStruct4)_backgroundSlices:(struct CGSize)fp8;	// IMP=0x3241a920
- (id)background;	// IMP=0x3241a900
- (void)drawTitleAtPoint:(struct CGPoint)fp8 width:(float)fp16;	// IMP=0x3241a998
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3241a7f8
- (float)minTitleMargin;	// IMP=0x3241a964
- (void)setBackgroundImage:(id)fp8;	// IMP=0x3241a8c0
- (void)setBackgroundSlices:(CDAnonymousStruct4)fp8;	// IMP=0x3241a880
- (void)setPressedBackgroundImage:(id)fp8;	// IMP=0x3241a8e0

@end

