/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIBezierPath;

@interface UITouchDiagnosticsLayer : UIView
{
    struct __CFArray *_eventQueue;
    UIBezierPath *_hitRectsPath;
    UIBezierPath *_customHitRectsPath;
    UIBezierPath *_chargesPath;
    BOOL _trackTouchEvents;
    BOOL _displayTouchEvents;
    BOOL _displayHitRects;
    BOOL _displayChargeMap;
}

- (void)_addLayerHitRects:(id)fp8 toPath:(id)fp12 customPath:(id)fp16;	// IMP=0x3242a43c
- (void)dealloc;	// IMP=0x3242a284
- (void)diagnoseEvent:(struct __GSEvent *)fp8;	// IMP=0x3242a6e4
- (void)drawChargeMap;	// IMP=0x3242adc4
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3242a8fc
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3242a1dc
- (BOOL)layerRespondsToEvents:(id)fp8;	// IMP=0x3242a314
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3242a778
- (void)refreshHitRects;	// IMP=0x3242a780
- (void)setDisplayChargeMap:(BOOL)fp8;	// IMP=0x3242a880
- (void)setDisplayHitRects:(BOOL)fp8;	// IMP=0x3242a818
- (void)setDisplayTouchEvents:(BOOL)fp8;	// IMP=0x3242a84c
- (void)setTrackTouchEvents:(BOOL)fp8;	// IMP=0x3242a7e4
- (void)tearDown;	// IMP=0x3242a8b4

@end

