/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (UIImageViewImplementation)
- (id)image;	// IMP=0x3240d720
- (id)initWithImage:(id)fp8;	// IMP=0x3240d670
- (void)setImage:(id)fp8;	// IMP=0x3240d7f8
@end

