/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (UIAutocorrectInlinePrompt)
- (void)reduceWidth:(float)fp8;	// IMP=0x324a1af8
@end

