/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWebView.h>

@interface UIWebView (PDF)
+ (id)_PDFPageNumberLabel;	// IMP=0x324aef3c
- (void)hidePDFPageNumberLabel;	// IMP=0x324aefc0
- (void)updatePDFPageNumberLabel;	// IMP=0x324af03c
@end

