/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface _NSDWARFAbbrevDecl : NSObject
{
    unsigned int _tag;	// 4 = 0x4
    BOOL _hasChildren;	// 8 = 0x8
    NSArray *_attributes;	// 12 = 0xc
}

+ (id)abbrevDeclWithTag:(unsigned int)fp8 withChildren:(BOOL)fp12 withAttributes:(id)fp16;	// IMP=0x31884844
- (id)description;	// IMP=0x318848bc

@end

