/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface _NSDWARFAttribute : NSObject
{
    unsigned int _name;	// 4 = 0x4
    unsigned int _form;	// 8 = 0x8
}

+ (id)attributeWithName:(unsigned int)fp8 withForm:(unsigned int)fp12;	// IMP=0x318847a4
- (id)description;	// IMP=0x318847f8

@end

