/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface _NSSourceInfo : NSObject
{
    NSString *_filename;	// 4 = 0x4
    unsigned long long _lineNumber;	// 8 = 0x8
    unsigned long long _columnNumber;	// 16 = 0x10
    unsigned long long _fileOffset;	// 24 = 0x18
}

- (id)description;	// IMP=0x31884690

@end

