/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <vmutils/MemoryCache.h>

@interface MappedMemoryCache : MemoryCache
{
}

- (void)dealloc;	// IMP=0x3187e988
- (void)finalize;	// IMP=0x3187e9dc
- (id)init;	// IMP=0x3187e90c
- (BOOL)mapAddress:(unsigned int)fp8 toAddress:(unsigned int)fp12 size:(unsigned int)fp16;	// IMP=0x3187ea30
- (int)peekAtAddress:(unsigned int)fp8 returnsSize:(unsigned int *)fp12 returnsBuf:(void **)fp16;	// IMP=0x3187ec00
- (int)peekAtAddress:(unsigned int)fp8 size:(unsigned int)fp12 returnsBuf:(void **)fp16;	// IMP=0x3187eaf0
- (int)readPointerAt:(unsigned int)fp8 value:(unsigned int *)fp12;	// IMP=0x3187eb78
- (int)startPeeking;	// IMP=0x3187eae0
- (int)stopPeeking;	// IMP=0x3187eae8

@end

