/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <vmutils/NSMachOSymbolTable.h>

@interface NSMachOSymbolTable (PrivateRangeValueContainerFix)
- (void)populateSourceInfo;	// IMP=0x31884aa8
@end

