/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopyingProtocol.h"
#import "SafeNSProcInfoProtocolProtocol.h"

@class NSArray, NSImage, NSString;

@interface NSProcInfo : NSObject <SafeNSProcInfoProtocol, NSCopying>
{
    unsigned int _task;	// 4 = 0x4
    BOOL _needTaskPortDealloc;	// 8 = 0x8
    NSString *_name;	// 12 = 0xc
    int _cpuType;	// 16 = 0x10
    NSArray *_envVars;	// 20 = 0x14
    NSString *_procTableName;	// 24 = 0x18
    NSString *_realAppName;	// 28 = 0x1c
    NSString *_requestedAppName;	// 32 = 0x20
    NSString *_firstArg;	// 36 = 0x24
    int _pid;	// 40 = 0x28
    int _ppid;	// 44 = 0x2c
    struct timeval _startTime;	// 48 = 0x30
    NSImage *_procIconImage;	// 56 = 0x38
}

+ (id)getProcessIds;	// IMP=0x3189843c
+ (BOOL)isProcessRunning:(int)fp8;	// IMP=0x31898590
+ (int)processParentId:(int)fp8;	// IMP=0x318985f4
- (id)_nameFromCommandLine:(int)fp8;	// IMP=0x31898a64
- (id)_searchForImage;	// IMP=0x3189906c
- (int)compare:(id)fp8;	// IMP=0x3189943c
- (int)compareByName:(id)fp8;	// IMP=0x31899498
- (int)compareByUserAppName:(id)fp8;	// IMP=0x318994f0
- (int)cpuType;	// IMP=0x318992ec
- (void)dealloc;	// IMP=0x31898330
- (id)description;	// IMP=0x31898f78
- (id)envVars;	// IMP=0x31898784
- (void)finalize;	// IMP=0x318983d4
- (id)firstArgument;	// IMP=0x31898df4
- (unsigned int)hash;	// IMP=0x31899548
- (id)image;	// IMP=0x31899074
- (id)init;	// IMP=0x31898278
- (id)initWithPid:(int)fp8;	// IMP=0x318982b8
- (id)initWithTask:(unsigned int)fp8;	// IMP=0x318982e0
- (BOOL)isApp;	// IMP=0x31899268
- (BOOL)isCFM;	// IMP=0x31899298
- (BOOL)isEqual:(id)fp8;	// IMP=0x318993c0
- (BOOL)isMachO;	// IMP=0x31899270
- (BOOL)isNative;	// IMP=0x31899300
- (BOOL)isRunning;	// IMP=0x31899334
- (id)name;	// IMP=0x31898ebc
- (int)pid;	// IMP=0x31898fc4
- (int)ppid;	// IMP=0x31898fcc
- (id)procTableName;	// IMP=0x3189893c
- (id)realAppName;	// IMP=0x31898ce8
- (id)requestedAppName;	// IMP=0x31898d6c
- (BOOL)signal:(int)fp8;	// IMP=0x318993a0
- (struct timeval)startTime;	// IMP=0x31898658
- (unsigned int)task;	// IMP=0x31898fd4
- (BOOL)terminate;	// IMP=0x31899364
- (void)update;	// IMP=0x31899160
- (id)userAppName;	// IMP=0x31898e40

@end

