/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface RangeArray : NSObject
{
    unsigned int _count;	// 4 = 0x4
    struct _NSRange *_ranges;	// 8 = 0x8
    unsigned int _max;	// 12 = 0xc
}

- (void)addRange:(struct _NSRange)fp8;	// IMP=0x3187ee64
- (void)addRanges:(id)fp8;	// IMP=0x3187eec0
- (unsigned int)count;	// IMP=0x3187ee48
- (void)dealloc;	// IMP=0x3187ed98
- (id)description;	// IMP=0x3187f1a8
- (void)encodeWithCoder:(id)fp8;	// IMP=0x31881178
- (void)finalize;	// IMP=0x3187edec
- (id)init;	// IMP=0x3187ecac
- (id)initWithCoder:(id)fp8;	// IMP=0x31881270
- (id)initWithRanges:(const struct _NSRange *)fp8 count:(unsigned int)fp12;	// IMP=0x3187ed14
- (void)insertRange:(struct _NSRange)fp8 atIndex:(unsigned int)fp16;	// IMP=0x3187ef14
- (BOOL)intersectsRange:(struct _NSRange)fp8;	// IMP=0x3187effc
- (struct _NSRange)largestRange;	// IMP=0x3187f244
- (struct _NSRange)largestSubrangeNotExcludedBySelfForRange:(struct _NSRange)fp8 andLargerThan:(unsigned int)fp16;	// IMP=0x31880fac
- (struct _NSRange)range;	// IMP=0x31880914
- (struct _NSRange)rangeAtIndex:(unsigned int)fp8;	// IMP=0x3187ee50
- (struct _NSRange)rangeForLocation:(unsigned int)fp8;	// IMP=0x31880980
- (struct _NSRange *)ranges;	// IMP=0x3187ee40
- (void)removeRangeAtIndex:(unsigned int)fp8;	// IMP=0x3187efa8
- (struct _NSRange)subrangeNotExcludedBySelfForRange:(struct _NSRange)fp8;	// IMP=0x3187f080
- (unsigned int)sumLengths;	// IMP=0x3187f2ac

@end

