/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <vmutils/MemoryCache.h>

@interface TaskMemoryCache : MemoryCache
{
    unsigned int _task;	// 8 = 0x8
    BOOL _stopped;	// 12 = 0xc
}

- (void)dealloc;	// IMP=0x3187e19c
- (void)finalize;	// IMP=0x3187e29c
- (void)flushMemoryCache;	// IMP=0x3187e808
- (id)initForTask:(unsigned int)fp8;	// IMP=0x3187e130
- (int)peekAtAddress:(unsigned int)fp8 returnsSize:(unsigned int *)fp12 returnsBuf:(void **)fp16;	// IMP=0x3187e3e0
- (int)peekAtAddress:(unsigned int)fp8 size:(unsigned int)fp12 returnsBuf:(void **)fp16;	// IMP=0x3187e53c
- (int)readPointerAt:(unsigned int)fp8 value:(unsigned int *)fp12;	// IMP=0x3187e7c4
- (int)startPeeking;	// IMP=0x3187e39c
- (int)stopPeeking;	// IMP=0x3187e8d0

@end

