/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMapTable, NSMutableArray;

@interface TraceData : NSObject
{
    NSMapTable *pcMap;	// 4 = 0x4
    NSMapTable *threadTraces;	// 8 = 0x8
    NSMapTable *libXrefs;	// 12 = 0xc
    NSMapTable *fnXrefs;	// 16 = 0x10
    NSMutableArray *threadIDs;	// 20 = 0x14
    unsigned int maxDepth;	// 24 = 0x18
    unsigned int threadCount;	// 28 = 0x1c
}

- (void)addEvent:(id)fp8;	// IMP=0x318a9290
- (void)addOrIncrementXref:(id)fp8 withParent:(id)fp12 withChild:(id)fp16 withSelector:(SEL)fp20 commutative:(BOOL)fp24;	// IMP=0x318aa9c8
- (void)buildPCMap:(unsigned int *)fp8 withNumPages:(unsigned int)fp12 forTask:(unsigned int)fp16;	// IMP=0x318a9390
- (void)dealloc;	// IMP=0x318a9180
- (void)finalize;	// IMP=0x318a9220
- (void)freeXrefTable:(id)fp8;	// IMP=0x318a9108
- (id)functionXref;	// IMP=0x318aac50
- (void)generateXref:(id)fp8 withSelector:(SEL)fp12 commutative:(BOOL)fp16;	// IMP=0x318aaaf4
- (id)init;	// IMP=0x318a9018
- (id)initWithBacktraces:(id)fp8 forTask:(unsigned int)fp12;	// IMP=0x318a9890
- (id)initWithLogRecords:(CDAnonymousStruct2 *)fp8 forTask:(unsigned int)fp12;	// IMP=0x318a9520
- (id)libraryXref;	// IMP=0x318aace8
- (unsigned int)maxDepth;	// IMP=0x318a9dfc
- (void)printXrefs:(id)fp8 toString:(id)fp12;	// IMP=0x318aad84
- (BOOL)readFromFile:(struct __sFILE *)fp8;	// IMP=0x318aa10c
- (id)symbolForPC:(unsigned int)fp8;	// IMP=0x318a9dbc
- (id)threadIDs;	// IMP=0x318a9dd4
- (id)traceForThread:(unsigned int)fp8;	// IMP=0x318a9ddc
- (void)writeToFile:(struct __sFILE *)fp8;	// IMP=0x318a9e04

@end

