/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface xSYMImage : NSObject
{
    NSString *symFilePath;	// 4 = 0x4
    int symVersion;	// 8 = 0x8
    struct DISK_SYMBOL_HEADER_BLOCK dumpDSHB;	// 12 = 0xc
    char *nameTable;	// 224 = 0xe0
    struct __sFILE *symFile;	// 228 = 0xe4
    struct pagebuff *pageList;	// 232 = 0xe8
    int symFileDesc;	// 236 = 0xec
    struct stat symFileStats;	// 240 = 0xf0
    struct MODULES_TABLE_ENTRY *optimizedMTEs;	// 336 = 0x150
}

- (long)CLTECount;	// IMP=0x31895f20
- (union CONTAINED_LABELS_TABLE_ENTRY *)CLTEntryAtIndex:(long)fp8;	// IMP=0x31895f30
- (long)CMTECount;	// IMP=0x318954ec
- (union CONTAINED_MODULES_TABLE_ENTRY *)CMTEntryAtIndex:(long)fp8;	// IMP=0x318954fc
- (long)CSNTECount;	// IMP=0x318963d4
- (union CONTAINED_STATEMENTS_TABLE_ENTRY *)CSNTEntryAtIndex:(long)fp8;	// IMP=0x318963e4
- (long)CTTECount;	// IMP=0x318967e8
- (union CONTAINED_TYPES_TABLE_ENTRY *)CTTEntryAtIndex:(long)fp8;	// IMP=0x318967f8
- (long)CVTECount;	// IMP=0x318957c4
- (union CONTAINED_VARIABLES_TABLE_ENTRY *)CVTEntryAtIndex:(long)fp8;	// IMP=0x318957d4
- (long)FITECount;	// IMP=0x31896e64
- (union FRTE_INDEX_TABLE_ENTRY *)FITEntryAtIndex:(long)fp8;	// IMP=0x31896e74
- (long)FRTECount;	// IMP=0x31894d7c
- (union FILE_REFERENCE_TABLE_ENTRY *)FRTEntryAtIndex:(long)fp8;	// IMP=0x31894db0
- (long)MTECount;	// IMP=0x31894314
- (char *)MTENameAtIndex:(long)fp8;	// IMP=0x31894800
- (struct MODULES_TABLE_ENTRY *)MTEntryAtIndex:(long)fp8;	// IMP=0x318946ec
- (struct MODULES_TABLE_ENTRY *)MTEntryWithResOffset:(long)fp8 fromIndex:(long)fp12 toIndex:(long)fp16;	// IMP=0x31894748
- (long)RTECount;	// IMP=0x3189511c
- (struct RESOURCE_TABLE_ENTRY *)RTEntryAtIndex:(long)fp8;	// IMP=0x3189512c
- (long)TTECount;	// IMP=0x31896c28
- (BOOL)checkVersion;	// IMP=0x31893dbc
- (struct RESOURCE_TABLE_ENTRY *)codeRTE;	// IMP=0x31895268
- (void)convertToDTI:(struct DISK_TABLE_INFO *)fp8 fromDTIv32v33v333:(struct DISK_TABLE_INFO_v32 *)fp12;	// IMP=0x31893ed0
- (void)convertToFREF:(struct FILE_REFERENCE *)fp8 fromFREFv32v33:(struct FILE_REFERENCE_v32 *)fp12;	// IMP=0x31894d8c
- (struct RESOURCE_TABLE_ENTRY *)dataRTE;	// IMP=0x31895300
- (void)dealloc;	// IMP=0x31893c38
- (struct pagebuff *)fetchPage:(long)fp8;	// IMP=0x31893d5c
- (void)finalize;	// IMP=0x31893cd4
- (char *)getAddr:(long)fp8 page:(long)fp12;	// IMP=0x31893d6c
- (id)initWithPath:(id)fp8;	// IMP=0x31893a8c
- (char *)nameAtIndex:(long)fp8;	// IMP=0x31897230
- (void)optimizeMTEs;	// IMP=0x31894324
- (void)printCLTE;	// IMP=0x318961ac
- (void)printCMTE;	// IMP=0x31895698
- (void)printCSNTE;	// IMP=0x31896628
- (void)printCTTE;	// IMP=0x31896a3c
- (void)printCVTE;	// IMP=0x31895a88
- (void)printDSHB;	// IMP=0x31897480
- (void)printDTI:(struct DISK_TABLE_INFO *)fp8 name:(char *)fp12 size:(long)fp16;	// IMP=0x318941ac
- (void)printFITE;	// IMP=0x31896fa4
- (void)printFRTE;	// IMP=0x31894f3c
- (void)printMTE;	// IMP=0x31894840
- (void)printModDate:(long)fp8;	// IMP=0x31893eb0
- (void)printNTE;	// IMP=0x318942ac
- (char *)printNameTableEntry:(char *)fp8;	// IMP=0x318972f4
- (void)printRTE;	// IMP=0x31895398
- (void)printSourceLocations;	// IMP=0x318970bc
- (void)printTypeInfo;	// IMP=0x31896c38
- (BOOL)readDSHB;	// IMP=0x31893f04
- (BOOL)readNTE;	// IMP=0x31894204

@end

