/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>
#import <vmutils/NSFunctionNameDemangler.h>
#import <vmutils/NSMachOTaskImage.h>

@interface ImageSymbols : NSObject
{
    NSMapTable *_pcToNSStringCache;	// 4 = 0x4
    NSMachOTaskImage *_image;	// 8 = 0x8
    unsigned int _task;	// 12 = 0xc
    NSFunctionNameDemangler *_demangler;	// 16 = 0x10
    NSMapTable *_badPCToName;	// 20 = 0x14
}

+ (void)forceForTask:(unsigned int)fp8 specialSymbols:(id)fp12;	// IMP=0x31897c24
+ (id)imageSymbolsForCurrentProcess;	// IMP=0x31897bf4
+ (id)imageSymbolsWithTask:(unsigned int)fp8 subst:(id)fp12;	// IMP=0x31897b78
+ (void)initialize;	// IMP=0x31897b18
- (id)_rawSymbolForPC:(unsigned int)fp8;	// IMP=0x31897dd8
- (struct _NSRange)addressRangeOfOneSymbolWithAddress:(unsigned int)fp8;	// IMP=0x31898090
- (struct _NSRange)addressRangeOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x31898054
- (struct _NSRange)addressRangeOfSymbolWithName:(id)fp8;	// IMP=0x31898114
- (id)allHeaders;	// IMP=0x31898238
- (id)badPCToName;	// IMP=0x3189804c
- (void)dealloc;	// IMP=0x31897920
- (void)finalize;	// IMP=0x318979b4
- (void)forceNonLazyLoadOfAllSymbols;	// IMP=0x31897ee8
- (id)imageSignature;	// IMP=0x31897d18
- (id)init;	// IMP=0x3189789c
- (id)initWithTask:(unsigned int)fp8 subst:(id)fp12;	// IMP=0x31897a24
- (id)libraryForPC:(unsigned int)fp8;	// IMP=0x31898170
- (id)libraryRangesForPC:(unsigned int)fp8;	// IMP=0x318980f4
- (id)machBinaries;	// IMP=0x31898190
- (unsigned int)pcForSymbol:(id)fp8;	// IMP=0x31897f08
- (unsigned int)pcForSymbol:(id)fp8 inLibrary:(id)fp12;	// IMP=0x31897f48
- (struct stabInfo *)sourceLocationOfAddress:(unsigned int)fp8;	// IMP=0x318980d4
- (id)symbolForPC:(unsigned int)fp8;	// IMP=0x31897fac
- (unsigned int)task;	// IMP=0x318980cc
- (id)taskImage;	// IMP=0x31898230
- (void)updateHeaders;	// IMP=0x31898258

@end

