/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface MemoryCache : NSObject
{
    struct {
        unsigned long;
        unsigned long;
        unsigned char unknown[0];
    } *_memoryRegions;	// 4 = 0x4
}

- (void)dealloc;	// IMP=0x3187e0b0
- (void)finalize;	// IMP=0x3187e0f0
- (void)flushMemoryCache;	// IMP=0x3187de4c
- (id)init;	// IMP=0x3187de0c
- (int)peekAtAddress:(unsigned int)fp8 returnsSize:(unsigned int *)fp12 returnsBuf:(void **)fp16;	// IMP=0x3187de70
- (int)peekAtAddress:(unsigned int)fp8 size:(unsigned int)fp12 returnsBuf:(void **)fp16;	// IMP=0x3187de60
- (int)readPointerAt:(unsigned int)fp8 value:(unsigned int *)fp12;	// IMP=0x3187de68
- (int)readString:(char *)fp8 returnsString:(char **)fp12 isNullTerminated:(char *)fp16;	// IMP=0x3187de78
- (id)readUTF8String:(char *)fp8;	// IMP=0x3187df08
- (int)startPeeking;	// IMP=0x3187de50
- (int)stopPeeking;	// IMP=0x3187de58

@end

