/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "StabsSourceProtocol.h"
#import "SymbolSourceProtocol.h"

@class MemoryCache, NSMachOImage;

@interface NSBinaryHeader : NSObject <SymbolSource, StabsSource>
{
    NSMachOImage *_image;	// 4 = 0x4
    MemoryCache *_memoryCache;	// 8 = 0x8
}

- (unsigned int)addressOfOneSymbolWithCName:(const char *)fp8;	// IMP=0x3188cbe8
- (unsigned int)addressOfSymbolWithCName:(const char *)fp8;	// IMP=0x3188cbe0
- (unsigned int)addressOfSymbolWithCName:(const char *)fp8 inLibrary:(const char *)fp12;	// IMP=0x3188cbf0
- (struct _NSRange)addressRangeOfOneSymbolWithAddress:(unsigned int)fp8;	// IMP=0x3188cc30
- (struct _NSRange)addressRangeOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x3188cbd0
- (struct _NSRange)addressRangeOfSymbolWithCName:(const char *)fp8;	// IMP=0x3188cc20
- (const char *)cnameOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x3188cbc8
- (void)dealloc;	// IMP=0x3188ca9c
- (id)description;	// IMP=0x3188cb54
- (BOOL)hasSourceInfo;	// IMP=0x3188cbc0
- (BOOL)hasSymbolInfo;	// IMP=0x3188cbb8
- (id)image;	// IMP=0x3188cb44
- (id)initInImage:(id)fp8;	// IMP=0x3188ca44
- (id)libraryRanges;	// IMP=0x3188cbb0
- (id)name;	// IMP=0x3188cb4c
- (void)setImage:(id)fp8;	// IMP=0x3188caf4
- (struct stabInfo *)sourceLocationOfAddress:(unsigned int)fp8;	// IMP=0x3188cbf8
- (struct stabInfo *)sourceLocationsOfAddressRange:(struct _NSRange)fp8;	// IMP=0x3188cc00
- (BOOL)sourceLocationsOfAddressRange:(struct _NSRange)fp8 stabsInfo:(struct stabInfo *)fp16;	// IMP=0x3188cc08
- (struct _NSRange)sourceRangeForAddress:(unsigned int)fp8;	// IMP=0x3188cc10
- (id)symbolRanges;	// IMP=0x3188cba8

@end

