/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, RangeArray;

@interface NSNonOverlappingRangeValueTable : NSObject
{
    RangeArray *ranges;	// 4 = 0x4
    NSMutableArray *values;	// 8 = 0x8
}

- (unsigned int)_indexForLocation:(unsigned int)fp8;	// IMP=0x3187fa98
- (struct _NSRange)_indexRangeForOverlappingRangesForRange:(struct _NSRange)fp8;	// IMP=0x3187fe54
- (struct _NSRange)_indexRangeInCandidateRange:(struct _NSRange)fp8 forRange:(struct _NSRange)fp16;	// IMP=0x3187fc8c
- (void)addTable:(id)fp8;	// IMP=0x318802f0
- (void)addValue:(id)fp8 forNonOverlappingRange:(struct _NSRange)fp12;	// IMP=0x3187fc34
- (id)allRanges;	// IMP=0x318800f0
- (id)allValues;	// IMP=0x318800e8
- (unsigned int)count;	// IMP=0x3187f980
- (void)dealloc;	// IMP=0x3187f800
- (id)description;	// IMP=0x3187f8a8
- (id)dictionaryRepresentation;	// IMP=0x318800f8
- (void)encodeWithCoder:(id)fp8;	// IMP=0x318803a8
- (void)expandRangesWithinRange:(struct _NSRange)fp8;	// IMP=0x31880a70
- (void)fillRangeArray:(id)fp8 forOverlappingRangesForRange:(struct _NSRange)fp12;	// IMP=0x3187ff38
- (void)finalize;	// IMP=0x3187f868
- (struct _NSRange)firstRangeIntersectingRange:(struct _NSRange)fp8;	// IMP=0x31880704
- (id)init;	// IMP=0x3187f6b8
- (id)initWithCoder:(id)fp8;	// IMP=0x31880400
- (id)initWithDictionaryRepresentation:(id)fp8;	// IMP=0x318801bc
- (id)initWithRanges:(id)fp8 values:(id)fp12;	// IMP=0x3187f724
- (BOOL)isNonOverlapping;	// IMP=0x3187fa04
- (BOOL)isSorted;	// IMP=0x3187f98c
- (struct _NSRange)range;	// IMP=0x31880a1c
- (struct _NSRange)rangeForLocation:(unsigned int)fp8;	// IMP=0x31880794
- (BOOL)removeValueForLocation:(unsigned int)fp8;	// IMP=0x3187ffdc
- (BOOL)removeValuesForRange:(struct _NSRange)fp8;	// IMP=0x31880040
- (void)setNonOverlappingRange:(struct _NSRange)fp8;	// IMP=0x31880eec
- (void)setValue:(id)fp8 forNonOverlappingRange:(struct _NSRange)fp12;	// IMP=0x31880d5c
- (void)setValue:(id)fp8 forRange:(struct _NSRange)fp12;	// IMP=0x31880b18
- (void)setValue:(id)fp8 forRangeArray:(id)fp12;	// IMP=0x3187fecc
- (id)valueForLocation:(unsigned int)fp8;	// IMP=0x3187fb00
- (id)valuesForRange:(struct _NSRange)fp8;	// IMP=0x3187fb44

@end

