/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopyingProtocol.h"
#import "NSMutableCopyingProtocol.h"

@interface ByteSet : NSObject <NSCopying, NSMutableCopying>
{
    char mySet[32];
}

+ (id)ASCIIByteSet;	// IMP=0x30b90499
+ (id)asciiWhitespaceSet;	// IMP=0x30b90455
+ (id)nonASCIIByteSet;	// IMP=0x30b904e1
+ (id)suspiciousCodepage1252ByteSet;	// IMP=0x30b90525
- (id)_initWithSet:(const char *)fp8;	// IMP=0x30b906f5
- (BOOL)byteIsMember:(BOOL)fp8;	// IMP=0x30b9056d
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x30b90729
- (id)initWithBytes:(const void *)fp8 length:(unsigned int)fp12;	// IMP=0x30b90699
- (id)initWithCString:(const char *)fp8;	// IMP=0x30b90675
- (id)initWithRange:(struct _NSRange)fp8;	// IMP=0x30b905b9
- (id)invertedSet;	// IMP=0x30b90583
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;	// IMP=0x30b90759

@end

