/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPDownload.h>

@class NSMutableArray;

@interface IMAPCompoundDownload : IMAPDownload
{
    NSMutableArray *_subdownloads;
}

- (void)addCommandsToPipeline:(id)fp8 withCache:(id)fp12;	// IMP=0x30bb615d
- (void)addSubdownload:(id)fp8;	// IMP=0x30bb6095
- (unsigned long)bytesFetched;	// IMP=0x30bb6369
- (void)dealloc;	// IMP=0x30bb5fed
- (unsigned long)expectedLength;	// IMP=0x30bb62d1
- (BOOL)isComplete;	// IMP=0x30bb623d
- (void)processResults;	// IMP=0x30bb6201
- (void)removeSubdownload:(id)fp8;	// IMP=0x30bb6121
- (id)subdownloads;	// IMP=0x30bb6029

@end

