/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageStore.h>

@interface MessageStore (MessageFrameworkOnly)
+ (void)_autosaveMessageStore:(void *)fp8;	// IMP=0x30b46f69
- (id)_cachedBodyDataContainerForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b47589
- (id)_cachedBodyDataForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b47519
- (id)_cachedBodyForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b474d1
- (id)_cachedHeaderDataForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b47509
- (id)_cachedHeadersForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b474f9
- (void)_cancelAutosave;	// IMP=0x30b46f6b
- (id)_fetchBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12;	// IMP=0x30b46f95
- (id)_fetchBodyForMessage:(id)fp8;	// IMP=0x30b47109
- (id)_fetchBodyForMessage:(id)fp8 updateFlags:(BOOL)fp12;	// IMP=0x30b46fbd
- (id)_fetchHeaderDataForMessage:(id)fp8;	// IMP=0x30b46f6f
- (void)_flushAllCaches;	// IMP=0x30b472c1
- (void)_invalidate;	// IMP=0x30b47245
- (void)_invalidateInBackground;	// IMP=0x30b47247
- (BOOL)_isReadyToBeInvalidated;	// IMP=0x30b47129
- (void)_rebuildTableOfContentsSynchronously;	// IMP=0x30b4731d
- (void)_saveChanges;	// IMP=0x30b47131
- (void)_setFlagsAndColorForMessages:(id)fp8;	// IMP=0x30b47655
- (void)_setFlagsForMessages:(id)fp8 mask:(unsigned long)fp12;	// IMP=0x30b475e1
- (void)_setNeedsAutosave;	// IMP=0x30b46f6d
- (id)_setOrGetBody:(id)fp8 forMessage:(id)fp12;	// IMP=0x30b47439
- (id)_setOrGetBody:(id)fp8 forMessage:(id)fp12 updateFlags:(BOOL)fp16;	// IMP=0x30b47c81
- (BOOL)_shouldCallCompactWhenClosing;	// IMP=0x30b47121
- (BOOL)_shouldChangeComponentMessageFlags;	// IMP=0x30b47a05
- (BOOL)_shouldChangeComponentMessageFlagsForMessage:(id)fp8;	// IMP=0x30b47a09
- (BOOL)_updateFlagForMessage:(id)fp8 key:(id)fp12 value:(BOOL)fp16;	// IMP=0x30b47ac9
- (void)messagesWereAdded:(id)fp8 forIncrementalLoading:(BOOL)fp12;	// IMP=0x30b478e1
- (void)updateBodyFlagsForMessage:(id)fp8 body:(id)fp12;	// IMP=0x30b47345
- (void)updateMessages:(id)fp8 updateColor:(BOOL)fp12 updateNumberOfAttachments:(BOOL)fp16;	// IMP=0x30b47715
@end

