/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageCriterion.h>

@interface MessageCriterion (LibraryAdditions)
- (id)SQLExpressionWithTables:(unsigned int *)fp8 baseTable:(unsigned int)fp12;	// IMP=0x30bbab35
- (unsigned int)bestBaseTable;	// IMP=0x30bbab75
- (id)criterionForSQL;	// IMP=0x30bbab05
@end

