/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MimePart.h>

@interface MimePart (MessageSupport)
- (void)_fixSubparts;	// IMP=0x30b6be0d
- (BOOL)parseMimeBody;	// IMP=0x30b6bbc9
@end

