/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSCoder.h"

@interface NSCoder (MFMessageFlags)
- (unsigned long)decodeMessageFlags;	// IMP=0x30b60255
@end

