/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageStore.h>

@class NSData;

@interface NSDataMessageStore : MessageStore
{
    NSData *_data;
}

- (id)_cachedBodyForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b47f61
- (id)_cachedHeadersForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30b47f65
- (id)bodyDataForMessage:(id)fp8 isComplete:(char *)fp12 downloadIfNecessary:(BOOL)fp16;	// IMP=0x30b47ea1
- (void)dealloc;	// IMP=0x30b47d4d
- (id)headerDataForMessage:(id)fp8;	// IMP=0x30b47de9
- (id)initWithData:(id)fp8;	// IMP=0x30b47d0d
- (id)message;	// IMP=0x30b47d95
- (id)storePath;	// IMP=0x30b47d89
- (void)writeUpdatedMessageDataToDisk;	// IMP=0x30b47d93

@end

