/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (MimeEnrichedReader)
+ (id)stringFromMimeEnrichedString:(id)fp8 asHTML:(BOOL)fp12;	// IMP=0x30b6e011
+ (id)stringFromMimeRichTextString:(id)fp8 asHTML:(BOOL)fp12;	// IMP=0x30b6df6d
@end

