/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (MimeHeaderEncoding)
- (id)decodeMimeHeaderValue;	// IMP=0x30b6f1f9
- (id)decodeMimeHeaderValueWithCharsetHint:(id)fp8;	// IMP=0x30b6f68d
- (id)encodedHeaderData;	// IMP=0x30b6f1c1
- (id)encodedHeaderDataWithEncodingHint:(unsigned long)fp8;	// IMP=0x30b6fabd
@end

