/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/AuthScheme.h>

@interface NTLMAuthScheme : AuthScheme
{
}

+ (void)initialize;	// IMP=0x30bc0845
- (Class)authenticatorClassForAccountClass:(Class)fp8;	// IMP=0x30bc0885
- (BOOL)hasEncryption;	// IMP=0x30bc08e1
- (id)humanReadableName;	// IMP=0x30bc08b9
- (id)name;	// IMP=0x30bc08a9
- (BOOL)requiresDomain;	// IMP=0x30bc08a5
- (BOOL)sendsPlainTextPasswords;	// IMP=0x30bc08dd

@end

