/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Message.h>

@class NSData, NSString;

@interface POPMessage : Message
{
    int _messageNumber;
    NSString *_messageID;
    NSData *_messageData;
    BOOL _messageDataIsComplete;
    unsigned int _size;
    NSString *_accountURL;
}

- (id)cachedAttributes;	// IMP=0x30b5b64d
- (void)dealloc;	// IMP=0x30b5b4b5
- (id)headers;	// IMP=0x30b5b731
- (id)messageData;	// IMP=0x30b5b509
- (id)messageDataIsComplete:(char *)fp8 downloadIfNecessary:(BOOL)fp12;	// IMP=0x30b5b5c1
- (id)messageID;	// IMP=0x30b5b5df
- (int)messageNumber;	// IMP=0x30b5b501
- (unsigned int)messageSize;	// IMP=0x30b5b591
- (id)originalMailboxURL;	// IMP=0x30b5b639
- (id)remoteMailboxURL;	// IMP=0x30b5b615
- (void)setAccountURL:(id)fp8;	// IMP=0x30b5b821
- (void)setMessageData:(id)fp8;	// IMP=0x30b5b579
- (void)setMessageData:(id)fp8 isComplete:(BOOL)fp12;	// IMP=0x30b5b541
- (void)setMessageID:(id)fp8;	// IMP=0x30b5b5e3
- (void)setMessageNumber:(int)fp8;	// IMP=0x30b5b505
- (void)setMessageSize:(unsigned int)fp8;	// IMP=0x30b5b5bd

@end

