/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "DataConsumerProtocol.h"

@class NSMutableData;

@interface SimplePOPDataConsumer : NSObject <DataConsumer>
{
    NSMutableData *data;
}

- (void)appendData:(id)fp8;	// IMP=0x30b5889d
- (id)data;	// IMP=0x30b588cf
- (void)dealloc;	// IMP=0x30b588d3
- (void)done;	// IMP=0x30b588cd

@end

