/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/SASLAuthenticator.h>

@class YahooAccount;

@interface XYMPKIAuthenticator : SASLAuthenticator
{
    BOOL sentInitialResponse;
    YahooAccount *_yahooAccount;
    struct _lockdown_connection *_lockdown;
}

- (BOOL)base64EncodeResponseData;	// IMP=0x30bc6339
- (void)dealloc;	// IMP=0x30bc6381
- (id)responseForServerData:(id)fp8;	// IMP=0x30bc6535
- (id)saslName;	// IMP=0x30bc632d
- (void)setAuthenticationState:(int)fp8;	// IMP=0x30bc633d

@end

