/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MailDelivery.h>

@class MFError, NSMutableData, NSURLResponse, YahooAccount;

@interface YahooDelivery : MailDelivery
{
    NSURLResponse *_response;
    NSMutableData *_responseData;
    BOOL _done;
    MFError *_error;
    YahooAccount *_yahooAccount;
}

+ (void)initialize;	// IMP=0x30bc0ff1
- (void)connection:(id)fp8 didFailWithError:(id)fp12;	// IMP=0x30bc15b1
- (void)connection:(id)fp8 didReceiveData:(id)fp12;	// IMP=0x30bc127d
- (void)connection:(id)fp8 didReceiveData:(id)fp12 lengthReceived:(int)fp16;	// IMP=0x30bc1269
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;	// IMP=0x30bc124d
- (void)connectionDidFinishLoading:(id)fp8;	// IMP=0x30bc15d1
- (void)dealloc;	// IMP=0x30bc15d9
- (int)deliverSynchronously;	// IMP=0x30bc3141
- (void)setAccount:(id)fp8;	// IMP=0x30bc1031

@end

