/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class Account, ActivityMonitor, MFError, NSArray;

@interface AccountValidator : NSObject
{
    Account *_account;
    id _delegate;
    ActivityMonitor *_accountValidationActivity;
    struct {
        unsigned int incomingServerSupportsSSL:1;
        unsigned int smtpServerSupportsSSL:1;
        unsigned int validationInProgress:1;
        unsigned int canceled:1;
        unsigned int unused:28;
    } _flags;
    MFError *_incomingServerValidationError;
    MFError *_smtpServerValidationError;
    NSArray *_incomingServerAuthSchemes;
    NSArray *_smtpServerAuthSchemes;
}

- (void)_backgroundValidateAccountFinished:(id)fp8 authSchemes:(id)fp12;	// IMP=0x30bc740b
- (BOOL)_incomingServerValid;	// IMP=0x30bc73c1
- (id)_ispAccountInfo;	// IMP=0x30bc6be5
- (BOOL)_outgoingServerValid;	// IMP=0x30bc73e5
- (void)_updateValidationStatusForAccount:(id)fp8 status:(id)fp12;	// IMP=0x30bc7409
- (void)_validateAccount:(id)fp8;	// IMP=0x30bc6be9
- (void)_validateAccountInBackground:(id)fp8;	// IMP=0x30bc7545
- (id)account;	// IMP=0x30bc6bcd
- (BOOL)accountIsValid;	// IMP=0x30bc7641
- (BOOL)accountSupportsSSL;	// IMP=0x30bc7699
- (BOOL)accountValidationCanceled;	// IMP=0x30bc753d
- (void)cancelValidation;	// IMP=0x30bc6bd1
- (void)dealloc;	// IMP=0x30bc6b1d
- (id)error;	// IMP=0x30bc76e5
- (id)init;	// IMP=0x30bc6af5
- (void)setDelegate:(id)fp8;	// IMP=0x30bc6b9d
- (void)stop;	// IMP=0x30bc751d
- (void)validateAccount:(id)fp8;	// IMP=0x30bc6ba1

@end

