/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Connection.h>

@interface Connection (Gross)
- (id)_nssocket;	// IMP=0x30b9fc1d
@end

