/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/AuthScheme.h>

@interface CRAM_MD5AuthScheme : AuthScheme
{
}

- (Class)authenticatorClassForAccountClass:(Class)fp8;	// IMP=0x30bc0671
- (BOOL)canAuthenticateAccountClass:(Class)fp8 connection:(id)fp12;	// IMP=0x30bc06cd
- (BOOL)hasEncryption;	// IMP=0x30bc06c9
- (id)humanReadableName;	// IMP=0x30bc06a1
- (id)name;	// IMP=0x30bc0691
- (BOOL)sendsPlainTextPasswords;	// IMP=0x30bc06c5

@end

