/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPMessage.h>

@class MessageHeaders, NSData;

@interface IMAPMessageWithCache : IMAPMessage
{
    NSData *_messageData;
    MessageHeaders *_headers;
}

- (void)dealloc;	// IMP=0x30bbcb31
- (id)headerData;	// IMP=0x30bbcd21
- (id)headers;	// IMP=0x30bbccf1
- (BOOL)isMessageContentsLocallyAvailable;	// IMP=0x30bbccc9
- (id)messageData;	// IMP=0x30bbcb75
- (void)setHeaders:(id)fp8;	// IMP=0x30bbccf5
- (void)setMessageData:(id)fp8;	// IMP=0x30bbcbe9

@end

