/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class MessageStore, NSData, NSString;

@interface Message : NSObject
{
    MessageStore *_store;
    unsigned int _messageFlags;
    CDAnonymousStruct6 _flags;
    unsigned int _preferredEncoding;
    NSString *_senderAddressComment;
    unsigned int _dateSentInterval;
    unsigned int _dateReceivedInterval;
    NSString *_subject;
    unsigned char _subjectPrefixLength;
    NSString *_to;
    NSString *_cc;
    NSString *_sender;
    NSString *_contentType;
    NSData *_messageIDHeaderDigest;
    NSData *_inReplyToHeaderDigest;
    NSString *_summary;
}

+ (unsigned int)displayablePriorityForPriority:(int)fp8;	// IMP=0x30b5c275
+ (id)forwardedMessagePrefixWithSpacer:(BOOL)fp8;	// IMP=0x30b5bae5
+ (id)frameworkVersion;	// IMP=0x30b5b91d
+ (void)initialize;	// IMP=0x30b5b83d
+ (id)mailDirectory;	// IMP=0x30b5b9fd
+ (id)messageWithPersistentID:(id)fp8;	// IMP=0x30b5d10d
+ (id)messageWithRFC822Data:(id)fp8;	// IMP=0x30b5ba99
+ (id)productName;	// IMP=0x30b5b885
+ (id)replyPrefixWithSpacer:(BOOL)fp8;	// IMP=0x30b5bb55
+ (void)setUserAgent:(id)fp8;	// IMP=0x30b5b9e5
+ (id)userAgent;	// IMP=0x30b5b9f1
+ (unsigned int)validatePriority:(int)fp8;	// IMP=0x30b5c269
+ (id)verboseVersion;	// IMP=0x30b5b891
- (id)URL;	// IMP=0x30b5d3a9
- (void)_calculateAttachmentInfoFromBody:(id)fp8;	// IMP=0x30b5d269
- (id)_copyDateFromDateHeaderInHeaders:(id)fp8;	// IMP=0x30b5c511
- (id)_copyDateFromReceivedHeadersInHeaders:(id)fp8;	// IMP=0x30b5c405
- (BOOL)_doesDateAppearToBeSane:(id)fp8;	// IMP=0x30b5c3d1
- (id)_inReplyToHeaderDigestIvar;	// IMP=0x30b5c205
- (id)_messageIDHeaderDigestIvar;	// IMP=0x30b5c071
- (void)_setDateReceivedFromHeaders:(id)fp8;	// IMP=0x30b5c5f1
- (void)_setDateSentFromHeaders:(id)fp8;	// IMP=0x30b5c675
- (id)account;	// IMP=0x30b5d07d
- (id)bodyData;	// IMP=0x30b5d131
- (id)bodyDataIsComplete:(char *)fp8;	// IMP=0x30b5d159
- (id)cachedAttributes;	// IMP=0x30b5d365
- (void)calculateAttachmentInfoFromBody:(id)fp8;	// IMP=0x30b5d26b
- (id)cc;	// IMP=0x30b5cd6b
- (id)ccIfCached;	// IMP=0x30b5cd7b
- (BOOL)colorHasBeenEvaluated;	// IMP=0x30b5be45
- (id)contentType;	// IMP=0x30b5caef
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x30b5bbfd
- (id)dataForMimePart:(id)fp8;	// IMP=0x30b5d1b5
- (id)dataForMimePart:(id)fp8 inRange:(struct _NSRange)fp12 isComplete:(char *)fp20;	// IMP=0x30b5d1dd
- (id)dataForMimePart:(id)fp8 inRange:(struct _NSRange)fp12 isComplete:(char *)fp20 downloadIfNecessary:(BOOL)fp24 didDownload:(char *)fp28;	// IMP=0x30b5d21d
- (id)dateReceived;	// IMP=0x30b5c89d
- (double)dateReceivedAsTimeIntervalSince1970;	// IMP=0x30b5c9ab
- (id)dateSent;	// IMP=0x30b5c915
- (double)dateSentAsTimeIntervalSince1970;	// IMP=0x30b5ca5d
- (void)dealloc;	// IMP=0x30b5be5f
- (id)headerData;	// IMP=0x30b5d18d
- (id)headers;	// IMP=0x30b5bc3d
- (id)headersIfAvailable;	// IMP=0x30b5bc65
- (id)inReplyToHeaderDigest;	// IMP=0x30b5c0bf
- (id)init;	// IMP=0x30b5bbc5
- (BOOL)isMessageContentsLocallyAvailable;	// IMP=0x30b5c245
- (void)loadCachedHeaderValuesFromHeaders:(id)fp8;	// IMP=0x30b5d4e1
- (id)mailbox;	// IMP=0x30b5bc19
- (void)markAsForwarded;	// IMP=0x30b5d425
- (void)markAsNotViewed;	// IMP=0x30b5d49d
- (void)markAsReplied;	// IMP=0x30b5d461
- (void)markAsViewed;	// IMP=0x30b5d0a1
- (id)messageBody;	// IMP=0x30b5bca9
- (id)messageBodyIfAvailable;	// IMP=0x30b5bcd1
- (id)messageBodyIfAvailableUpdatingFlags:(BOOL)fp8;	// IMP=0x30b5bd2d
- (id)messageBodyUpdatingFlags:(BOOL)fp8;	// IMP=0x30b5bcf9
- (id)messageData;	// IMP=0x30b5be2d
- (id)messageDataIsComplete:(char *)fp8 downloadIfNecessary:(BOOL)fp12;	// IMP=0x30b5bd61
- (unsigned long)messageFlags;	// IMP=0x30b5bc8d
- (id)messageID;	// IMP=0x30b5bf29
- (id)messageIDHeaderDigest;	// IMP=0x30b5bf2d
- (unsigned int)messageSize;	// IMP=0x30b5befd
- (id)messageStore;	// IMP=0x30b5bc11
- (CDAnonymousStruct6)moreMessageFlags;	// IMP=0x30b5d059
- (BOOL)needsDateReceived;	// IMP=0x30b5ca29
- (BOOL)needsMessageIDHeader;	// IMP=0x30b5c0b1
- (unsigned int)numberOfAttachments;	// IMP=0x30b5c249
- (id)originalMailboxURL;	// IMP=0x30b5d0e9
- (id)path;	// IMP=0x30b5d079
- (id)persistentID;	// IMP=0x30b5d12d
- (id)preferredEmailAddressToReplyWith;	// IMP=0x30b5bf25
- (unsigned long)preferredEncoding;	// IMP=0x30b5c381
- (int)priority;	// IMP=0x30b5c319
- (id)references;	// IMP=0x30b5d03d
- (id)remoteID;	// IMP=0x30b5d041
- (id)remoteMailboxURL;	// IMP=0x30b5d0e5
- (id)sender;	// IMP=0x30b5cca1
- (id)senderAddressComment;	// IMP=0x30b5cccf
- (id)senderIfCached;	// IMP=0x30b5ccb1
- (void)setCc:(id)fp8;	// IMP=0x30b5cd8b
- (void)setColorHasBeenEvaluated:(BOOL)fp8;	// IMP=0x30b5be4f
- (void)setContentType:(id)fp8;	// IMP=0x30b5cb6d
- (void)setDateReceivedTimeIntervalSince1970:(double)fp8;	// IMP=0x30b5c98d
- (void)setDateSentTimeIntervalSince1970:(double)fp8;	// IMP=0x30b5cadd
- (void)setInReplyToHeaderDigest:(id)fp8;	// IMP=0x30b5c1e1
- (void)setMessageFlags:(unsigned long)fp8;	// IMP=0x30b5bc91
- (void)setMessageFlagsWithoutCommitting:(unsigned long)fp8;	// IMP=0x30b5bc95
- (void)setMessageIDHeaderDigest:(id)fp8;	// IMP=0x30b5c04d
- (void)setMessageInfo:(id)fp8 to:(id)fp12 cc:(id)fp16 sender:(id)fp20 dateReceivedTimeIntervalSince1970:(double)fp24 dateSentTimeIntervalSince1970:(double)fp32 messageIDHeaderDigest:(id)fp40 inReplyToHeaderDigest:(id)fp44 summary:(id)fp48;	// IMP=0x30b5cddb
- (void)setMessageInfoFromMessage:(id)fp8;	// IMP=0x30b5cf49
- (void)setMessageStore:(id)fp8;	// IMP=0x30b5bc15
- (void)setNumberOfAttachments:(unsigned int)fp8 isSigned:(BOOL)fp12 isEncrypted:(BOOL)fp16;	// IMP=0x30b5d321
- (void)setPreferredEncoding:(unsigned long)fp8;	// IMP=0x30b5c385
- (void)setPriorityFromHeaders:(id)fp8;	// IMP=0x30b5c299
- (void)setSender:(id)fp8;	// IMP=0x30b5ccc1
- (void)setSubject:(id)fp8;	// IMP=0x30b5c841
- (void)setSummary:(id)fp8;	// IMP=0x30b5cdcd
- (void)setTo:(id)fp8;	// IMP=0x30b5cd5d
- (id)subject;	// IMP=0x30b5c7ad
- (id)subjectAndPrefixLength:(unsigned int *)fp8;	// IMP=0x30b5c6f9
- (id)subjectNotIncludingReAndFwdPrefix;	// IMP=0x30b5c77d
- (id)summary;	// IMP=0x30b5cd99
- (id)to;	// IMP=0x30b5cd3d
- (id)toIfCached;	// IMP=0x30b5cd4d
- (unsigned long)uid;	// IMP=0x30b5d055
- (void)unlockedSetInReplyToHeaderDigest:(id)fp8;	// IMP=0x30b5c185
- (void)unlockedSetMessageIDHeaderDigest:(id)fp8;	// IMP=0x30b5bff1

@end

