/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface MessageDetails : NSObject
{
    unsigned int libraryID;
    unsigned int messageFlags;
    unsigned int uid;
    unsigned int encoding;
    BOOL isInvalid;
    int mailboxID;
    unsigned int dateReceived;
}

- (double)dateReceivedAsTimeIntervalSince1970;	// IMP=0x30baed0d
- (id)description;	// IMP=0x30baeba9
- (unsigned int)hash;	// IMP=0x30baeca9
- (id)init;	// IMP=0x30baec0d
- (BOOL)isEqual:(id)fp8;	// IMP=0x30baec41
- (unsigned int)libraryID;	// IMP=0x30baecd5
- (id)mailbox;	// IMP=0x30baeced
- (unsigned int)mailboxID;	// IMP=0x30baecd9
- (unsigned long)messageFlags;	// IMP=0x30baecdd
- (id)messageID;	// IMP=0x30baece1
- (id)remoteID;	// IMP=0x30baecc9
- (unsigned long)uid;	// IMP=0x30baec09

@end

