/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MimePart.h>

@interface MimePart (IMAPSupport)
- (BOOL)parseIMAPPropertyList:(id)fp8;	// IMP=0x30b6958d
- (id)partNumber;	// IMP=0x30b6ad35
@end

