/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@class NSMutableDictionary, NSMutableSet, NSString, NSTimer;

@interface NetworkController : NSObject
{
    struct __SCDynamicStore *_store;
    NSString *_domainName;
    NSMutableDictionary *_reachabilityObjects;
    NSMutableSet *_reachableHosts;
    unsigned int _waitingForDialToFinish:1;
    unsigned int _checkedNetwork:1;
    unsigned int _isNetworkUp:1;
    unsigned int _isFatPipe:1;
    unsigned int _edgeRequested:1;
    NSTimer *_notificationTimer;
}

+ (id)sharedInstance;	// IMP=0x30b96e29
- (id)IMEI;	// IMP=0x30b97a55
- (void)bringUpEdge;	// IMP=0x30b97b09
- (void)createReacher:(id)fp8;	// IMP=0x30b9739d
- (void)dealloc;	// IMP=0x30b96e81
- (id)domainName;	// IMP=0x30b97fb1
- (id)edgeInterfaceName;	// IMP=0x30b97a5f
- (id)init;	// IMP=0x30b97cb5
- (BOOL)isEdgeUp;	// IMP=0x30b97ab9
- (BOOL)isFatPipe;	// IMP=0x30b97215
- (BOOL)isHostReachable:(id)fp8;	// IMP=0x30b974d1
- (BOOL)isNetworkUp;	// IMP=0x30b96fad
- (void)keepEdgeUp;	// IMP=0x30b97b55
- (id)primaryEthernetAddressAsString;	// IMP=0x30b975d5
- (void)registerCTServerRunLoopSource;	// IMP=0x30b976d5

@end

