/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSMutableDictionary.h"

@interface NSMutableDictionary (RFC2231Support)
- (void)fixupRFC2231Values;	// IMP=0x30b70215
@end

