/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (PathUtils)
- (id)betterStringByResolvingSymlinksInPath;	// IMP=0x30b9ebf5
- (BOOL)isSubdirectoryOfPath:(id)fp8;	// IMP=0x30b9ea5d
- (BOOL)makeDirectoryWithMode:(int)fp8;	// IMP=0x30b9ea25
- (id)stringByReallyAbbreviatingWithTildeInPath;	// IMP=0x30b9eafd
@end

