/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface ObjectCache : NSObject
{
    unsigned int _arrayCapacity;
    struct __CFArray *_keysAndValues;
    BOOL _useIsEqual;
}

- (void)dealloc;	// IMP=0x30b9e715
- (id)initWithCapacity:(unsigned int)fp8;	// IMP=0x30b9e6e1
- (BOOL)isObjectInCache:(id)fp8;	// IMP=0x30b9e829
- (id)objectForKey:(id)fp8;	// IMP=0x30b9e781
- (void)removeAllObjects;	// IMP=0x30b9e819
- (void)removeObjectForKey:(id)fp8;	// IMP=0x30b9e89d
- (void)setCapacity:(unsigned int)fp8;	// IMP=0x30b9e749
- (void)setObject:(id)fp8 forKey:(id)fp12;	// IMP=0x30b9e919
- (void)setUsesIsEqualForComparison:(BOOL)fp8;	// IMP=0x30b9e77d

@end

