/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/POP3Connection.h>

@interface POP3Connection (PrivateCommands)
- (int)_apopWithUsername:(id)fp8 password:(id)fp12;	// IMP=0x30b5a515
- (int)_getStatusFromReply;	// IMP=0x30b5b0f9
- (int)_pass:(id)fp8;	// IMP=0x30b5a641
- (int)_readMultilineResponseWithMaxSize:(int)fp8 informDelegate:(BOOL)fp12 consumer:(id)fp16;	// IMP=0x30b5a281
- (int)_sendCommand:(const char *)fp8 withArguments:(id)fp12;	// IMP=0x30b5a6f1
- (int)_user:(id)fp8;	// IMP=0x30b5a605
- (id)copyReplyLineData;	// IMP=0x30b5a479
- (void)getTop:(int)fp8 ofMessageNumber:(unsigned long)fp12 intoMutableData:(id)fp16;	// IMP=0x30b5a149
@end

