/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/YahooAccount.h>

@interface YahooAccount (Internal)
- (id)devtypeParameter;	// IMP=0x30bc590d
- (id)yahooParameterForKey:(id)fp8;	// IMP=0x30bc495d
@end

