/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface FunctionDescriptor : NSObject
{
    NSString *name;	// 4 = 0x4
    unsigned int tag;	// 8 = 0x8
    int type;	// 12 = 0xc
    void *preCallRelay;	// 16 = 0x10
    int preCallRelayLength;	// 20 = 0x14
    void *postCallRelay;	// 24 = 0x18
    int postCallRelayLength;	// 28 = 0x1c
    void *context;	// 32 = 0x20
    int contextLength;	// 36 = 0x24
    struct _NSRange addrRange;	// 40 = 0x28
    struct _NSRange preCallRelayAddrRange;	// 48 = 0x30
    struct _NSRange postCallRelayAddrRange;	// 56 = 0x38
    struct _NSRange calloutAddrRange;	// 64 = 0x40
    unsigned int contextAddr;	// 72 = 0x48
}

- (void)dealloc;	// IMP=0x318995dc
- (void)encodeWithCoder:(id)fp8;	// IMP=0x31899738
- (unsigned int)hash;	// IMP=0x3189963c
- (id)initWithCoder:(id)fp8;	// IMP=0x3189987c
- (id)initWithFunctionName:(id)fp8;	// IMP=0x31899588
- (BOOL)isEqual:(id)fp8;	// IMP=0x31899668
- (id)name;	// IMP=0x31899634

@end

