/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMachOTaskImage, NSString;

@interface NSMachODyldSecrets : NSObject
{
    unsigned int _task;	// 4 = 0x4
    struct {
        unsigned int object_images_address;
        unsigned int library_images_address;
        unsigned int gdb_nobject_images;
        unsigned int gdb_object_image_size;
        unsigned int gdb_nlibrary_images;
        unsigned int gdb_library_image_size;
        unsigned int gdb_object_images_size;
        unsigned int gdb_library_images_size;
    } _dyldState;	// 8 = 0x8
    struct {
        unsigned int dyld_all_image_infos_address;
        struct dyld_all_image_infos dyld_all_image_infos;
    } _dyldState64;	// 40 = 0x28
    unsigned int _preferredDyldStart;	// 64 = 0x40
    unsigned int _dyldStart;	// 68 = 0x44
    int _dyldSlide;	// 72 = 0x48
    unsigned int _dyldLength;	// 76 = 0x4c
    NSMachOTaskImage *_taskImage;	// 80 = 0x50
    NSString *_dyldName;	// 84 = 0x54
    NSString *_executablesPath;	// 88 = 0x58
    BOOL _mustSwap;	// 92 = 0x5c
    BOOL _is64Bit;	// 93 = 0x5d
    BOOL _usesAllImageInfos;	// 94 = 0x5e
}

+ (unsigned int)getDyldAllImageInfos:(id)fp8;	// IMP=0x3188f7f4
+ (void)initialize;	// IMP=0x3188f3d4
- (unsigned int *)addressOfNImagesInLibraryImages:(unsigned int)fp8;	// IMP=0x31890064
- (unsigned int *)addressOfNImagesInObjectImages:(unsigned int)fp8;	// IMP=0x31890054
- (unsigned int *)addressOfNextImagesInLibraryImages:(unsigned int)fp8;	// IMP=0x31890088
- (unsigned int *)addressOfNextImagesInObjectImages:(unsigned int)fp8;	// IMP=0x31890074
- (void)dealloc;	// IMP=0x3188ff3c
- (BOOL)doesDyldStartAtAddress:(unsigned int)fp8;	// IMP=0x3188f434
- (struct dyld_all_image_infos *)dyldImageInfos;	// IMP=0x3189009c
- (id)dyldName;	// IMP=0x31890450
- (id)dyldNameStartingAtAddress:(unsigned int)fp8 returnsArch:(int *)fp12;	// IMP=0x3189047c
- (struct _NSRange)dyldRange;	// IMP=0x318900b0
- (id)executablesPath;	// IMP=0x31890458
- (void)finalize;	// IMP=0x3188ffa8
- (id)findMachHeadersForTask;	// IMP=0x3189092c
- (void)free_dyldState64_contents;	// IMP=0x3188fedc
- (id)initWithTask:(unsigned int)fp8 image:(id)fp12 checkSwapped:(BOOL)fp16;	// IMP=0x3188f83c
- (unsigned int)libraryImageSize;	// IMP=0x31890024
- (unsigned int)libraryImagesAddress;	// IMP=0x31890004
- (unsigned int)libraryImagesSize;	// IMP=0x31890034
- (struct image *)nthImage:(int)fp8 inLibraryImages:(unsigned int)fp12;	// IMP=0x31890048
- (struct image *)nthImage:(int)fp8 inObjectImages:(unsigned int)fp12;	// IMP=0x3189003c
- (int)numberOfLibraryImagesPerGroup;	// IMP=0x31890014
- (int)numberOfMachHeadersInTask;	// IMP=0x318900c0
- (int)numberOfObjectImagesPerGroup;	// IMP=0x3189000c
- (unsigned int)objectImageSize;	// IMP=0x3189001c
- (unsigned int)objectImagesAddress;	// IMP=0x3188fffc
- (unsigned int)objectImagesSize;	// IMP=0x3189002c
- (unsigned int)startOfDyldProbablyAt:(unsigned int)fp8;	// IMP=0x3188f728

@end

