/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface TraceSymbol : NSObject
{
    unsigned int address;	// 4 = 0x4
    NSString *name;	// 8 = 0x8
    NSString *library;	// 12 = 0xc
    NSString *filename;	// 16 = 0x10
    int lineNumber;	// 20 = 0x14
}

- (id)filename;	// IMP=0x318a8ffc
- (id)initWithCString:(char *)fp8 length:(int)fp12 withLine:(int)fp16;	// IMP=0x318ab388
- (id)initWithPC:(unsigned int)fp8 withImageSymbols:(id)fp12;	// IMP=0x318ab2d4
- (id)library;	// IMP=0x318a8ff4
- (int)lineNumber;	// IMP=0x318a9004
- (id)name;	// IMP=0x318a8fec
- (BOOL)readFromFile:(struct __sFILE *)fp8;	// IMP=0x318a9010
- (void)writeToFile:(struct __sFILE *)fp8;	// IMP=0x318a900c

@end

