/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <TelephonyUI/TPBottomButtonBar.h>

@class TPPushButton;

@interface TPBottomDualButtonBar : TPBottomButtonBar
{
    TPPushButton *_button2;
    unsigned int _drawSeparator:1;
}

- (float)_buttonWidth;	// IMP=0x32638b64
- (void)_updateButtonSettings:(id)fp8;	// IMP=0x32638bdc
- (id)button2;	// IMP=0x32638ca0
- (void)dealloc;	// IMP=0x32638b0c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32638cec
- (id)initForCallFailureWithFrame:(struct CGRect)fp8;	// IMP=0x3263886c
- (id)initForEmergencyCallWithFrame:(struct CGRect)fp8;	// IMP=0x32639168
- (id)initForIncomingCallWithFrame:(struct CGRect)fp8;	// IMP=0x32639454
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x326387f4
- (void)setButton2:(id)fp8;	// IMP=0x32638efc
- (void)setButton:(id)fp8;	// IMP=0x32639038
- (void)setDrawsSeparateWells:(BOOL)fp8;	// IMP=0x32638ca8

@end

