/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface TPBottomBar : UIView
{
}

+ (id)_backgroundImage;	// IMP=0x32638530
+ (float)defaultHeight;	// IMP=0x326385e0
+ (void)preloadImages;	// IMP=0x326385c4
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3263871c
- (id)initWithDefaultSize;	// IMP=0x326385f4
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32638694

@end

