/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class TPPushButton;

@interface TPCallWaitingButton : UIThreePartButton
{
    TPPushButton *_innerButton;
    unsigned int _type:1;
}

+ (struct CGSize)defaultSizeForType:(int)fp8;	// IMP=0x3263cfec
+ (float)defaultVerticalCenteringOffset;	// IMP=0x3263d0c8
- (void)addTarget:(id)fp8 action:(SEL)fp12 forEvents:(int)fp16;	// IMP=0x3263d4cc
- (void)dealloc;	// IMP=0x3263d474
- (id)initBottomForIncomingCallWaiting;	// IMP=0x3263d804
- (id)initBottomForSecondIncomingCallWaiting;	// IMP=0x3263d678
- (id)initBottomForTTYWithTitle:(id)fp8;	// IMP=0x3263d564
- (id)initTopForIncomingCallWaiting;	// IMP=0x3263d378
- (id)initTopForTTY;	// IMP=0x3263d950
- (id)initWithFrame:(struct CGRect)fp8 type:(int)fp24;	// IMP=0x3263d0d4
- (BOOL)isEnabled;	// IMP=0x3263d540
- (void)removeTarget:(id)fp8 forEvents:(int)fp12;	// IMP=0x3263d4fc
- (void)setEnabled:(BOOL)fp8;	// IMP=0x3263d51c

@end

