/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class NSString, NSTimer;

@interface TPLockTextView : UIView
{
    NSString *_label;
    struct CGImage *_textCache;
    char *_textData;
    NSTimer *_maskTimer;
    double _maskStartTime;
    struct __GSFont *_labelFont;
    float _fps;
}

- (void)_cacheLabel:(id)fp8 size:(struct CGSize)fp12;	// IMP=0x326397d8
- (void)dealloc;	// IMP=0x3263973c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32639c44
- (id)initWithLabel:(id)fp8 fontSize:(float)fp12;	// IMP=0x3263991c
- (BOOL)isAnimating;	// IMP=0x32639c34
- (id)label;	// IMP=0x32639a84
- (void)setFPS:(float)fp8;	// IMP=0x32639bd0
- (void)startAnimation;	// IMP=0x32639a8c
- (void)stopAnimation;	// IMP=0x32639b80

@end

