/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@interface TPPhonePad : UIControl
{
    int _downKey;
    id _delegate;
    BOOL _playsSounds;
    float _topHeight;
    float _midHeight;
    float _bottomHeight;
    float _leftWidth;
    float _midWidth;
    float _rightWidth;
    struct __CFSet *_inflightSounds;
    struct __CFDictionary *_keyToButtonMap;
    unsigned int _soundsActivated:1;
}

+ (void)_delayedDeactivate;	// IMP=0x3263b51c
+ (BOOL)launchFieldTestIfNeeded:(id)fp8;	// IMP=0x3263b2c8
+ (BOOL)shouldStringAutoDial:(id)fp8 givenLastChar:(BOOL)fp12;	// IMP=0x3263b150
- (void)_activateSounds:(BOOL)fp8;	// IMP=0x3263b578
- (void)_appResumed;	// IMP=0x3263b788
- (void)_appSuspended;	// IMP=0x3263b768
- (void)_handleKey:(id)fp8 forEvent:(struct __GSEvent *)fp12;	// IMP=0x3263c304
- (void)_handleKeyPressAndHold:(id)fp8;	// IMP=0x3263c60c
- (int)_keyForPoint:(struct CGPoint)fp8;	// IMP=0x3263c714
- (id)_keypadImage;	// IMP=0x3263bce0
- (void)_playSoundForKey:(int)fp8;	// IMP=0x3263ca50
- (id)_pressedImage;	// IMP=0x3263bc14
- (struct CGRect)_rectForKey:(int)fp8;	// IMP=0x3263c8a0
- (void)_stopAllSounds;	// IMP=0x3263cadc
- (void)_stopSoundForKey:(int)fp8;	// IMP=0x3263ca94
- (float)_yFudge;	// IMP=0x3263bdc0
- (BOOL)cancelMouseTracking;	// IMP=0x3263c1f8
- (void)dealloc;	// IMP=0x3263b45c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3263bdcc
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3263c070
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3263b338
- (void)movedFromWindow:(id)fp8;	// IMP=0x3263b7b4
- (void)movedToWindow:(id)fp8;	// IMP=0x3263b810
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3263c068
- (void)removeFromSuperview;	// IMP=0x3263b710
- (void)setButton:(id)fp8 forKeyAtIndex:(int)fp12;	// IMP=0x3263bac0
- (void)setDelegate:(id)fp8;	// IMP=0x3263b878
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x3263c108
- (void)setNeedsDisplayForKey:(int)fp8;	// IMP=0x3263bba8
- (void)setPlaysSounds:(BOOL)fp8;	// IMP=0x3263b880

@end

