/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet;

@interface AVObjectRegistry : NSObject
{
    NSMutableSet *_objSet;
}

+ (id)defaultObjectRegistry;	// IMP=0x3029c294
- (void)dealloc;	// IMP=0x3029c360
- (id)init;	// IMP=0x3029c2e8
- (BOOL)isObjectRegistered:(id)fp8;	// IMP=0x3029c448
- (BOOL)isObjectValueRegistered:(id)fp8;	// IMP=0x3029c494
- (void)registerObject:(id)fp8;	// IMP=0x3029c3b8
- (void)safeInvokeWithDescription:(id)fp8;	// IMP=0x3029c4b8
- (void)safePerformOnMainThreadTarget:(id)fp8 selector:(SEL)fp12 object:(id)fp16;	// IMP=0x3029c598
- (void)unregisterObject:(id)fp8;	// IMP=0x3029c400

@end

