/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface AVTimeMarkerObservation : NSObject
{
    id _observer;
    NSArray *_times;
    id _context;
    int _currentIndex;
}

- (id)context;	// IMP=0x3028e280
- (int)currentIndex;	// IMP=0x3028e288
- (void)dealloc;	// IMP=0x3028e06c
- (BOOL)gotoTime:(double)fp8;	// IMP=0x3028e0d4
- (id)initWithObserver:(id)fp8 times:(id)fp12 context:(id)fp16 currentIndex:(int)fp20;	// IMP=0x3028dfe0
- (double)nextInterestingTime;	// IMP=0x3028e194
- (id)observer;	// IMP=0x3028e278
- (double)prevInterestingTime;	// IMP=0x3028e204

@end

