/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface CodeLog : NSObject
{
}

+ (void)decrimentIndent;	// IMP=0x30294724
+ (id)dispenseLine;	// IMP=0x30294784
+ (void)doLogLines;	// IMP=0x302942b4
+ (void)incrementIndent;	// IMP=0x302946bc
+ (id)lineQueue;	// IMP=0x30294148
+ (void)logCode:(id)fp8;	// IMP=0x30294634
+ (void)logCode:(id)fp8 forLine:(id)fp12;	// IMP=0x30294678
+ (void)logLines;	// IMP=0x302945f8
+ (void)logString:(id)fp8;	// IMP=0x3029419c

@end

