/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface fmpcDummyThreadInvoker : NSObject
{
}

+ (void)invokeThread:(id)fp8;	// IMP=0x3029dec4

@end

