/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

#if 0
#import "LibrarySourceProtocol.h"
#import "StabsSourceProtocol.h"
#import "SymbolSourceProtocol.h"
#endif

@class MemoryCache, NSMutableArray, NSMutableDictionary, NSNonOverlappingRangeValueTable;

@interface NSMachOImage : NSObject // <SymbolSource, StabsSource, LibrarySource>
{
    NSMutableArray *_machHeaders;	// 4 = 0x4
    NSMutableArray *_pefHeaders;	// 8 = 0x8
    int _numberOfMachHeaders;	// 12 = 0xc
    int _numberOfPEFHeaders;	// 16 = 0x10
    NSNonOverlappingRangeValueTable *_machHeaderRangeMap;	// 20 = 0x14
    NSNonOverlappingRangeValueTable *_pefHeaderRangeMap;	// 24 = 0x18
    MemoryCache *_memoryCache;	// 28 = 0x1c
    NSMutableDictionary *_imageSignature;	// 32 = 0x20
}

+ (void)initialize;	// IMP=0x318813bc
- (void)addHeader:(id)fp8;	// IMP=0x318815d4
- (unsigned int)addressOfOneSymbolWithCName:(const char *)fp8;	// IMP=0x318829d4
- (unsigned int)addressOfOneSymbolWithCName:(const char *)fp8 inLibrary:(id)fp12;	// IMP=0x318829f4
- (unsigned int)addressOfSymbolWithCName:(const char *)fp8;	// IMP=0x31882940
- (unsigned int)addressOfSymbolWithCName:(const char *)fp8 inLibrary:(const char *)fp12;	// IMP=0x3188285c
- (struct _NSRange)addressRangeOfOneSymbolWithAddress:(unsigned int)fp8;	// IMP=0x318830a4
- (struct _NSRange)addressRangeOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x318827a4
- (struct _NSRange)addressRangeOfSymbolWithCName:(const char *)fp8;	// IMP=0x31882fc4
- (id)allHeaders;	// IMP=0x31881d44
- (const char *)cnameOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x31882b0c
- (void)dealloc;	// IMP=0x31881508
- (void)finalize;	// IMP=0x31881594
- (void)flushHeaders;	// IMP=0x318826c0
- (void)forceNonLazyLoadOfAllSymbols;	// IMP=0x31882628
- (id)getMachHeaders;	// IMP=0x31881d34
- (id)imageSignature;	// IMP=0x31881dd0
- (id)init;	// IMP=0x31881420
- (id)libraryForPC:(unsigned int)fp8;	// IMP=0x31882c3c
- (id)libraryRangesForLibrary:(id)fp8;	// IMP=0x31882cf4
- (id)libraryRangesForPC:(unsigned int)fp8;	// IMP=0x31882c98
- (id)memoryCache;	// IMP=0x3188279c
- (id)pefHeaders;	// IMP=0x31881d3c
- (struct stabInfo *)sourceLocationOfAddress:(unsigned int)fp8;	// IMP=0x31882b9c
- (struct stabInfo *)sourceLocationsOfAddressRange:(struct _NSRange)fp8;	// IMP=0x31882c2c
- (BOOL)sourceLocationsOfAddressRange:(struct _NSRange)fp8 stabsInfo:(struct stabInfo *)fp16;	// IMP=0x31882c34
- (struct _NSRange)sourceRangeForAddress:(unsigned int)fp8;	// IMP=0x31882f0c
- (void)updateHeaders;	// IMP=0x31882798

@end

