/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <vmutils/NSBinaryHeader.h>

@class NSMutableDictionary, NSString, RangeArray, xSYMImage;

@interface NSPEFHeader : NSBinaryHeader
{
    RangeArray *_range;	// 12 = 0xc
    NSString *_libraryName;	// 16 = 0x10
    xSYMImage *_xSYM;	// 20 = 0x14
    unsigned int _xSYM_offset;	// 24 = 0x18
    NSMutableDictionary *_sourceFileNameDict;	// 28 = 0x1c
    RangeArray *_noTBTblRanges;	// 32 = 0x20
    void *lastMTE;	// 36 = 0x24
    struct stabInfo *tmpStabInfoArray;	// 40 = 0x28
    unsigned long maxTmpStabInfo;	// 44 = 0x2c
}

- (struct _NSRange)addressRangeOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x31893704
- (const char *)cnameOfSymbolWithAddress:(unsigned int)fp8;	// IMP=0x3189388c
- (void)dealloc;	// IMP=0x31892898
- (id)description;	// IMP=0x31892a80
- (void)finalize;	// IMP=0x31892934
- (struct TracebackTbl *)findPEFTracebackTbl:(unsigned int)fp8 direction:(int)fp12 tableAddr:(unsigned int *)fp16 tableSize:(int *)fp20;	// IMP=0x31892b28
- (BOOL)hasSourceInfo;	// IMP=0x31893044
- (BOOL)hasSymbolInfo;	// IMP=0x3189303c
- (id)initInImage:(id)fp8;	// IMP=0x3189281c
- (id)libraryRanges;	// IMP=0x31892a5c
- (id)name;	// IMP=0x31892a54
- (struct _NSRange)range;	// IMP=0x31892a18
- (void)setRange:(struct _NSRange)fp8 name:(id)fp16;	// IMP=0x31892988
- (void)setxSYM:(id)fp8;	// IMP=0x31892f9c
- (struct stabInfo *)sourceLocationOfAddress:(unsigned int)fp8;	// IMP=0x31893054
- (struct _NSRange)sourceRangeForAddress:(unsigned int)fp8;	// IMP=0x3189358c
- (id)symbolRanges;	// IMP=0x31892a64

@end

