/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/AVControllerLog.h>

@interface AVControllerLog (AVControllerLog_Celeste)
- (void)setVibrationEnabled:(BOOL)fp8;	// IMP=0x30295ec4
- (void)setVibrationPattern:(id)fp8;	// IMP=0x30295ee8
- (BOOL)vibrationEnabled;	// IMP=0x30295ea0
- (id)vibrationPattern;	// IMP=0x30295f08
@end

