/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/AVController.h>

@interface AVController (AVController_Celeste)
- (void)setVibrationEnabled:(BOOL)fp8;	// IMP=0x30295d9c
- (void)setVibrationPattern:(id)fp8;	// IMP=0x30295de8
- (BOOL)vibrationEnabled;	// IMP=0x30295d8c
- (id)vibrationPattern;	// IMP=0x30295e6c
@end

