/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class AVByteStream, AVExternalAudioDelegate, AVRefMovieParser, LKLayer, NSDictionary, NSMutableDictionary, NSString, NSURL;

struct AVControllerPrivate {
    id _field1;
    id _field2;
    id _field3;
    id _field4;
    id _field5;
    id _field6;
    id _field7;
    char _field8;
    Class _field9;
    id _field10;
    int _field11;
    struct _NSSize _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
    float _field17;
    int _field18;
    id _field19;
    struct _LKImageQueue *_field20;
    struct OpaqueFigVisualContext *_field21;
    id _field22;
    struct __CFRunLoop *_field23;
    unsigned int _field24;
    int _field25;
    int _field26;
    int _field27;
    char _field28;
    char _field29;
    char _field30;
    char _field31;
    char _field32;
    id _field33;
    int _field34;
    int _field35;
    id _field36;
    char _field37;
    char _field38;
    char _field39;
    struct opaqueFigMoviePlaybackRef *_field40;
    id _field41;
    char _field42;
    struct opaqueFigMoviePlaybackRef *_field43;
    struct FMPlaybackProcPtrs _field44;
    id _field45;
    struct __CFRunLoop *_field46;
    char _field47;
    id _field48;
};

struct AVExternalAudioPrivate {
    char _field1;
    struct FMPlaybackProcPtrs _field2;
    AVExternalAudioDelegate *_field3;
    char _field4;
};

struct AVFileValidatorPrivate {
    NSString *_field1;
    AVByteStream *_field2;
    AVRefMovieParser *_field3;
    struct FigOpaqueFileCheck *_field4;
    struct FigFileCheckDataLocation _field5;
};

struct AVItemPrivate {
    id _field1;
    NSString *_field2;
    double _field3;
    float _field4;
    float _field5;
    float _field6;
    unsigned int _field7;
    char _field8;
    char _field9;
    NSDictionary *_field10;
    int _field11;
    long long _field12;
    long long _field13;
};

struct AVLayerSynchronizerPrivate {
    struct OpaqueFigReentrantMutex *_field1;
    struct TimebaseSyncMoment _field2;
    char _field3;
    double _field4;
    double _field5;
    LKLayer *_field6;
    unsigned char _field7;
};

struct AVRecorderPrivate {
    NSURL *_field1;
    unsigned int _field2;
    unsigned int _field3;
    NSMutableDictionary *_field4;
    long long _field5;
    char _field6;
    struct AudioStreamBasicDescription _field7;
    struct OpaqueAudioFileID *_field8;
    struct OpaqueAudioQueue *_field9;
    unsigned int _field10;
    struct AudioQueueLevelMeterState *_field11;
    struct AudioQueueLevelMeterState *_field12;
    unsigned int _field13;
    unsigned int _field14;
    unsigned int _field15;
    struct AudioQueueBuffer *_field16[3];
    char _field17[3];
    char _field18;
    char _field19;
    char _field20;
    struct FMPlaybackProcPtrs _field21;
};

struct AVSystemControllerPrivate {
    char _field1;
    struct FMPlaybackProcPtrs _field2;
};

struct AudioQueueBuffer {
    unsigned int _field1;
    void *_field2;
    unsigned int _field3;
    void *_field4;
};

struct AudioQueueLevelMeterState;

struct AudioStreamBasicDescription {
    double mSampleRate;
    unsigned int mFormatID;
    unsigned int mFormatFlags;
    unsigned int mBytesPerPacket;
    unsigned int mFramesPerPacket;
    unsigned int mBytesPerFrame;
    unsigned int mChannelsPerFrame;
    unsigned int mBitsPerChannel;
    unsigned int mReserved;
};

struct AudioStreamPacketDescription {
    long long _field1;
    unsigned int _field2;
    unsigned int _field3;
};

struct AudioTimeStamp {
    double _field1;
    unsigned long long _field2;
    double _field3;
    unsigned long long _field4;
    struct SMPTETime _field5;
    unsigned int _field6;
    unsigned int _field7;
};

struct CGSize {
    float _field1;
    float _field2;
};

struct FMPlaybackProcPtrs {
    int version;
    struct opaqueFigMoviePlaybackConnectionRef *connectionRef;
    void *releaseProcPtrs;
    void *createWithPath;
    void *release;
    void *copyAttribute;
    void *setAttribute;
    void *prepareForPlayback;
    void *setMovieVolume;
    void *getMovieVolume;
    void *setMuted;
    void *getMuted;
    void *setEQPreset;
    void *getEQPreset;
    void *setRate;
    void *getRate;
    void *setCurrentTime;
    void *getCurrentTime;
    void *getDimensions;
    void *getDuration;
    void *addItemToReadCache;
    void *flushReadCache;
    void *prepareForPlaybackServer;
    void *beginInterruption;
    void *endInterruption;
    void *setRateWithFade;
    void *setConnectionActive;
    void *abortSetCurrentTime;
};

struct FigFileCheckDataLocation {
    unsigned long long offset;
    unsigned long long size;
};

struct FigOpaqueFileCheck;

struct OpaqueAudioFileID;

struct OpaqueAudioQueue;

struct OpaqueFigByteFlume;

struct OpaqueFigByteStream;

struct OpaqueFigCachedByteStream;

struct OpaqueFigReentrantMutex;

struct OpaqueFigScheduledIO;

struct OpaqueFigVisualContext;

struct SMPTETime {
    short _field1;
    short _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    short _field6;
    short _field7;
    short _field8;
    short _field9;
};

struct TimebaseSyncMoment {
    unsigned int size;
    unsigned int flags;
    double effectiveRate;
    struct {
        long long _field1;
        int _field2;
        long long _field3;
        unsigned int _field4;
    } currentTime;
    struct {
        long long _field1;
        int _field2;
        long long _field3;
        unsigned int _field4;
    } hostTime;
    double clockRateScaler;
};

struct _LKImageQueue;

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSSize {
    float width;
    float height;
};

struct __CFRunLoop;

struct __CVBuffer;

struct opaqueFigMoviePlaybackConnectionRef;

struct opaqueFigMoviePlaybackRef;

typedef struct {
    long long value;
    int timescale;
    long long epoch;
    unsigned int flags;
} CDAnonymousStruct1;

