/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/AVQueueFeeder.h>

@class NSMutableArray;

@interface AVArrayQueueFeeder : AVQueueFeeder
{
    NSMutableArray *_items;
}

- (void)dealloc;	// IMP=0x3027f20c
- (id)init;	// IMP=0x3027f12c
- (id)initWithArray:(id)fp8;	// IMP=0x3027f1a4
- (void)insertObject:(id)fp8 atIndex:(unsigned int)fp12;	// IMP=0x3027f38c
- (unsigned int)numberOfPaths;	// IMP=0x3027f264
- (id)pathAtIndex:(unsigned int)fp8;	// IMP=0x3027f284
- (void)removeObjectAtIndex:(unsigned int)fp8;	// IMP=0x3027f498
- (void)shuffleWithCurrentIndex:(unsigned int)fp8;	// IMP=0x3027f3e0

@end

