/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface AVByteStream : NSObject
{
    NSString *_path;
    struct OpaqueFigScheduledIO *_networkSource;
    struct OpaqueFigCachedByteStream *_crabs;
    struct OpaqueFigByteFlume *_uncachedSource;
    struct OpaqueFigByteStream *_fileStream;
}

- (void)cancel;	// IMP=0x302a3654
- (struct OpaqueFigCachedByteStream *)crabs;	// IMP=0x302a3660
- (void)dealloc;	// IMP=0x302a3210
- (struct OpaqueFigByteStream *)figByteStream;	// IMP=0x302a3658
- (id)initWithPath:(id)fp8;	// IMP=0x302a3194
- (void)open;	// IMP=0x302a34b4
- (void)openComplete:(id)fp8;	// IMP=0x302a32b8

@end

