/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/ObjectWrapper.h>

@interface AVControllerLog : ObjectWrapper
{
}

- (id)attributeForKey:(id)fp8;	// IMP=0x3028fb38
- (BOOL)beginInterruption:(id *)fp8;	// IMP=0x30290600
- (id)currentItem;	// IMP=0x3028f9cc
- (double)currentTime;	// IMP=0x3028f384
- (id)delegate;	// IMP=0x3028e5e4
- (void)endInterruptionWithStatus:(id)fp8;	// IMP=0x30290770
- (int)eqPreset;	// IMP=0x3028f840
- (unsigned int)indexOfCurrentQueueFeederItem;	// IMP=0x30290540
- (id)init;	// IMP=0x3028e290
- (id)initWithQueue:(id)fp8 error:(id *)fp12;	// IMP=0x3028e3c0
- (BOOL)muted;	// IMP=0x3028f6b4
- (void)pause;	// IMP=0x3028ef18
- (BOOL)play:(id *)fp8;	// IMP=0x3028eda8
- (BOOL)playNextItem:(id *)fp8;	// IMP=0x3028efc8
- (id)queue;	// IMP=0x3028e9fc
- (id)queueFeeder;	// IMP=0x302902fc
- (float)rate;	// IMP=0x3028f138
- (void)registerTimeMarkerObserver:(id)fp8 forItem:(id)fp12 times:(id)fp16 context:(id)fp20;	// IMP=0x302909cc
- (int)repeatMode;	// IMP=0x3028ece8
- (BOOL)resumePlayback:(double)fp8 error:(id *)fp16;	// IMP=0x3029083c
- (void)setAVItemClass:(Class)fp8;	// IMP=0x3028eb54
- (BOOL)setAttribute:(id)fp8 forKey:(id)fp12 error:(id *)fp16;	// IMP=0x3028fc0c
- (void)setCurrentTime:(double)fp8;	// IMP=0x3028f44c
- (void)setDelegate:(id)fp8;	// IMP=0x3028e70c
- (void)setEQPreset:(int)fp8;	// IMP=0x3028f900
- (BOOL)setIndexOfCurrentQueueFeederItem:(unsigned int)fp8 error:(id *)fp12;	// IMP=0x302903c4
- (void)setMuted:(BOOL)fp8;	// IMP=0x3028f774
- (void)setQueue:(id)fp8;	// IMP=0x3028e8e8
- (void)setQueueFeeder:(id)fp8;	// IMP=0x30290120
- (BOOL)setRate:(float)fp8 error:(id *)fp12;	// IMP=0x3028f1f8
- (BOOL)setRepeatMode:(int)fp8;	// IMP=0x3028ec14
- (void)setVolume:(float)fp8;	// IMP=0x3028f5e0
- (void)unregisterTimeMarkerObserver:(id)fp8 forItem:(id)fp12;	// IMP=0x30290de4
- (float)volume;	// IMP=0x3028f520

@end

