/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface AVExternalAudio : NSObject
{
    struct AVExternalAudioPrivate *_priv;
}

+ (id)avExternalAudio:(id)fp8;	// IMP=0x3029cce0
- (BOOL)activate:(id *)fp8;	// IMP=0x3029d92c
- (id)attributeForKey:(id)fp8;	// IMP=0x3029d1bc
- (void)dealloc;	// IMP=0x3029cfe0
- (void)fmpChangeConnectionActive:(BOOL)fp8;	// IMP=0x3029dc20
- (void)fmpServerConnectionDied;	// IMP=0x3029d888
- (void)fmpUserVolumeDidChange;	// IMP=0x3029db40
- (id)initWithDelegate:(id)fp8;	// IMP=0x3029cd24
- (BOOL)isActive;	// IMP=0x3029da30
- (void)makeError:(id *)fp8 withDescription:(id)fp12 code:(long)fp16;	// IMP=0x3029d71c
- (BOOL)okToNotifyFromThisThread;	// IMP=0x3029d900
- (void)postServerConnectionDiedNotification:(id)fp8;	// IMP=0x3029d7e4
- (void)postUserVolumeChangedNotification:(id)fp8;	// IMP=0x3029da3c
- (BOOL)setAttribute:(id)fp8 forKey:(id)fp12 error:(id *)fp16;	// IMP=0x3029d228
- (float)volume;	// IMP=0x3029d9c0

@end

