/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface AVItem : NSObject
{
    struct AVItemPrivate *_priv;
}

+ (id)avItem;	// IMP=0x3027d45c
+ (id)avItemWithPath:(id)fp8 error:(id *)fp12;	// IMP=0x3027d498
- (int)_instantiateItem;	// IMP=0x3027d824
- (id)attributeForKey:(id)fp8;	// IMP=0x3027da28
- (void)dealloc;	// IMP=0x3027d668
- (double)duration;	// IMP=0x3027d860
- (int)eqPreset;	// IMP=0x3027da1c
- (id)init;	// IMP=0x3027d5bc
- (id)initWithError:(id *)fp8;	// IMP=0x3027d4e4
- (id)initWithPath:(id)fp8 error:(id *)fp12;	// IMP=0x3027d5dc
- (struct CGSize)naturalSize;	// IMP=0x3027d8c0
- (id)path;	// IMP=0x3027d82c
- (BOOL)setAttribute:(id)fp8 forKey:(id)fp12 error:(id *)fp16;	// IMP=0x3027dd94
- (void)setEQPreset:(int)fp8;	// IMP=0x3027d9b8
- (BOOL)setPath:(id)fp8 error:(id *)fp12;	// IMP=0x3027d6e8
- (void)setVolume:(float)fp8;	// IMP=0x3027d954
- (float)volume;	// IMP=0x3027d948

@end

