/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSRecursiveLock;

@interface AVQueue : NSObject
{
    NSRecursiveLock *_mutex;
    NSMutableArray *_items;
    void *_reserved;
    unsigned int _flags;
}

+ (id)avQueue;	// IMP=0x3027e198
+ (id)queueWithArray:(id)fp8 error:(id *)fp12;	// IMP=0x3027e1dc
- (int)_instantiateItem;	// IMP=0x3027e424
- (BOOL)appendItem:(id)fp8 error:(id *)fp12;	// IMP=0x3027e670
- (BOOL)appendItemsFromArray:(id)fp8 error:(id *)fp12;	// IMP=0x3027e5c8
- (void)dealloc;	// IMP=0x3027e378
- (unsigned int)indexOfItem:(id)fp8;	// IMP=0x3027e4c8
- (id)init;	// IMP=0x3027e2b0
- (id)initWithArray:(id)fp8 error:(id *)fp12;	// IMP=0x3027e2d4
- (id)initWithError:(id *)fp8;	// IMP=0x3027e228
- (BOOL)insertItem:(id)fp8 afterItem:(id)fp12 error:(id *)fp16;	// IMP=0x3027e958
- (BOOL)insertItem:(id)fp8 atIndex:(unsigned int)fp12 error:(id *)fp16;	// IMP=0x3027e7b4
- (id)itemAfterItem:(id)fp8;	// IMP=0x3027e524
- (id)itemAtIndex:(unsigned int)fp8;	// IMP=0x3027e44c
- (unsigned int)itemCount;	// IMP=0x3027e42c
- (void)itemWasAdded:(id)fp8;	// IMP=0x3027e6d0
- (void)itemWillBeRemoved:(id)fp8;	// IMP=0x3027eb20
- (void)removeAllItems;	// IMP=0x3027ed9c
- (BOOL)removeItem:(id)fp8;	// IMP=0x3027ec04
- (BOOL)removeItemAtIndex:(unsigned int)fp8;	// IMP=0x3027ec70
- (void)removeItemsInRange:(struct _NSRange)fp8;	// IMP=0x3027ed44

@end

