/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface AVQueueFeeder : NSObject
{
}

- (void)contentInvalidatedWithCurrentItemMovedToIndex:(unsigned int)fp8;	// IMP=0x3027f02c
- (void)contentsDidChangeByInsertingRange:(struct _NSRange)fp8;	// IMP=0x3027ee44
- (void)contentsDidChangeByRemovingRange:(struct _NSRange)fp8;	// IMP=0x3027ef38
- (id)init;	// IMP=0x3027edec
- (unsigned int)numberOfPaths;	// IMP=0x3027ee2c
- (id)pathAtIndex:(unsigned int)fp8;	// IMP=0x3027ee34
- (id)playbackInfoAtIndex:(unsigned int)fp8;	// IMP=0x3027ee3c

@end

