/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class AVByteStream, NSString, NSThread;

@interface AVRefMovieParser : NSObject
{
    NSString *_filePath;
    AVByteStream *_byteStream;
    NSThread *_processingThread;
}

- (void)cancel;	// IMP=0x302a3980
- (void)dealloc;	// IMP=0x302a3700
- (id)initWithPath:(id)fp8 byteStream:(id)fp12;	// IMP=0x302a3668
- (void)parse;	// IMP=0x302a3924
- (void)work:(id)fp8;	// IMP=0x302a3778

@end

