/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface FigHTTPProbeRangeSupportHandler : NSObject
{
    unsigned long long m_RequestID;
}

- (void)connection:(id)fp8 didFailWithError:(id)fp12;	// IMP=0x302cb178
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;	// IMP=0x302cb0ec
- (id)connection:(id)fp8 willCacheResponse:(id)fp12;	// IMP=0x302cb18c
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;	// IMP=0x302cb194
- (void)connectionDidFinishLoading:(id)fp8;	// IMP=0x302cb188
- (id)initWithID:(unsigned long long)fp8;	// IMP=0x302cb0e4

@end

