/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface FigHTTPGetWithRangeHandler : NSObject
{
    unsigned long long m_RequestID;
    long long m_RequestedOffset;
    unsigned int m_RequestedLength;
    unsigned int m_numBytesConfirmed;
    unsigned int m_numBytesReceived;
}

- (void)connection:(id)fp8 didFailWithError:(id)fp12;	// IMP=0x302cb4a0
- (void)connection:(id)fp8 didReceiveData:(id)fp12;	// IMP=0x302cb23c
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;	// IMP=0x302cb1dc
- (id)connection:(id)fp8 willCacheResponse:(id)fp12;	// IMP=0x302cb52c
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;	// IMP=0x302cb534
- (void)connectionDidFinishLoading:(id)fp8;	// IMP=0x302cb50c
- (id)initWithID:(unsigned long long)fp8 offset:(long long)fp16 length:(unsigned int)fp24;	// IMP=0x302cb1b4

@end

