/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface CATransaction : NSObject {}
+ (void)begin;
+ (void)commit;
+ (void)flush;

@end

@interface CATransaction (CATransactionPrivate)
+ (BOOL)beginWithoutBlocking;	
+ (unsigned int)currentState;	
+ (void)synchronize;	
@end
