/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/AVController.h>

@interface AVControllerFig : AVController
{
}

- (id)initWithQueue:(id)fp8 error:(id *)fp12;	// IMP=0x3027c990

@end

