/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/ObjectWrapper.h>

@interface AVDelegateLog : ObjectWrapper
{
}

- (void)controller:(id)fp8 crossedTimeMarker:(int)fp12 forItem:(id)fp16 context:(id)fp20;	// IMP=0x30291278
- (BOOL)controller:(id)fp8 shouldBeginPlayingItem:(id)fp12 error:(id *)fp16;	// IMP=0x30291004

@end

