/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/ObjectWrapper.h>

@interface AVItemLog : ObjectWrapper
{
}

- (void)_clearPlaybackStats;	// IMP=0x30292460
- (void)_noteDidPlay;	// IMP=0x302924d8
- (void)_noteJumpedToCurrentTime:(double)fp8;	// IMP=0x302925e0
- (void)_noteStoppedByHittingEnd;	// IMP=0x3029267c
- (void)_noteStoppedTime:(double)fp8;	// IMP=0x30292550
- (void)_noteTrackRep:(id)fp8;	// IMP=0x30292360
- (id)_trackRep;	// IMP=0x302923e8
- (void)adjustRateForPlayer:(id)fp8;	// IMP=0x30292a2c
- (void)applyAttributesForTrack:(id)fp8 player:(id)fp12;	// IMP=0x30292acc
- (id)attributeForKey:(id)fp8;	// IMP=0x30291ee8
- (BOOL)didPlay;	// IMP=0x3029276c
- (double)duration;	// IMP=0x30291a2c
- (int)eqPreset;	// IMP=0x30291d5c
- (unsigned int)indexInQueueFeeder;	// IMP=0x30292954
- (id)init;	// IMP=0x302914e4
- (id)initWithPath:(id)fp8 error:(id *)fp12;	// IMP=0x30291614
- (double)maxVisitedTime;	// IMP=0x302926f4
- (struct CGSize)naturalSize;	// IMP=0x30291af4
- (id)path;	// IMP=0x3029196c
- (BOOL)setAttribute:(id)fp8 forKey:(id)fp12 error:(id *)fp16;	// IMP=0x30291fbc
- (void)setEQPreset:(int)fp8;	// IMP=0x30291e1c
- (BOOL)setPath:(id)fp8 error:(id *)fp12;	// IMP=0x302917f4
- (void)setVolume:(float)fp8;	// IMP=0x30291c88
- (double)startedTime;	// IMP=0x302927e8
- (BOOL)stoppedByHittingEnd;	// IMP=0x302928d8
- (double)stoppedTime;	// IMP=0x30292860
- (float)volume;	// IMP=0x30291bc8

@end

