/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/ObjectWrapper.h>

@interface AVQueueLog : ObjectWrapper
{
}

- (BOOL)appendItem:(id)fp8 error:(id *)fp12;	// IMP=0x30293618
- (BOOL)appendItemsFromArray:(id)fp8 error:(id *)fp12;	// IMP=0x302937e4
- (id)buildCleanItemArray:(id)fp8 outArray:(id *)fp12;	// IMP=0x30292b84
- (unsigned int)indexOfItem:(id)fp8;	// IMP=0x30293360
- (id)init;	// IMP=0x30292db0
- (id)initWithArray:(id)fp8 error:(id *)fp12;	// IMP=0x30292ee0
- (BOOL)insertItem:(id)fp8 afterItem:(id)fp12 error:(id *)fp16;	// IMP=0x30293bc0
- (BOOL)insertItem:(id)fp8 atIndex:(unsigned int)fp12 error:(id *)fp16;	// IMP=0x302939e0
- (id)itemAfterItem:(id)fp8;	// IMP=0x3029347c
- (id)itemAtIndex:(unsigned int)fp8;	// IMP=0x302931fc
- (unsigned int)itemCount;	// IMP=0x3029313c
- (void)removeAllItems;	// IMP=0x30294098
- (BOOL)removeItem:(id)fp8;	// IMP=0x30293dcc
- (BOOL)removeItemAtIndex:(unsigned int)fp8;	// IMP=0x30293ee8
- (void)removeItemsInRange:(struct _NSRange)fp8;	// IMP=0x30293fbc

@end

