/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Celestial/ObjectWrapper.h>

@interface AVQueueFeederLog : ObjectWrapper
{
}

- (id)buildCleanItemArray:(id)fp8 outArray:(id *)fp12;	// IMP=0x30295044
- (unsigned int)countOfTracks;	// IMP=0x302957f0
- (unsigned int)indexOfTrack:(id)fp8;	// IMP=0x30295a14
- (id)initWithArray:(id)fp8;	// IMP=0x302952d4
- (id)initWithQuery:(id)fp8 focusingOnEntityAtIndex:(unsigned int)fp12;	// IMP=0x3029569c
- (BOOL)isQueueEqualToQuery:(id)fp8 focusingOnEntityAtIndex:(unsigned int)fp12;	// IMP=0x30295bf4
- (unsigned int)numberOfPaths;	// IMP=0x302955b0
- (id)pathAtIndex:(unsigned int)fp8;	// IMP=0x30295478
- (id)trackAtIndex:(unsigned int)fp8;	// IMP=0x302958dc
- (id)trackQuery;	// IMP=0x30295b14

@end

