/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Message.h>

@interface _NSDataMessageStoreMessage : Message
{
}

- (void)dealloc;	// IMP=0x30b47fad
- (id)initWithStore:(id)fp8;	// IMP=0x30b47f69

@end

