/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class MessageInvocation, NSString;

@interface _NSSocket : NSObject
{
    struct __CFReadStream *_readStream;
    struct __CFWriteStream *_writeStream;
    NSString *_protocol;
    void *_stats;
    void *_request;
    unsigned int _numTimeoutSecs:16;
    unsigned int _openCompleted:1;
    unsigned int _canRead:1;
    unsigned int _canWrite:1;
    unsigned int _error:1;
    unsigned int _closed:1;
    unsigned int _ignoreCerts:1;
    float _lastReadTime;
    MessageInvocation *_eventHandler;
}

+ (unsigned int)connects;	// IMP=0x30b9ba35
+ (unsigned long long)inBytes;	// IMP=0x30b9b88d
+ (unsigned long long)inBytesPerSecond;	// IMP=0x30b9b94d
+ (void)initialize;	// IMP=0x30b9b67f
+ (unsigned long long)outBytes;	// IMP=0x30b9b87d
+ (unsigned long long)outBytesPerSecond;	// IMP=0x30b9b89d
+ (unsigned int)reads;	// IMP=0x30b9ba4d
+ (void)resetStatistics;	// IMP=0x30b9b83d
+ (void)setSimulatedSocketSpeed:(int)fp8;	// IMP=0x30b9b7c1
+ (void)showStatistics;	// IMP=0x30b9ba59
+ (int)simulatedSocketSpeed;	// IMP=0x30b9b77d
+ (unsigned long long)totalBytesPerSecond;	// IMP=0x30b9b9fd
+ (unsigned int)writes;	// IMP=0x30b9ba41
- (void)abort;	// IMP=0x30b9bc99
- (BOOL)connectToHost:(id)fp8 withPort:(unsigned int)fp12 protocol:(id)fp16;	// IMP=0x30b9d08d
- (struct __CFReadStream *)copyReadStream;	// IMP=0x30b9cb95
- (struct __CFWriteStream *)copyWriteStream;	// IMP=0x30b9bf25
- (void)dealloc;	// IMP=0x30b9bb4b
- (int)fileDescriptor;	// IMP=0x30b9c529
- (id)init;	// IMP=0x30b9bb21
- (id)initWithTimeout:(int)fp8;	// IMP=0x30b9babd
- (BOOL)isReadable;	// IMP=0x30b9cbbd
- (BOOL)isValid;	// IMP=0x30b9bba9
- (BOOL)isWritable;	// IMP=0x30b9bf4d
- (float)lastReadTime;	// IMP=0x30b9bc95
- (int)readBytes:(char *)fp8 length:(int)fp12;	// IMP=0x30b9c6bd
- (void)registerForEvents;	// IMP=0x30b9c60d
- (id)remoteHostname;	// IMP=0x30b9c5a9
- (unsigned int)remotePortNumber;	// IMP=0x30b9c533
- (id)securityProtocol;	// IMP=0x30b9b5e5
- (id)serverCertificates;	// IMP=0x30b9cc11
- (void)setEventHandler:(id)fp8;	// IMP=0x30b9bc29
- (void)setIgnoreSSLCertificates:(BOOL)fp8;	// IMP=0x30b9b669
- (BOOL)setSecurityProtocol:(id)fp8;	// IMP=0x30b9d6a1
- (void)setTimeout:(int)fp8;	// IMP=0x30b9bb47
- (id)sourceIPAddress;	// IMP=0x30b9c4e1
- (int)timeout;	// IMP=0x30b9bb41
- (int)writeBytes:(const char *)fp8 length:(int)fp12;	// IMP=0x30b9bfb5

@end

