/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface Account : NSObject
{
    NSMutableDictionary *_info;
    unsigned int _isOffline:1;
    unsigned int _autosynchronizingEnabled:1;
    unsigned int _ignoreSSLCertificates:1;
    unsigned int _promptedToIgnoreSSLCertificates:1;
    unsigned int _isActive:2;
}

+ (id)accountInfoValueForKey:(id)fp8 value:(id)fp12;	// IMP=0x30b74a39
+ (id)accountTypeString;	// IMP=0x30b735dd
+ (BOOL)allObjectsInArrayAreOffline:(id)fp8;	// IMP=0x30b738e1
+ (id)createAccountWithDictionary:(id)fp8;	// IMP=0x30b735a3
+ (id)displayedAccountTypeString;	// IMP=0x30b735e9
+ (BOOL)haveAccountsBeenConfigured;	// IMP=0x30b73595
+ (void)initialize;	// IMP=0x30b73431
+ (BOOL)isPredefinedAccountType;	// IMP=0x30b73599
+ (id)myFullName;	// IMP=0x30b735fd
+ (id)predefinedValueForKey:(id)fp8;	// IMP=0x30b7359d
+ (id)readAccountsUsingKey:(id)fp8;	// IMP=0x30b75211
+ (id)saslProfileName;	// IMP=0x30b7458d
+ (void)saveAccountInfoToDefaults;	// IMP=0x30b735a1
+ (void)saveAccounts:(id)fp8 usingKey:(id)fp12;	// IMP=0x30b75339
- (BOOL)_connectAndAuthenticate:(id)fp8;	// IMP=0x30b74881
- (BOOL)_ignoreSSLCertificates;	// IMP=0x30b74a05
- (void)_queueAccountInfoDidChange;	// IMP=0x30b73657
- (void)_removePasswordInKeychain;	// IMP=0x30b73e25
- (void)_setAccountInfo:(id)fp8;	// IMP=0x30b74e39
- (void)_setIgnoreSSLCertificates:(BOOL)fp8;	// IMP=0x30b74a0d
- (BOOL)_shouldRetryConnectionWithoutCertificateCheckingAfterError:(id)fp8;	// IMP=0x30b74661
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned int)fp8;	// IMP=0x30b74641
- (id)accountInfo;	// IMP=0x30b736ad
- (void)accountInfoDidChange;	// IMP=0x30b74441
- (BOOL)acquireCredentialsWithPassword:(id)fp8;	// IMP=0x30b74131
- (id)authenticatedConnection;	// IMP=0x30b745d1
- (BOOL)canGoOffline;	// IMP=0x30b739f5
- (Class)connectionClass;	// IMP=0x30b74591
- (id)customDescriptionForError:(id)fp8 authScheme:(id)fp12 defaultDescription:(id)fp16;	// IMP=0x30b746c5
- (id)customTitleForAuthenticationError:(id)fp8 authScheme:(id)fp12 defaultTitle:(id)fp16;	// IMP=0x30b746c1
- (id)customTitleForError:(id)fp8 authScheme:(id)fp12 defaultTitle:(id)fp16;	// IMP=0x30b74665
- (void)dealloc;	// IMP=0x30b7351d
- (unsigned int)defaultPortNumber;	// IMP=0x30b74195
- (unsigned int)defaultSecurePortNumber;	// IMP=0x30b74199
- (id)defaultsDictionary;	// IMP=0x30b736fd
- (id)displayName;	// IMP=0x30b73a15
- (id)domain;	// IMP=0x30b74379
- (id)hostname;	// IMP=0x30b73c59
- (id)init;	// IMP=0x30b7346d
- (BOOL)isActive;	// IMP=0x30b7377d
- (BOOL)isCommonPortNumber:(unsigned int)fp8;	// IMP=0x30b74281
- (BOOL)isInactivatedInsteadOfBeingDeleted;	// IMP=0x30b73861
- (BOOL)isOffline;	// IMP=0x30b739f9
- (BOOL)isPasswordMissing;	// IMP=0x30b74771
- (id)nameForMailboxUid:(id)fp8;	// IMP=0x30b74a23
- (BOOL)needsCredentials;	// IMP=0x30b7412d
- (id)password;	// IMP=0x30b73f91
- (id)passwordFromKeychain;	// IMP=0x30b73f01
- (id)passwordFromStoredUserInfo;	// IMP=0x30b74a79
- (unsigned int)portNumber;	// IMP=0x30b74135
- (id)preferredAuthScheme;	// IMP=0x30b744a1
- (id)promptUserForPasswordWithMessage:(id)fp8;	// IMP=0x30b740f1
- (id)promptUserIfNeededForPasswordWithMessage:(id)fp8;	// IMP=0x30b75015
- (void)releaseAllConnections;	// IMP=0x30b742c1
- (void)releaseAllForcedConnections;	// IMP=0x30b742d9
- (void)removeValueInAccountInfoForKey:(id)fp8;	// IMP=0x30b736d9
- (void)reportAuthenticationError:(id)fp8 authScheme:(id)fp12;	// IMP=0x30b7479d
- (BOOL)requiresAuthentication;	// IMP=0x30b745cd
- (id)secureServiceName;	// IMP=0x30b742bd
- (id)serviceName;	// IMP=0x30b742b9
- (void)setAccountInfo:(id)fp8;	// IMP=0x30b736b1
- (void)setAutosynchronizingEnabled:(BOOL)fp8;	// IMP=0x30b73641
- (void)setDisplayName:(id)fp8;	// IMP=0x30b73b1d
- (void)setDomain:(id)fp8;	// IMP=0x30b7438d
- (void)setHostname:(id)fp8;	// IMP=0x30b73c6d
- (void)setInactivatedInsteadOfBeingDeleted:(BOOL)fp8;	// IMP=0x30b73895
- (void)setIsActive:(BOOL)fp8;	// IMP=0x30b737cd
- (void)setIsOffline:(BOOL)fp8;	// IMP=0x30b73a03
- (void)setPassword:(id)fp8;	// IMP=0x30b74b49
- (void)setPasswordInKeychain:(id)fp8;	// IMP=0x30b73d91
- (void)setPortNumber:(unsigned int)fp8;	// IMP=0x30b7419d
- (void)setPreferredAuthScheme:(id)fp8;	// IMP=0x30b7451d
- (void)setTemporaryPassword:(id)fp8;	// IMP=0x30b73eb5
- (void)setUsername:(id)fp8;	// IMP=0x30b73ba5
- (void)setUsesSSL:(BOOL)fp8;	// IMP=0x30b742f5
- (void)setValueInAccountInfo:(id)fp8 forKey:(id)fp12;	// IMP=0x30b74d59
- (BOOL)storesPassword;	// IMP=0x30b74129
- (id)uniqueId;	// IMP=0x30b75451
- (id)username;	// IMP=0x30b73b91
- (BOOL)usesSSL;	// IMP=0x30b742dd
- (void)validateConnections;	// IMP=0x30b742db
- (id)valueInAccountInfoForKey:(id)fp8;	// IMP=0x30b74c15
- (void)willSleep:(id)fp8;	// IMP=0x30b73581

@end

