/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableSet;

@interface ActivityMonitorMultiTarget : NSObject
{
    id _primaryTarget;
    NSMutableSet *_allTargets;
}

- (BOOL)addActivityTarget:(id)fp8;	// IMP=0x30b90245
- (id)allTargets;	// IMP=0x30b90335
- (void)dealloc;	// IMP=0x30b90201
- (id)displayName;	// IMP=0x30b9034d
- (id)primaryTarget;	// IMP=0x30b90305
- (BOOL)removeActivityTarget:(id)fp8;	// IMP=0x30b902ad
- (void)setPrimaryTarget:(id)fp8;	// IMP=0x30b90309

@end

