/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/AuthScheme.h>

@interface APOPAuthScheme : AuthScheme
{
}

- (Class)authenticatorClassForAccountClass:(Class)fp8;	// IMP=0x30bbc5b5
- (BOOL)canAuthenticateAccountClass:(Class)fp8 connection:(id)fp12;	// IMP=0x30bbc5f9
- (Class)connectionClassForAccountClass:(Class)fp8;	// IMP=0x30bbc569
- (BOOL)hasEncryption;	// IMP=0x30bbc5b9
- (id)humanReadableName;	// IMP=0x30bbc5d5
- (id)name;	// IMP=0x30bbc5c5
- (BOOL)requiresDomain;	// IMP=0x30bbc5c1
- (BOOL)requiresPassword;	// IMP=0x30bbc5bd
- (BOOL)supportsAccountType:(id)fp8;	// IMP=0x30bbc53d

@end

