/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/POP3Connection.h>

@interface APOPConnection : POP3Connection
{
}

- (BOOL)authenticateUsingAccount:(id)fp8;	// IMP=0x30bbc66d

@end

