/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface AuthScheme : NSObject
{
}

+ (id)authSchemesForAccount:(id)fp8 connection:(id)fp12;	// IMP=0x30b9f80d
+ (void)initialize;	// IMP=0x30b9f629
+ (id)knownSchemes;	// IMP=0x30b9f765
+ (void)registerSchemeClass:(Class)fp8;	// IMP=0x30b9f785
+ (id)schemeWithName:(id)fp8;	// IMP=0x30b9f7ed
- (Class)authenticatorClassForAccountClass:(Class)fp8;	// IMP=0x30b9f957
- (id)authenticatorForAccount:(id)fp8 connection:(id)fp12;	// IMP=0x30b9f999
- (BOOL)canAuthenticateAccountClass:(Class)fp8 connection:(id)fp12;	// IMP=0x30b9f963
- (Class)connectionClassForAccountClass:(Class)fp8;	// IMP=0x30b9f953
- (unsigned int)defaultPortForAccount:(id)fp8;	// IMP=0x30b9f95b
- (BOOL)hasEncryption;	// IMP=0x30b9f95f
- (id)humanReadableName;	// IMP=0x30b9fa19
- (id)name;	// IMP=0x30b9fa15
- (void)release;	// IMP=0x30b9f951
- (BOOL)requiresDomain;	// IMP=0x30b9fa11
- (BOOL)requiresPassword;	// IMP=0x30b9fa0d
- (id)retain;	// IMP=0x30b9f949
- (unsigned int)retainCount;	// IMP=0x30b9f94b

@end

