/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/BufferedQueue.h>

@interface BufferedMessageQueue : BufferedQueue
{
}

- (unsigned int)sizeForItem:(id)fp8;	// IMP=0x30bbf5e9

@end

