/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, _NSSocket;

@interface Connection : NSObject
{
    id <SASLSecurityLayer> _securityLayer;
    _NSSocket *_socket;
    char *_buffer;
    int _bufferRemainingBytes;
    unsigned int _bufferStart;
    unsigned int _bufferLength;
    NSData *_logData;
    unsigned int _isFetching:1;
}

+ (void)appResumed:(id)fp8;	// IMP=0x30b886b5
+ (void)flushLog;	// IMP=0x30b888ed
+ (void)initialize;	// IMP=0x30b886fd
+ (id)logActivityOnHosts;	// IMP=0x30b8898d
+ (id)logActivityOnPorts;	// IMP=0x30b8894d
+ (BOOL)logAllSocketActivity;	// IMP=0x30b88931
+ (void)logBytes:(const char *)fp8 length:(int)fp12;	// IMP=0x30b88895
+ (id)logClasses;	// IMP=0x30b888ef
+ (void)setLogActivityOnHosts:(id)fp8;	// IMP=0x30b88999
+ (void)setLogActivityOnPorts:(id)fp8;	// IMP=0x30b88959
+ (void)setLogAllSocketActivity:(BOOL)fp8;	// IMP=0x30b88941
+ (void)setLogClasses:(id)fp8;	// IMP=0x30b888fd
- (void *)_socket;	// IMP=0x30b89c3d
- (BOOL)authenticateUsingAccount:(id)fp8;	// IMP=0x30b894b1
- (BOOL)authenticateUsingAccount:(id)fp8 authenticator:(id)fp12;	// IMP=0x30b89a89
- (id)authenticationMechanisms;	// IMP=0x30b89681
- (id)capabilities;	// IMP=0x30b8967d
- (BOOL)connectUsingAccount:(id)fp8;	// IMP=0x30b88d95
- (void)dealloc;	// IMP=0x30b889cd
- (void)disconnect;	// IMP=0x30b89c11
- (BOOL)hasBytesAvailable;	// IMP=0x30b89c41
- (BOOL)isFetching;	// IMP=0x30b88d75
- (BOOL)isForcedConnection;	// IMP=0x30b88cc5
- (BOOL)isValid;	// IMP=0x30b89be9
- (BOOL)readBytesIntoData:(id)fp8 desiredLength:(unsigned int)fp12;	// IMP=0x30b8a075
- (BOOL)readLineIntoData:(id)fp8;	// IMP=0x30b89f61
- (void)setIsFetching:(BOOL)fp8;	// IMP=0x30b88d81
- (BOOL)startTLSForAccount:(id)fp8;	// IMP=0x30b89b39
- (BOOL)writeData:(id)fp8;	// IMP=0x30b89c71
- (BOOL)writeData:(id)fp8 dontLogBytesInRange:(struct _NSRange)fp12;	// IMP=0x30b8a0f1

@end

