/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "DataConsumerProtocol.h"

@class LibraryMessage, NSDictionary, NSFileHandle, NSMutableData, NSString;

@interface DataCollector : NSObject <DataConsumer>
{
    NSString *_path;
    NSString *_tmpPath;
    LibraryMessage *_message;
    NSString *_part;
    NSFileHandle *_fileHandle;
    unsigned int _length;
    NSDictionary *_plist;
    NSMutableData *_data;
    BOOL _partial;
    BOOL _incomplete;
}

- (void)appendData:(id)fp8;	// IMP=0x30bae959
- (id)data;	// IMP=0x30baeb65
- (void)dealloc;	// IMP=0x30baead1
- (void)done;	// IMP=0x30baf971
- (id)fileHandle;	// IMP=0x30bb2211
- (id)initWithMessage:(id)fp8 part:(id)fp12 partial:(BOOL)fp16 incomplete:(BOOL)fp20;	// IMP=0x30bae8e1

@end

