/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData;

@interface DataScanner : NSObject
{
    NSData *myData;
    unsigned int myLocation;
}

+ (id)scannerWithData:(id)fp8;	// IMP=0x30b912c9
- (BOOL)byteAtScanLocation;	// IMP=0x30b9115d
- (id)data;	// IMP=0x30b90ad5
- (void)dealloc;	// IMP=0x30b90a99
- (void)incrementLocation;	// IMP=0x30b90ee1
- (id)initWithData:(id)fp8;	// IMP=0x30b91295
- (BOOL)isAtEnd;	// IMP=0x30b91139
- (id)nextTokenWithPunctuation:(id)fp8;	// IMP=0x30b911b1
- (BOOL)scanByte:(char *)fp8;	// IMP=0x30b90ae1
- (BOOL)scanBytesFromSet:(id)fp8 intoData:(id *)fp12;	// IMP=0x30b90e39
- (BOOL)scanCString:(const char *)fp8 intoData:(id *)fp12;	// IMP=0x30b90d9d
- (BOOL)scanData:(id)fp8 intoData:(id *)fp12;	// IMP=0x30b90cfd
- (BOOL)scanInt:(int *)fp8;	// IMP=0x30b90b45
- (unsigned int)scanLocation;	// IMP=0x30b90ad9
- (BOOL)scanUpToBytesFromSet:(id)fp8 intoData:(id *)fp12;	// IMP=0x30b91091
- (BOOL)scanUpToCString:(const char *)fp8 intoData:(id *)fp12;	// IMP=0x30b90fd5
- (BOOL)scanUpToData:(id)fp8 intoData:(id *)fp12;	// IMP=0x30b90f05
- (void)setData:(id)fp8;	// IMP=0x30b90a6d
- (void)setScanLocation:(unsigned int)fp8;	// IMP=0x30b90add

@end

