/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSUserDefaults;

@interface Defaults : NSObject
{
    NSUserDefaults *defaults;
}

+ (id)basicHeaders;	// IMP=0x30b91ce1
+ (id)logMessages;	// IMP=0x30b91c65
+ (void)setupLoggingDefaults;	// IMP=0x30b913c9
+ (id)sharedInstance;	// IMP=0x30b912fd
- (id)alternateAddressesForSelf;	// IMP=0x30b9206d
- (id)archiveMailbox;	// IMP=0x30b91f01
- (BOOL)autosaveWindows;	// IMP=0x30b9200d
- (BOOL)boolForKey:(id)fp8;	// IMP=0x30b9216d
- (id)defaultMailDirectory;	// IMP=0x30b91e85
- (id)dictionaryForKey:(id)fp8;	// IMP=0x30b920d1
- (id)draftsMailbox;	// IMP=0x30b91f59
- (int)integerForKey:(id)fp8;	// IMP=0x30b92185
- (id)mailAccountDirectory;	// IMP=0x30b91df5
- (id)objectForKey:(id)fp8;	// IMP=0x30b9213d
- (id)primaryEmailAddress;	// IMP=0x30b91d91
- (void)removeObjectForKey:(id)fp8;	// IMP=0x30b9210d
- (void)setAutosaveWindows:(BOOL)fp8;	// IMP=0x30b9204d
- (void)setBool:(BOOL)fp8 forKey:(id)fp12;	// IMP=0x30b92155
- (void)setDefaultMailDirectory:(id)fp8;	// IMP=0x30b91e51
- (void)setObject:(id)fp8 forKey:(id)fp12;	// IMP=0x30b92125
- (void)setPrimaryEmailAddress:(id)fp8;	// IMP=0x30b91dd9
- (id)stringForKey:(id)fp8;	// IMP=0x30b920e9
- (BOOL)synchronize;	// IMP=0x30b9219d
- (id)trashMailboxName;	// IMP=0x30b91fb1

@end

