/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Account.h>

@interface DeliveryAccount : Account
{
}

+ (void)_postDeliveryAccountsHaveChanged;	// IMP=0x30b8b2e5
+ (id)accountWithHostname:(id)fp8 username:(id)fp12;	// IMP=0x30b8b785
+ (id)accountWithHostname:(id)fp8 username:(id)fp12 lookForExistingAccounts:(BOOL)fp16;	// IMP=0x30b8b7a1
+ (id)accountWithIdentifier:(id)fp8;	// IMP=0x30b8b681
+ (id)accountWithUniqueId:(id)fp8;	// IMP=0x30b8b5c9
+ (void)addDeliveryAccount:(id)fp8;	// IMP=0x30b8b4c1
+ (id)deliveryAccounts;	// IMP=0x30b8b3ad
+ (id)existingAccountWithHostname:(id)fp8 username:(id)fp12;	// IMP=0x30b8b719
+ (id)newDefaultInstance;	// IMP=0x30b8b84d
+ (void)removeDeliveryAccount:(id)fp8;	// IMP=0x30b8b4ed
+ (void)saveAccountInfoToDefaults;	// IMP=0x30b8b589
+ (void)setDeliveryAccounts:(id)fp8;	// IMP=0x30b8b465
- (Class)deliveryClass;	// IMP=0x30b8b851
- (id)identifier;	// IMP=0x30b8b855
- (id)mailAccountIfAvailable;	// IMP=0x30b8b9f9
- (unsigned long long)maximumMessageBytes;	// IMP=0x30b8b94d
- (void)setMaximumMessageBytes:(unsigned long long)fp8;	// IMP=0x30b8b979
- (void)setShouldUseAuthentication:(BOOL)fp8;	// IMP=0x30b8b92d
- (BOOL)shouldUseAuthentication;	// IMP=0x30b8b8d1

@end

