/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@interface ExchangeAccount : IMAPAccount
{
}

+ (id)accountTypeString;	// IMP=0x30bc8195
+ (BOOL)usingActiveDirectory;	// IMP=0x30bc83c7
- (id)_defaultSpecialMailboxNameForType:(int)fp8;	// IMP=0x30bc81f5
- (void)_filterMailboxList:(id)fp8 forMailboxWithPath:(id)fp12 iisServer:(id)fp16;	// IMP=0x30bc8255
- (BOOL)_syncOnly_defaultValueForShouldStoreJunkOnServer;	// IMP=0x30bc81c1
- (Class)connectionClass;	// IMP=0x30bc81a1
- (void)filterMailboxList:(id)fp8 forMailbox:(id)fp12 options:(int)fp16;	// IMP=0x30bc8239
- (void)handleOpenMailboxError:(id)fp8;	// IMP=0x30bc83c5
- (id)serverPathPrefix;	// IMP=0x30bc83cb
- (BOOL)storeDraftsOnServer;	// IMP=0x30bc81c5
- (BOOL)storeSentMessagesOnServer;	// IMP=0x30bc81dd

@end

