/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface FlagChangeEntry : NSObject
{
    NSString *path;
    unsigned int uid;
    NSDictionary *changes;
    unsigned int connectionTag;
    double commitTime;
}

- (void)dealloc;	// IMP=0x30b803ad
- (id)initWithPath:(id)fp8 UID:(unsigned int)fp12 changes:(id)fp16;	// IMP=0x30b80345

@end

