/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableString, PlainTextDocument;

@interface FormatFlowedWriter : NSObject
{
    PlainTextDocument *_inputDocument;
    unsigned int _encoding;
    NSMutableString *_outputString;
    unsigned int _addedTrailingSpaces:1;
    NSMutableString *_lineString;
}

+ (id)newWithPlainTextDocument:(id)fp8 encoding:(unsigned long)fp12;	// IMP=0x30b714ed
- (unsigned int)_findLineBreakInRange:(struct _NSRange)fp8 maxCharWidthCount:(unsigned int)fp16 endIsURL:(BOOL)fp20;	// IMP=0x30b71871
- (void)_outputQuotedParagraph:(id)fp8 range:(struct _NSRange)fp12 withQuoteLevel:(unsigned int)fp20;	// IMP=0x30b71e01
- (BOOL)addedTrailingSpaces;	// IMP=0x30b71579
- (void)dealloc;	// IMP=0x30b7152d
- (id)outputString;	// IMP=0x30b71645

@end

