/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPOperation.h>

@interface IMAPOfflineCopyOnStupidServerOperation : IMAPOperation
{
    struct __CFArray *messageIds;
    struct __CFArray *internalDates;
}

- (void)_deserializeOpSpecificValuesFromData:(id)fp8 cursor:(unsigned int *)fp12;	// IMP=0x30b4ffed
- (unsigned char)_magic;	// IMP=0x30b4ffe9
- (unsigned int)approximateSize;	// IMP=0x30b500e5
- (void)dealloc;	// IMP=0x30b500a5
- (void)expungeTemporaryUid:(unsigned int)fp8;	// IMP=0x30b50121
- (BOOL)getMessageId:(id *)fp8 andInternalDate:(id *)fp12 forDestinationUid:(unsigned int)fp16;	// IMP=0x30b5031d
- (void)serializeIntoData:(id)fp8;	// IMP=0x30b4ffad
- (void)setMessageId:(id)fp8 andInternalDate:(id)fp12 forMessageWithSourceUid:(unsigned int)fp16;	// IMP=0x30b501d5

@end

