/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPCompoundDownload.h>

@class LibraryMessage;

@interface IMAPAttachmentsDownload : IMAPCompoundDownload
{
    LibraryMessage *_message;
}

- (void)dealloc;	// IMP=0x30bb837d
- (id)initWithLibraryMessage:(id)fp8;	// IMP=0x30bb83b9
- (id)message;	// IMP=0x30bb8411
- (void)saveCompletedDownloads;	// IMP=0x30bb8415

@end

