/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface IMAPCommandPipeline : NSObject
{
    unsigned int _chunkSize;
    unsigned int _expectedSize;
    unsigned int _full:1;
    unsigned int _sending:1;
    NSMutableArray *_fetchUnits;
}

- (void)_removeFetchUnitMatchingResponse:(id)fp8;	// IMP=0x30bb6595
- (void)addFetchCommandForUid:(unsigned long)fp8 fetchItem:(id)fp12 expectedLength:(unsigned long)fp16;	// IMP=0x30bb6489
- (unsigned long)chunkSize;	// IMP=0x30bb6575
- (void)dealloc;	// IMP=0x30bb644d
- (unsigned long)expectedSize;	// IMP=0x30bb656d
- (id)failureResponsesFromSendingCommandsWithConnection:(id)fp8;	// IMP=0x30bb6615
- (BOOL)isFull;	// IMP=0x30bb658b
- (BOOL)isSending;	// IMP=0x30bb6a89
- (void)setChunkSize:(unsigned long)fp8;	// IMP=0x30bb6571
- (void)setFull:(BOOL)fp8;	// IMP=0x30bb6579

@end

