/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface IMAPDownload : NSObject
{
    unsigned int _uid;
    NSMutableArray *_pendingFetchResults;
}

- (void)addCommandsToPipeline:(id)fp8 withCache:(id)fp12;	// IMP=0x30bb5913
- (unsigned long)bytesFetched;	// IMP=0x30bb5901
- (id)data;	// IMP=0x30bb5905
- (void)dealloc;	// IMP=0x30bb5875
- (id)error;	// IMP=0x30bb5909
- (unsigned long)expectedLength;	// IMP=0x30bb58f9
- (void)handleFetchResult:(id)fp8;	// IMP=0x30bb590f
- (id)initWithUid:(unsigned long)fp8;	// IMP=0x30bb58b1
- (BOOL)isComplete;	// IMP=0x30bb58fd
- (void)processResults;	// IMP=0x30bb5911
- (void)setError:(id)fp8;	// IMP=0x30bb590d
- (unsigned long)uid;	// IMP=0x30bb58f5

@end

