/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSData, NSDate, NSString;

@interface IMAPFetchResult : NSObject
{
    int _itemType;
    union {
        NSArray *envelope;
        NSDate *internalDate;
        unsigned int messageSize;
        NSArray *bodyStructure;
        struct {
            NSString *section;
            unsigned int startOffset;
            NSData *sectionData;
        } bodySectionInfo;
        unsigned int uid;
        unsigned int flags;
    } _typeSpecific;
}

- (id)bodyStructure;	// IMP=0x30bb4d9d
- (void)dealloc;	// IMP=0x30bb473d
- (id)description;	// IMP=0x30bb554d
- (unsigned long)encoding;	// IMP=0x30bb57b1
- (id)envelope;	// IMP=0x30bb47e1
- (id)fetchData;	// IMP=0x30bb4ab9
- (id)flagsArray;	// IMP=0x30bb533d
- (id)initWithType:(int)fp8;	// IMP=0x30bb470d
- (id)internalDate;	// IMP=0x30bb494d
- (unsigned long)messageFlags;	// IMP=0x30bb5549
- (unsigned long)messageSize;	// IMP=0x30bb4c51
- (id)section;	// IMP=0x30bb5065
- (void)setBodyStructure:(id)fp8;	// IMP=0x30bb4e41
- (void)setEnvelope:(id)fp8;	// IMP=0x30bb4885
- (void)setFetchData:(id)fp8;	// IMP=0x30bb4b6d
- (void)setFlagsArray:(id)fp8;	// IMP=0x30bb53f5
- (void)setInternalDate:(id)fp8;	// IMP=0x30bb49f1
- (void)setMessageFlags:(unsigned long)fp8;	// IMP=0x30bb54a1
- (void)setMessageSize:(unsigned long)fp8;	// IMP=0x30bb4cf5
- (void)setSection:(id)fp8;	// IMP=0x30bb5129
- (void)setStartOffset:(unsigned long)fp8;	// IMP=0x30bb4fbd
- (void)setUid:(unsigned long)fp8;	// IMP=0x30bb5295
- (unsigned long)startOffset;	// IMP=0x30bb4f09
- (int)type;	// IMP=0x30bb47dd
- (unsigned long)uid;	// IMP=0x30bb51f1

@end

