/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MailAccount.h>

#import "IMAPMailboxListFilterProtocol.h"

@class IMAPOperationCache, NSLock, NSMutableArray, NSMutableSet, NSRecursiveLock, NSString;

@interface IMAPAccount : MailAccount <IMAPMailboxListFilter>
{
    NSString *_separatorChar;
    struct __CFArray *_lastKnownCapabilities;
    struct __CFArray *_cachedConnections;
    struct __CFArray *_mailboxesToSynchronize;
    unsigned int _readBufferSize:31;
    unsigned int _lastConnectionFailed:1;
    IMAPOperationCache *_offlineCache;
    NSLock *_mailboxListingLock;
    NSMutableSet *_mailboxesWithChangedUidNext;
    int _greatestInboxUid;
    double _timeLastFetchedMailboxList;
    NSRecursiveLock *_flagChangesLock;
    NSMutableArray *_recentFlagChanges;
    int _nextConnectionTag;
}

+ (void)_deleteQueuedMailboxes:(id)fp8;	// IMP=0x30b841e1
+ (id)accountTypeString;	// IMP=0x30b80e09
+ (void)initialize;	// IMP=0x30b80401
+ (id)saslProfileName;	// IMP=0x30b808f1
- (id)_URLScheme;	// IMP=0x30b850e5
- (void)_checkForNewMessagesInStore:(id)fp8 unreadCountDelta:(unsigned int)fp12;	// IMP=0x30b81329
- (id)_copyMailboxUidWithParent:(id)fp8 name:(id)fp12 attributes:(unsigned int)fp16 existingMailboxUid:(id)fp20;	// IMP=0x30b83e31
- (id)_dataForTemporaryUid:(unsigned long)fp8;	// IMP=0x30b813c9
- (BOOL)_deleteMailbox:(id)fp8;	// IMP=0x30b82e89
- (void)_didSynchronizeMailboxCachesAndFoundChanges:(BOOL)fp8;	// IMP=0x30b80b2d
- (void)_fetchUnreadCountsCheckForNewMessages:(BOOL)fp8;	// IMP=0x30b839c9
- (void)_fetchUnreadCountsForMailboxUid:(id)fp8 recursively:(BOOL)fp12 connection:(id)fp16;	// IMP=0x30b839a5
- (void)_fetchUnreadCountsForMailboxUid:(id)fp8 recursively:(BOOL)fp12 connection:(id)fp16 checkForNewMessages:(BOOL)fp20;	// IMP=0x30b836a9
- (id)_fileSystemServerPathPrefix;	// IMP=0x30b860a1
- (void)_getMailboxListIfNecessaryWithConnection:(id)fp8;	// IMP=0x30b83b87
- (id)_infoForMatchingURL:(id)fp8;	// IMP=0x30b85f39
- (BOOL)_isMailboxTypeStoredLocally:(int)fp8;	// IMP=0x30b831b1
- (id)_listingForMailboxUid:(id)fp8 listAllChildren:(BOOL)fp12;	// IMP=0x30b82bf1
- (id)_listingForMailboxUid:(id)fp8 listAllChildren:(BOOL)fp12 onlySubscribed:(BOOL)fp16;	// IMP=0x30b82bcd
- (id)_listingForMailboxUid:(id)fp8 listAllChildren:(BOOL)fp12 onlySubscribed:(BOOL)fp16 withConnection:(id)fp20;	// IMP=0x30b82919
- (void)_loadEntriesFromFileSystemPath:(id)fp8 parent:(id)fp12;	// IMP=0x30b84c6d
- (id)_localMailboxNameForType:(int)fp8 usingDisplayName:(id)fp12;	// IMP=0x30b83201
- (id)_mailboxPathPrefix;	// IMP=0x30b84c4d
- (id)_mailboxUidForName:(id)fp8;	// IMP=0x30b861ed
- (void)_mailboxesWereRemovedFromTree:(id)fp8 withFileSystemPaths:(id)fp12;	// IMP=0x30b84079
- (id)_nameForMailboxUid:(id)fp8;	// IMP=0x30b84861
- (id)_pathComponentForUidName:(id)fp8;	// IMP=0x30b84831
- (void)_readCustomInfoFromMailboxCache:(id)fp8;	// IMP=0x30b80671
- (void)_releaseAllConnectionsAndCallSuper:(BOOL)fp8;	// IMP=0x30b82095
- (void)_releaseAllConnectionsAndCallSuper:(BOOL)fp8 edgeForcedOnly:(BOOL)fp12;	// IMP=0x30b8584d
- (void)_renameLocalSpecialMailboxesToName:(id)fp8;	// IMP=0x30b832e1
- (void)_setCapabilities:(id)fp8;	// IMP=0x30b850f1
- (BOOL)_setChildren:(id)fp8 forMailboxUid:(id)fp12;	// IMP=0x30b80d11
- (void)_setIsOffline:(BOOL)fp8;	// IMP=0x30b824b5
- (void)_setIsOfflineWrapper:(id)fp8;	// IMP=0x30b82511
- (void)_setSpecialMailbox:(id)fp8 forType:(int)fp12;	// IMP=0x30b83075
- (id)_specialMailboxUidWithType:(int)fp8 create:(BOOL)fp12;	// IMP=0x30b8346d
- (void)_synchronizeAccountWithServer;	// IMP=0x30b83c79
- (void)_synchronizeMailboxesSynchronously;	// IMP=0x30b80f9d
- (void)_synchronouslyLoadListingForParent:(id)fp8;	// IMP=0x30b83f85
- (id)_uidNameForPathComponent:(id)fp8;	// IMP=0x30b84849
- (void)_validateConnections;	// IMP=0x30b82121
- (void)_waitForMailboxListingLoadToComplete;	// IMP=0x30b8402d
- (void)_writeCustomInfoToMailboxCache:(id)fp8;	// IMP=0x30b8075d
- (void)addFlagChanges:(id)fp8 forMailboxPath:(id)fp12 UID:(unsigned int)fp16;	// IMP=0x30b851f9
- (BOOL)allowsPartialDownloads;	// IMP=0x30b81461
- (int)cachePolicy;	// IMP=0x30b809dd
- (BOOL)canBeSynchronized;	// IMP=0x30b83595
- (BOOL)canGoOffline;	// IMP=0x30b824b1
- (BOOL)canMailboxBeDeleted:(id)fp8;	// IMP=0x30b84a4d
- (void)checkInConnection:(id)fp8;	// IMP=0x30b85c89
- (void)checkInConnectionsForStore:(id)fp8;	// IMP=0x30b81d75
- (BOOL)compactWhenClosingMailboxes;	// IMP=0x30b80921
- (BOOL)connectAndAuthenticate:(id)fp8;	// IMP=0x30b814b5
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;	// IMP=0x30b8246d
- (BOOL)connection:(id)fp8 shouldHandleUntaggedResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;	// IMP=0x30b822a3
- (Class)connectionClass;	// IMP=0x30b80901
- (void)connectionDidDisconnect:(id)fp8;	// IMP=0x30b822a1
- (id)connectionForStore:(id)fp8 delegate:(id)fp12 options:(int)fp16;	// IMP=0x30b816cd
- (void)considerSynchronizingNow;	// IMP=0x30b835d1
- (id)createMailboxWithParent:(id)fp8 name:(id)fp12;	// IMP=0x30b82c11
- (void)dealloc;	// IMP=0x30b807d1
- (unsigned int)defaultPortNumber;	// IMP=0x30b808cd
- (unsigned int)defaultSecurePortNumber;	// IMP=0x30b808d1
- (void)deleteMessagesFromMailboxUid:(id)fp8 olderThanNumberOfDays:(unsigned int)fp12;	// IMP=0x30b84da1
- (void)fetchMailboxList;	// IMP=0x30b83e19
- (int)fetchSynchronously;	// IMP=0x30b82609
- (int)fetchSynchronouslyLite;	// IMP=0x30b82681
- (void)filterMailboxList:(id)fp8 forMailbox:(id)fp12 options:(int)fp16;	// IMP=0x30b81fed
- (id)flagChangesForMailboxPath:(id)fp8 UID:(unsigned int)fp12 connectTime:(double)fp16;	// IMP=0x30b852c9
- (id)flagChangesLock;	// IMP=0x30b851f5
- (int)greatestInboxUid;	// IMP=0x30b8061d
- (void)handleAlertResponse:(id)fp8;	// IMP=0x30b80e19
- (void)handleOpenMailboxError:(id)fp8;	// IMP=0x30b81d41
- (id)init;	// IMP=0x30b80449
- (void)insertInMailboxes:(id)fp8 atIndex:(unsigned int)fp12;	// IMP=0x30b84581
- (id)lastKnownCapabilities;	// IMP=0x30b82839
- (id)mailboxPathExtension;	// IMP=0x30b80885
- (id)mailboxUidForRelativePath:(id)fp8 create:(BOOL)fp12;	// IMP=0x30b84f81
- (void)messagesAdded:(id)fp8;	// IMP=0x30b80515
- (int)minID;	// IMP=0x30b8066d
- (int)minUID;	// IMP=0x30b80669
- (unsigned int)minimumPartialDownloadSize;	// IMP=0x30b81449
- (id)nameForMailboxUid:(id)fp8;	// IMP=0x30b84a39
- (BOOL)needToSynchronizeMailboxCaches;	// IMP=0x30b80a59
- (void)nowWouldBeAGoodTimeToStartBackgroundSynchronization;	// IMP=0x30b835fd
- (id)offlineCache;	// IMP=0x30b84f09
- (id)offlineCacheIfOffline;	// IMP=0x30b84e49
- (id)primaryMailboxUid;	// IMP=0x30b80d99
- (unsigned int)readBufferSize;	// IMP=0x30b80f65
- (void)refreshMailboxListingRootedAtUid:(id)fp8;	// IMP=0x30b83fd9
- (void)releaseAllConnections;	// IMP=0x30b820ad
- (void)releaseAllForcedConnections;	// IMP=0x30b820d5
- (void)removeFlagChanges:(id)fp8 forMessages:(id)fp12;	// IMP=0x30b8540d
- (void)removeFlagChangesCommittedBefore:(double)fp8;	// IMP=0x30b8552d
- (BOOL)renameMailbox:(id)fp8 newName:(id)fp12 parent:(id)fp16;	// IMP=0x30b84319
- (BOOL)requiresAuthentication;	// IMP=0x30b808fd
- (void)resetMailboxTimer;	// IMP=0x30b83b7d
- (void)saveState;	// IMP=0x30b80829
- (id)secureServiceName;	// IMP=0x30b808e5
- (id)separatorChar;	// IMP=0x30b8277d
- (id)serverPathPrefix;	// IMP=0x30b84aa1
- (id)serviceName;	// IMP=0x30b808d9
- (void)setAllowsPartialDownloads:(BOOL)fp8;	// IMP=0x30b81481
- (void)setCachePolicy:(int)fp8;	// IMP=0x30b8098d
- (void)setCommitTime:(double)fp8 forConnectionTag:(unsigned int)fp16;	// IMP=0x30b85631
- (void)setCompactWhenClosingMailboxes:(BOOL)fp8;	// IMP=0x30b80939
- (void)setConnectionTag:(unsigned int)fp8 forFlagChanges:(id)fp12 forMessages:(id)fp16;	// IMP=0x30b856e9
- (void)setDisplayName:(id)fp8;	// IMP=0x30b80891
- (void)setIsOffline:(BOOL)fp8;	// IMP=0x30b8253d
- (void)setReadBufferSize:(unsigned int)fp8;	// IMP=0x30b80f89
- (void)setServerPathPrefix:(id)fp8;	// IMP=0x30b84c35
- (void)setServerPathPrefix:(id)fp8 shouldSync:(BOOL)fp12;	// IMP=0x30b84ab5
- (void)setStoreMailboxType:(int)fp8 onServer:(BOOL)fp12;	// IMP=0x30b86331
- (void)setUseIDLEIfAvailable:(BOOL)fp8;	// IMP=0x30b80a2d
- (void)setValueInAccountInfo:(id)fp8 forKey:(id)fp12;	// IMP=0x30b85181
- (id)specialMailboxNameForType:(int)fp8;	// IMP=0x30b830d5
- (Class)storeClass;	// IMP=0x30b80865
- (BOOL)storeMailboxTypeOnServer:(int)fp8;	// IMP=0x30b80d3d
- (BOOL)supportsIDLE;	// IMP=0x30b82875
- (void)synchronizeAllMailboxes;	// IMP=0x30b812ed
- (void)synchronizeMailboxes:(id)fp8;	// IMP=0x30b811d5
- (void)unselectMailbox:(id)fp8;	// IMP=0x30b81e79
- (BOOL)useIDLEIfAvailable;	// IMP=0x30b80a29
- (void)validateConnections;	// IMP=0x30b82219
- (id)valueInAccountInfoForKey:(id)fp8;	// IMP=0x30b857ed

@end

