/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface IMAPDownloadCache : NSObject
{
    NSMutableArray *_downloads;
}

- (void)addCommandsForDownload:(id)fp8 toPipeline:(id)fp12;	// IMP=0x30bb7069
- (void)cleanUpDownloadsForUid:(unsigned long)fp8;	// IMP=0x30bb7795
- (void)dealloc;	// IMP=0x30bb6fe1
- (id)downloadForMessage:(id)fp8;	// IMP=0x30bb7275
- (id)downloadForUid:(unsigned long)fp8 section:(id)fp12 expectedLength:(unsigned long)fp16;	// IMP=0x30bb758d
- (id)downloadForUid:(unsigned long)fp8 section:(id)fp12 length:(unsigned long)fp16;	// IMP=0x30bb7569
- (id)downloadForUid:(unsigned long)fp8 section:(id)fp12 range:(struct _NSRange)fp16;	// IMP=0x30bb75b5
- (void)handleFetchResponse:(id)fp8 forUid:(unsigned long)fp12;	// IMP=0x30bb75d7
- (void)handleFetchResponses:(id)fp8;	// IMP=0x30bb7639
- (void)processResultsForUid:(unsigned long)fp8;	// IMP=0x30bb771d

@end

