/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@interface iToolsAccount : IMAPAccount
{
}

+ (id)accountInfoValueForKey:(id)fp8 value:(id)fp12;	// IMP=0x30b868c9
+ (id)accountTypeString;	// IMP=0x30b86439
+ (id)defaultPathNameForAccountWithHostname:(id)fp8 username:(id)fp12;	// IMP=0x30b863f9
+ (id)displayedAccountTypeString;	// IMP=0x30b8644d
+ (id)emailAddressHostPart;	// IMP=0x30b863ed
+ (id)iToolsMailHostname;	// IMP=0x30b86421
+ (id)iToolsSMTPHostname;	// IMP=0x30b8642d
+ (BOOL)isPredefinedAccountType;	// IMP=0x30b86459
- (void)_removePasswordInKeychain;	// IMP=0x30b86549
- (id)deliveryAccount;	// IMP=0x30b866f1
- (id)emailAddresses;	// IMP=0x30b865c1
- (id)hostname;	// IMP=0x30b8645d
- (id)passwordFromKeychain;	// IMP=0x30b86585
- (unsigned int)portNumber;	// IMP=0x30b864c5
- (void)setDeliveryAccount:(id)fp8;	// IMP=0x30b8663d
- (void)setHostname:(id)fp8;	// IMP=0x30b86469
- (void)setPasswordInKeychain:(id)fp8;	// IMP=0x30b864fd
- (void)setPortNumber:(unsigned int)fp8;	// IMP=0x30b8646b
- (void)setUsername:(id)fp8;	// IMP=0x30b8646d

@end

