/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/LibraryStore.h>

@class POP3Connection;

@interface LibraryPOPStore : LibraryStore
{
    POP3Connection *_connection;
}

- (id)_fetchBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12;	// IMP=0x30bbfe47
- (id)_fetchHeaderDataForMessage:(id)fp8;	// IMP=0x30bbf8bd
- (void)_handleFlagsChangedForMessages:(id)fp8 oldFlagsByMessage:(id)fp12;	// IMP=0x30bc0051
- (id)bodyDataForMessage:(id)fp8 isComplete:(char *)fp12 downloadIfNecessary:(BOOL)fp16;	// IMP=0x30bbf7e5
- (id)copyOfMessagesInRange:(struct _NSRange)fp8 options:(unsigned int)fp16;	// IMP=0x30bbf9ad
- (id)dataForMimePart:(id)fp8 inRange:(struct _NSRange)fp12 isComplete:(char *)fp20;	// IMP=0x30bbf7b1
- (id)dataForMimePart:(id)fp8 inRange:(struct _NSRange)fp12 isComplete:(char *)fp20 downloadIfNecessary:(BOOL)fp24 didDownload:(char *)fp28;	// IMP=0x30bbf63b
- (void)dealloc;	// IMP=0x30bbfc2d
- (int)fetchNumMessages:(unsigned int)fp8 preservingUID:(id)fp12 beforeUID:(unsigned int)fp16 synchronize:(BOOL)fp20;	// IMP=0x30bbfadd
- (int)fetchSynchronously;	// IMP=0x30bbfa99
- (id)fullBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12 isComplete:(char *)fp16 downloadIfNecessary:(BOOL)fp20;	// IMP=0x30bbf89d
- (BOOL)hasMoreMessages:(unsigned int)fp8;	// IMP=0x30bbfe39
- (id)initWithMailboxUid:(id)fp8 readOnly:(BOOL)fp12;	// IMP=0x30bbf601
- (void)messageFlagsDidChange:(id)fp8 flags:(id)fp12;	// IMP=0x30bbfa49
- (id)messageForRemoteID:(id)fp8;	// IMP=0x30bbfc55
- (void)messagesWereAdded:(id)fp8 forIncrementalLoading:(BOOL)fp12;	// IMP=0x30bbf9f9
- (void)messagesWereDeleted:(id)fp8;	// IMP=0x30bbfcb9
- (void)openSynchronouslyUpdatingMetadata:(BOOL)fp8;	// IMP=0x30bbf639
- (void)purgeMessages:(id)fp8;	// IMP=0x30bbfabd
- (unsigned int)serverMessageCount;	// IMP=0x30bbfdc9
- (unsigned int)serverUnreadCount;	// IMP=0x30bbfe35
- (void)setServerMessageCount:(unsigned int)fp8;	// IMP=0x30bbfd61
- (void)setServerUnreadCount:(unsigned int)fp8;	// IMP=0x30bbfdcd

@end

