/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Message.h>

@class NSString;

@interface LibraryMessage : Message
{
    unsigned int _libraryID;
    NSString *_remoteID;
    unsigned int _uid;
    unsigned int _size;
    CDAnonymousStruct8 _imapFlags;
    unsigned int _mailboxID;
    unsigned int _originalMailboxID;
    NSString *_messageID;
}

+ (id)messageWithLibraryID:(unsigned int)fp8;	// IMP=0x30ba0801
- (void)_updateUID;	// IMP=0x30ba097d
- (id)account;	// IMP=0x30ba1035
- (void)commit;	// IMP=0x30ba0e89
- (int)compareByUidWithMessage:(id)fp8;	// IMP=0x30ba0d21
- (void)dealloc;	// IMP=0x30ba0fc1
- (id)description;	// IMP=0x30ba0f55
- (BOOL)hasTemporaryUid;	// IMP=0x30ba0cbd
- (unsigned int)hash;	// IMP=0x30ba0af9
- (CDAnonymousStruct8)imapFlags;	// IMP=0x30ba0bad
- (id)initWithLibraryID:(unsigned int)fp8;	// IMP=0x30ba07af
- (BOOL)isEqual:(id)fp8;	// IMP=0x30ba0a8d
- (BOOL)isMessageContentsLocallyAvailable;	// IMP=0x30ba0c55
- (BOOL)isPartial;	// IMP=0x30ba0c25
- (unsigned int)libraryID;	// IMP=0x30ba0899
- (id)mailbox;	// IMP=0x30ba095d
- (unsigned int)mailboxID;	// IMP=0x30ba089d
- (id)mailboxName;	// IMP=0x30ba0ce1
- (void)markAsForwarded;	// IMP=0x30ba11cd
- (void)markAsNotViewed;	// IMP=0x30ba14a1
- (void)markAsReplied;	// IMP=0x30ba1111
- (void)markAsViewed;	// IMP=0x30ba1055
- (id)messageID;	// IMP=0x30ba0845
- (unsigned int)messageSize;	// IMP=0x30ba08d1
- (id)messageStore;	// IMP=0x30ba08d9
- (unsigned int)originalMailboxID;	// IMP=0x30ba08a5
- (id)originalMailboxURL;	// IMP=0x30ba08ad
- (id)path;	// IMP=0x30ba1015
- (id)persistentID;	// IMP=0x30ba0885
- (id)preferredEmailAddressToReplyWith;	// IMP=0x30ba1289
- (id)remoteID;	// IMP=0x30ba0a69
- (void)setFlags:(unsigned long long)fp8;	// IMP=0x30ba0dad
- (void)setHasTemporaryUid:(BOOL)fp8;	// IMP=0x30ba0cc7
- (void)setIMAPFlags:(CDAnonymousStruct8)fp8;	// IMP=0x30ba0b19
- (void)setIsPartial:(BOOL)fp8;	// IMP=0x30ba0c2f
- (void)setLibraryColor:(char *)fp8;	// IMP=0x30ba0e19
- (void)setLibraryID:(unsigned int)fp8;	// IMP=0x30ba0841
- (void)setMailboxID:(unsigned int)fp8;	// IMP=0x30ba08a1
- (void)setMessageFlags:(unsigned long)fp8;	// IMP=0x30ba0d75
- (void)setMessageFlagsWithoutCommitting:(unsigned long)fp8;	// IMP=0x30ba0d71
- (void)setMessageSize:(unsigned int)fp8;	// IMP=0x30ba08d5
- (void)setMessageStore:(id)fp8;	// IMP=0x30ba091d
- (void)setMutableInfoFromMessage:(id)fp8;	// IMP=0x30ba0ec1
- (void)setOriginalMailboxID:(unsigned int)fp8;	// IMP=0x30ba08a9
- (void)setPreferredEncoding:(unsigned long)fp8;	// IMP=0x30ba0c79
- (void)setRemoteID:(id)fp8;	// IMP=0x30ba0a21
- (void)setRemoteID:(const char *)fp8 flags:(unsigned long long)fp12 size:(unsigned int)fp20 mailboxID:(unsigned int)fp24 originalMailboxID:(unsigned int)fp28 color:(char *)fp32;	// IMP=0x30ba13b1
- (void)setSummary:(id)fp8;	// IMP=0x30ba0dcf
- (void)setUid:(unsigned long)fp8;	// IMP=0x30ba0bd1
- (unsigned long)uid;	// IMP=0x30ba0bcd

@end

