/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@class NSMutableArray;

@interface LocalAccount : MailAccount
{
    NSMutableArray *_disembodiedUids;
}

+ (id)accountTypeString;	// IMP=0x30b87b49
+ (id)localAccount;	// IMP=0x30b878f9
- (id)_URLScheme;	// IMP=0x30b8818d
- (id)_copyMailboxUidWithParent:(id)fp8 name:(id)fp12 attributes:(unsigned int)fp16 existingMailboxUid:(id)fp20;	// IMP=0x30b87c95
- (id)_infoForMatchingURL:(id)fp8;	// IMP=0x30b88239
- (BOOL)_setChildren:(id)fp8 forMailboxUid:(id)fp12;	// IMP=0x30b87d09
- (void)_synchronouslyLoadListingForParent:(id)fp8;	// IMP=0x30b87bc5
- (BOOL)canFetch;	// IMP=0x30b87b83
- (id)displayName;	// IMP=0x30b87b55
- (void)fetchSynchronously;	// IMP=0x30b87b87
- (id)initWithPath:(id)fp8;	// IMP=0x30b879c1
- (void)insertInMailboxes:(id)fp8 atIndex:(unsigned int)fp12;	// IMP=0x30b87f19
- (BOOL)isOffline;	// IMP=0x30b87b8d
- (id)mailboxPathExtension;	// IMP=0x30b87ae1
- (id)mailboxUidForFileSystemPath:(id)fp8;	// IMP=0x30b88019
- (id)password:(BOOL)fp8;	// IMP=0x30b87b75
- (id)primaryMailboxUid;	// IMP=0x30b87aed
- (BOOL)renameMailbox:(id)fp8 newName:(id)fp12 parent:(id)fp16;	// IMP=0x30b87d8d
- (void)setHostname:(id)fp8;	// IMP=0x30b87b71
- (void)setIsOffline:(BOOL)fp8;	// IMP=0x30b87b91
- (void)setPassword:(id)fp8;	// IMP=0x30b87b81
- (void)setPath:(id)fp8;	// IMP=0x30b87af1
- (void)setUsername:(id)fp8;	// IMP=0x30b87b73
- (BOOL)shouldAutoFetch;	// IMP=0x30b87b89
- (Class)storeClass;	// IMP=0x30b87ac1
- (id)uniqueId;	// IMP=0x30b87ab5

@end

