/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/SASLAuthenticator.h>

@interface LoginAuthenticator : SASLAuthenticator
{
    BOOL _justSentPassword;
}

- (BOOL)justSentPlainTextPassword;	// IMP=0x30b9ffd9
- (id)responseForServerData:(id)fp8;	// IMP=0x30b9ff15
- (id)saslName;	// IMP=0x30b9ff09

@end

