/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@interface MailAccount (Internal)
+ (id)_accountWithPath:(id)fp8;	// IMP=0x30b79719
+ (id)_outboxMailboxUid;	// IMP=0x30b7adf5
+ (void)_postMailAccountsHaveChanged;	// IMP=0x30b797a9
+ (void)_setOutboxMailboxUid:(id)fp8;	// IMP=0x30b7ad21
- (id)URLForMessage:(id)fp8;	// IMP=0x30b7b4b1
- (id)_URLForInfo:(id)fp8;	// IMP=0x30b7b29d
- (id)_URLScheme;	// IMP=0x30b7b299
- (BOOL)_assignSpecialMailboxToAppropriateIvar:(id)fp8 forType:(int)fp12 delete:(BOOL)fp16;	// IMP=0x30b7ae81
- (void)_backgroundFetchCompleted;	// IMP=0x30b7ad09
- (void)_backgroundFetchCompletedCount:(unsigned int)fp8;	// IMP=0x30b7ac35
- (BOOL)_canEmptyMessagesFromMailboxUid:(id)fp8;	// IMP=0x30b7b1f1
- (id)_copyMailboxUidWithParent:(id)fp8 name:(id)fp12 attributes:(unsigned int)fp16 existingMailboxUid:(id)fp20;	// IMP=0x30b79879
- (id)_defaultSpecialMailboxNameForType:(int)fp8;	// IMP=0x30b7ae31
- (BOOL)_deleteMailbox:(id)fp8;	// IMP=0x30b7ab91
- (void)_fetchSynchronouslyIfNeeded;	// IMP=0x30b7ac11
- (id)_infoForMatchingURL:(id)fp8;	// IMP=0x30b7b295
- (id)_insertMailbox:(id)fp8 intoParent:(id)fp12 withName:(id)fp16;	// IMP=0x30b7a65d
- (void)_loadEntriesFromFileSystemPath:(id)fp8 parent:(id)fp12;	// IMP=0x30b7ba1d
- (void)_loadMailboxListingIntoCache:(id)fp8 attributes:(unsigned int)fp12 children:(id)fp16 parent:(id)fp20;	// IMP=0x30b79957
- (id)_mailboxPathPrefix;	// IMP=0x30b7b4a1
- (void)_mailboxesWereRemovedFromTree:(id)fp8 withFileSystemPaths:(id)fp12;	// IMP=0x30b7cad9
- (id)_pathComponentForUidName:(id)fp8;	// IMP=0x30b79871
- (void)_postMailAccountsHaveChangedIfNeeded;	// IMP=0x30b79741
- (void)_readCustomInfoFromMailboxCache:(id)fp8;	// IMP=0x30b7b4ad
- (BOOL)_setChildren:(id)fp8 forMailboxUid:(id)fp12;	// IMP=0x30b7aa35
- (BOOL)_setPath:(id)fp8;	// IMP=0x30b7b5f1
- (void)_setSpecialMailbox:(id)fp8 forType:(int)fp12;	// IMP=0x30b7b091
- (void)_setSpecialMailboxName:(id)fp8 forType:(int)fp12;	// IMP=0x30b7b021
- (BOOL)_shouldLogDeleteActivity;	// IMP=0x30b7b1f5
- (id)_specialMailboxUidWithType:(int)fp8 create:(BOOL)fp12;	// IMP=0x30b7b121
- (void)_synchronizeMailboxListWithFileSystem;	// IMP=0x30b7a1d1
- (void)_synchronouslyLoadListingForParent:(id)fp8;	// IMP=0x30b79955
- (id)_uidNameForPathComponent:(id)fp8;	// IMP=0x30b79875
- (BOOL)_usesMailboxCache;	// IMP=0x30b79e1d
- (void)_writeCustomInfoToMailboxCache:(id)fp8;	// IMP=0x30b7b4af
- (void)_writeMailboxCacheWithPrejudice:(BOOL)fp8;	// IMP=0x30b7a471
- (id)description;	// IMP=0x30b7ab95
- (void)setIsActive:(BOOL)fp8;	// IMP=0x30b7c7f5
@end

