/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Account.h>

@class MFError, MailboxUid, NSString;

@interface MailAccount : Account
{
    NSString *_path;
    MailboxUid *_rootMailboxUid;
    struct {
        unsigned int cacheDirtyCount:16;
        unsigned int synchronizationThreadIsRunning:1;
        unsigned int backgroundFetchInProgress:1;
        unsigned int cacheHasBeenRead:1;
        unsigned int disableCacheWrite:1;
        unsigned int _UNUSED_:12;
    } _flags;
    MailboxUid *_inboxMailboxUid;
    MailboxUid *_draftsMailboxUid;
    MailboxUid *_sentMessagesMailboxUid;
    MailboxUid *_trashMailboxUid;
    MFError *_lastConnectionError;
}

+ (id)URLForInfo:(id)fp8;	// IMP=0x30b79265
+ (id)_accountContainingEmailAddress:(id)fp8 matchingAddress:(id *)fp12 fullUserName:(id *)fp16;	// IMP=0x30b7620d
+ (id)_accountForURL:(id)fp8;	// IMP=0x30b7921d
+ (id)_accountForURL:(id)fp8 includeInactiveAccounts:(BOOL)fp12;	// IMP=0x30b79045
+ (void)_addAccountToSortedPaths:(id)fp8;	// IMP=0x30b7b719
+ (void)_removeAccountFromSortedPaths:(id)fp8;	// IMP=0x30b75839
+ (void)_setOnlineStateOfAllAccountsTo:(BOOL)fp8;	// IMP=0x30b77899
+ (id)accountContainingEmailAddress:(id)fp8;	// IMP=0x30b76481
+ (id)accountForHeaders:(id)fp8 message:(id)fp12;	// IMP=0x30b7649d
+ (id)accountThatMessageIsFrom:(id)fp8;	// IMP=0x30b76571
+ (id)accountUsingHeadersFromMessage:(id)fp8;	// IMP=0x30b7652d
+ (id)accountWithPath:(id)fp8;	// IMP=0x30b769ad
+ (id)accountWithURLString:(id)fp8;	// IMP=0x30b79301
+ (id)accountWithURLString:(id)fp8 includeInactiveAccounts:(BOOL)fp12;	// IMP=0x30b79321
+ (id)accountWithUniqueId:(id)fp8;	// IMP=0x30b759b1
+ (id)activeAccounts;	// IMP=0x30b758a5
+ (id)addressesThatReceivedMessage:(id)fp8;	// IMP=0x30b765a1
+ (id)allEmailAddressesIncludingFullUserName:(BOOL)fp8;	// IMP=0x30b7c7a9
+ (id)allMailboxUids;	// IMP=0x30b76815
+ (void)connectAllAccounts;	// IMP=0x30b77985
+ (id)createAccountWithDictionary:(id)fp8;	// IMP=0x30b76a49
+ (id)defaultAccountDirectory;	// IMP=0x30b76d09
+ (id)defaultDeliveryAccount;	// IMP=0x30b7706d
+ (id)defaultPathForAccountWithHostname:(id)fp8 username:(id)fp12;	// IMP=0x30b76cb1
+ (id)defaultPathNameForAccountWithHostname:(id)fp8 username:(id)fp12;	// IMP=0x30b76d35
+ (void)deleteMailboxUidIfEmpty:(id)fp8;	// IMP=0x30b785e5
+ (void)disableMailboxListingNotifications;	// IMP=0x30b7556d
+ (void)disconnectAllAccounts;	// IMP=0x30b7796d
+ (void)enableMailboxListingNotifications:(BOOL)fp8;	// IMP=0x30b75589
+ (id)existingAccountWithType:(id)fp8 hostname:(id)fp12 username:(id)fp16;	// IMP=0x30b75a69
+ (BOOL)haveAccountsBeenConfigured;	// IMP=0x30b755e1
+ (id)infoForURL:(id)fp8;	// IMP=0x30b7923d
+ (void)initialize;	// IMP=0x30b7550d
+ (BOOL)isAnyAccountOffline;	// IMP=0x30b776f5
+ (BOOL)isAnyAccountOnline;	// IMP=0x30b777c5
+ (BOOL)isPredefinedAccountType;	// IMP=0x30b77319
+ (id)mailAccounts;	// IMP=0x30b75781
+ (BOOL)mailboxListingNotificationAreEnabled;	// IMP=0x30b75549
+ (id)mailboxUidForFileSystemPath:(id)fp8 create:(BOOL)fp12;	// IMP=0x30b7bcbd
+ (id)mailboxUidForURL:(id)fp8;	// IMP=0x30b79389
+ (id)newAccountWithPath:(id)fp8;	// IMP=0x30b769bb
+ (id)outboxMessageStore:(BOOL)fp8;	// IMP=0x30b7674d
+ (id)predefinedValueForKey:(id)fp8;	// IMP=0x30b796e5
+ (void)resetMailboxTimers;	// IMP=0x30b75bad
+ (void)saveAccountInfoToDefaults;	// IMP=0x30b7597d
+ (void)saveStateForAllAccounts;	// IMP=0x30b7799d
+ (void)setMailAccounts:(id)fp8;	// IMP=0x30b75821
+ (void)setMailAccounts:(id)fp8 saveIfChanged:(BOOL)fp12;	// IMP=0x30b7c399
+ (id)standardAccountClass:(Class)fp8 valueForKey:(id)fp12;	// IMP=0x30b795f3
+ (void)synchronouslyEmptyMailboxUidType:(int)fp8 inAccounts:(id)fp12;	// IMP=0x30b7820d
- (id)URLString;	// IMP=0x30b79299
- (void)_deleteHook;	// IMP=0x30b77549
- (int)_emptyFrequencyForKey:(id)fp8 defaultValue:(id)fp12;	// IMP=0x30b78101
- (void)_resetAllMailboxURLs:(BOOL)fp8;	// IMP=0x30b78689
- (BOOL)_resetSpecialMailboxes;	// IMP=0x30b782fd
- (void)_setEmptyFrequency:(int)fp8 forKey:(id)fp12;	// IMP=0x30b780a9
- (void)_synchronouslyInvalidateAndDelete:(unsigned int)fp8;	// IMP=0x30b7d4a1
- (void)_synchronouslyInvalidateAndDeleteWrapper:(id)fp8;	// IMP=0x30b77571
- (id)allMailboxUids;	// IMP=0x30b77f09
- (id)beginningOfDefaultFetchWindow;	// IMP=0x30b794d9
- (BOOL)canAppendMessages;	// IMP=0x30b77c97
- (BOOL)canBeSynchronized;	// IMP=0x30b77c9b
- (BOOL)canCreateNewMailboxes;	// IMP=0x30b78545
- (BOOL)canFetch;	// IMP=0x30b77b35
- (BOOL)canForwardWithoutDownload;	// IMP=0x30b79715
- (BOOL)canMailboxBeDeleted:(id)fp8;	// IMP=0x30b7859d
- (BOOL)canMailboxBeRenamed:(id)fp8;	// IMP=0x30b78555
- (BOOL)cheapStoreAtPathIsEmpty:(id)fp8;	// IMP=0x30b76725
- (id)connectionError;	// IMP=0x30b78bf5
- (BOOL)containsMailboxes;	// IMP=0x30b782f9
- (id)createMailboxWithParent:(id)fp8 name:(id)fp12;	// IMP=0x30b785c5
- (void)dealloc;	// IMP=0x30b76c15
- (id)defaultsDictionary;	// IMP=0x30b77b39
- (id)deleteAccount;	// IMP=0x30b776dd
- (id)deleteAccountWithOptions:(unsigned int)fp8;	// IMP=0x30b7759d
- (BOOL)deleteMailbox:(id)fp8;	// IMP=0x30b7cb01
- (void)deleteMessagesFromMailboxUid:(id)fp8 olderThanNumberOfDays:(unsigned int)fp12;	// IMP=0x30b78035
- (id)deliveryAccount;	// IMP=0x30b771a9
- (void)deliveryAccountWillBeRemoved:(id)fp8;	// IMP=0x30b77261
- (id)displayName;	// IMP=0x30b78185
- (id)displayNameForMailboxUid:(id)fp8;	// IMP=0x30b782b5
- (id)emailAddresses;	// IMP=0x30b77359
- (int)emptyFrequencyForMailboxType:(int)fp8;	// IMP=0x30b78145
- (void)emptyTrash;	// IMP=0x30b795a1
- (void)fetchAsynchronously;	// IMP=0x30b77d35
- (void)fetchAsynchronouslyLite;	// IMP=0x30b77db9
- (void)fetchMailboxList;	// IMP=0x30b77c95
- (int)fetchSynchronously;	// IMP=0x30b77e65
- (int)fetchSynchronouslyLite;	// IMP=0x30b77e3d
- (int)fetchWindowSize;	// IMP=0x30b7948d
- (BOOL)fileManager:(id)fp8 shouldProceedAfterError:(id)fp12;	// IMP=0x30b77511
- (id)firstEmailAddress;	// IMP=0x30b7731d
- (id)fullUserName;	// IMP=0x30b76f81
- (BOOL)hasUnreadMail;	// IMP=0x30b78dfd
- (id)init;	// IMP=0x30b76b2d
- (id)initWithPath:(id)fp8;	// IMP=0x30b76bbd
- (BOOL)isDotMacAccount;	// IMP=0x30b772a1
- (BOOL)isFetching;	// IMP=0x30b77e8d
- (BOOL)isValidAccountWithError:(id)fp8 accountBeingEdited:(id)fp12 userCanOverride:(char *)fp16;	// IMP=0x30b75c0b
- (id)mailboxPathExtension;	// IMP=0x30b78539
- (id)mailboxUidForRelativePath:(id)fp8 create:(BOOL)fp12;	// IMP=0x30b78e29
- (id)mailboxUidOfType:(int)fp8 createIfNeeded:(BOOL)fp12;	// IMP=0x30b77eb9
- (void)newMailHasBeenReceived;	// IMP=0x30b77e95
- (BOOL)newMailboxNameIsAcceptable:(id)fp8 reasonForFailure:(id *)fp12;	// IMP=0x30b78549
- (void)nowWouldBeAGoodTimeToStartBackgroundSynchronization;	// IMP=0x30b77bd5
- (int)numberOfMessagesToFetch;	// IMP=0x30b7959d
- (id)path;	// IMP=0x30b76d8d
- (void)postUserInfoHasChangedForMailboxUid:(id)fp8 userInfo:(id)fp12;	// IMP=0x30b78af9
- (id)primaryMailboxUid;	// IMP=0x30b77eb5
- (BOOL)receivesNewMailNotifications;	// IMP=0x30b795e9
- (void)releaseAllConnections;	// IMP=0x30b77a45
- (void)releaseAllForcedConnections;	// IMP=0x30b77a69
- (BOOL)renameMailbox:(id)fp8 newName:(id)fp12 parent:(id)fp16;	// IMP=0x30b7cf9d
- (void)resetMailboxTimer;	// IMP=0x30b75c09
- (void)resetMailboxURLs;	// IMP=0x30b78801
- (void)resetSpecialMailboxes;	// IMP=0x30b78525
- (id)rootMailboxUid;	// IMP=0x30b7a17d
- (void)saveState;	// IMP=0x30b77a11
- (void)setConnectionError:(id)fp8;	// IMP=0x30b78b69
- (void)setDeliveryAccount:(id)fp8;	// IMP=0x30b771dd
- (void)setEmailAddresses:(id)fp8;	// IMP=0x30b7c98d
- (void)setEmptyFrequency:(int)fp8 forMailboxType:(int)fp12;	// IMP=0x30b78169
- (void)setFullUserName:(id)fp8;	// IMP=0x30b76f95
- (void)setHostname:(id)fp8;	// IMP=0x30b788a5
- (void)setIsOffline:(BOOL)fp8;	// IMP=0x30b77a8d
- (void)setMailboxUid:(id)fp8 forMailboxType:(int)fp12;	// IMP=0x30b78021
- (void)setPath:(id)fp8;	// IMP=0x30b76e09
- (void)setPortNumber:(unsigned int)fp8;	// IMP=0x30b78931
- (void)setShouldAutoFetch:(BOOL)fp8;	// IMP=0x30b774bd
- (void)setUnreadCount:(unsigned int)fp8 forMailbox:(id)fp12;	// IMP=0x30b78d19
- (void)setUsername:(id)fp8;	// IMP=0x30b78819
- (void)setValueInAccountInfo:(id)fp8 forKey:(id)fp12;	// IMP=0x30b78a0d
- (BOOL)shouldAutoFetch;	// IMP=0x30b773f5
- (id)specialMailboxNameForType:(int)fp8;	// IMP=0x30b77ed1
- (void)startListeningForNotifications;	// IMP=0x30b795ed
- (void)stopListeningForNotifications;	// IMP=0x30b795ef
- (Class)storeClass;	// IMP=0x30b78cdd
- (Class)storeClassForMailbox:(id)fp8;	// IMP=0x30b78d05
- (id)storeForMailboxUid:(id)fp8;	// IMP=0x30b78c29
- (void)synchronizeAllMailboxes;	// IMP=0x30b77c9f
- (void)systemWillSleep;	// IMP=0x30b795f1
- (id)tildeAbbreviatedPath;	// IMP=0x30b76e35
- (id)transferDisabledMailboxUids;	// IMP=0x30b7801d
- (id)valueInAccountInfoForKey:(id)fp8;	// IMP=0x30b77379

@end

