/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface MainThread : NSObject
{
    struct __CFMessagePort *_ticklePort;
    NSMutableArray *_requests;
}

+ (id)mainThread;	// IMP=0x30b95bc1
+ (BOOL)runningOnMainThread;	// IMP=0x30b95bfd
+ (void)setupMainThreadObject;	// IMP=0x30b95ba1
- (void)_postNotificationInMainThread:(id)fp8;	// IMP=0x30b96169
- (BOOL)_runningOnMainThread;	// IMP=0x30b95d21
- (void)_threadWillDie:(id)fp8;	// IMP=0x30b95e2d
- (id)init;	// IMP=0x30b95c29
- (void)performOneway:(BOOL)fp8 invocation:(id)fp12;	// IMP=0x30b95f85

@end

