/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSString;

@interface MappedData : NSObject
{
    NSData *_mappedData;
    NSString *_storagePath;
}

- (void)appendBytes:(const void *)fp8 length:(unsigned int)fp12;	// IMP=0x30bc0e0d
- (void)appendBytesToDisk:(const void *)fp8 length:(unsigned int)fp12;	// IMP=0x30bc0ced
- (void)appendData:(id)fp8;	// IMP=0x30bc0dc1
- (void)convertNetworkLineEndingsToUnix;	// IMP=0x30bc0f69
- (void)convertToMutable;	// IMP=0x30bc0ec5
- (id)data;	// IMP=0x30bc0fc9
- (void)dealloc;	// IMP=0x30bc0b7d
- (BOOL)flushToDisk;	// IMP=0x30bc0c01
- (id)init;	// IMP=0x30bc0b55
- (unsigned int)length;	// IMP=0x30bc0ead
- (void)refreshFromDisk;	// IMP=0x30bc0d69
- (void)setData:(id)fp8;	// IMP=0x30bc0c69

@end

