/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class Message;

@interface MessageBody : NSObject
{
    Message *_message;
}

- (id)attachments;	// IMP=0x30b5da71
- (id)contentToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12 asHTML:(BOOL)fp16;	// IMP=0x30b5da09
- (void)dealloc;	// IMP=0x30b5da9d
- (id)htmlContent;	// IMP=0x30b5da0d
- (id)htmlContentToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12;	// IMP=0x30b5da05
- (BOOL)isHTML;	// IMP=0x30b5da29
- (BOOL)isRich;	// IMP=0x30b5da2d
- (id)message;	// IMP=0x30b5da69
- (unsigned int)numberOfAttachmentsSigned:(char *)fp8 encrypted:(char *)fp12;	// IMP=0x30b5da6d
- (id)rawData;	// IMP=0x30b5d9dd
- (void)setMessage:(id)fp8;	// IMP=0x30b5da31
- (id)textHtmlPart;	// IMP=0x30b5da95
- (id)webArchive;	// IMP=0x30b5da99

@end

