/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSURLProtocol.h"

@interface MessageURLProtocol : NSURLProtocol
{
}

+ (BOOL)canInitWithRequest:(id)fp8;	// IMP=0x30b724e5
+ (id)canonicalRequestForRequest:(id)fp8;	// IMP=0x30b72541
+ (void)initialize;	// IMP=0x30b724c5
+ (BOOL)requestIsCacheEquivalent:(id)fp8 toRequest:(id)fp12;	// IMP=0x30b72545
- (void)startLoading;	// IMP=0x30b72549
- (void)stopLoading;	// IMP=0x30b72a09

@end

