/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface MessageWriter : NSObject
{
    unsigned int _createsMimeAlternatives:1;
    unsigned int _createsRichText:1;
    unsigned int _createsPlainTextOnly:1;
    unsigned int _allows8BitMimeParts:1;
    unsigned int _allowsBinaryMimeParts:1;
    unsigned int _allowsAppleDoubleAttachments:1;
    unsigned int _signsOutput:1;
    unsigned int _encryptsOutput:1;
    unsigned int _writeImageSize:1;
    unsigned int _preferredEncoding;
    unsigned int _encodingHint;
}

- (BOOL)allows8BitMimeParts;	// IMP=0x30b6147d
- (BOOL)allowsAppleDoubleAttachments;	// IMP=0x30b614b9
- (BOOL)allowsBinaryMimeParts;	// IMP=0x30b6149b
- (void)appendDataForMimePart:(id)fp8 toData:(id)fp12 withPartData:(id)fp16;	// IMP=0x30b622cd
- (id)createMessageWithHtmlString:(id)fp8 attachments:(id)fp12 headers:(id)fp16;	// IMP=0x30b6391d
- (id)createMessageWithHtmlString:(id)fp8 plainTextAlternative:(id)fp12 otherHtmlStringsAndAttachments:(id)fp16 headers:(id)fp20;	// IMP=0x30b6332d
- (id)createMessageWithPlainTextDocumentsAndAttachments:(id)fp8 headers:(id)fp12;	// IMP=0x30b630a9
- (id)createMessageWithString:(id)fp8 headers:(id)fp12;	// IMP=0x30b62965
- (BOOL)createsMimeAlternatives;	// IMP=0x30b61425
- (BOOL)createsPlainTextOnly;	// IMP=0x30b61441
- (BOOL)createsRichText;	// IMP=0x30b6145f
- (unsigned long)encodingHint;	// IMP=0x30b614df
- (BOOL)encryptsOutput;	// IMP=0x30b61505
- (id)init;	// IMP=0x30b6078d
- (unsigned long)preferredEncoding;	// IMP=0x30b614d7
- (void)setAllows8BitMimeParts:(BOOL)fp8;	// IMP=0x30b61485
- (void)setAllowsAppleDoubleAttachments:(BOOL)fp8;	// IMP=0x30b614c1
- (void)setAllowsBinaryMimeParts:(BOOL)fp8;	// IMP=0x30b614a3
- (void)setCreatesMimeAlternatives:(BOOL)fp8;	// IMP=0x30b6142f
- (void)setCreatesPlainTextOnly:(BOOL)fp8;	// IMP=0x30b61449
- (void)setCreatesRichText:(BOOL)fp8;	// IMP=0x30b61467
- (void)setEncodingHint:(unsigned long)fp8;	// IMP=0x30b614e3
- (void)setEncryptsOutput:(BOOL)fp8;	// IMP=0x30b6150b
- (void)setPreferredEncoding:(unsigned long)fp8;	// IMP=0x30b614db
- (void)setSignsOutput:(BOOL)fp8;	// IMP=0x30b614ef
- (void)setWriteImageSize:(BOOL)fp8;	// IMP=0x30b61529
- (BOOL)signsOutput;	// IMP=0x30b614e7
- (BOOL)writeImageSize;	// IMP=0x30b6151f

@end

