/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface MessageInvocation : NSObject
{
    id _target;
    SEL _selector;
    id _argument1;
    id _argument2;
}

+ (id)invocationWithSelector:(SEL)fp8 target:(id)fp12;	// IMP=0x30b9698d
+ (id)invocationWithSelector:(SEL)fp8 target:(id)fp12 object1:(id)fp16 object2:(id)fp20;	// IMP=0x30b969b9
+ (id)invocationWithSelector:(SEL)fp8 target:(id)fp12 object:(id)fp16;	// IMP=0x30b969a3
- (void)dealloc;	// IMP=0x30b96a41
- (id)description;	// IMP=0x30b96a8d
- (id)invoke;	// IMP=0x30b969cf
- (id)invokeWithObject:(id)fp8;	// IMP=0x30b969f5
- (SEL)selector;	// IMP=0x30b96a3d
- (id)target;	// IMP=0x30b96a19

@end

