/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCodingProtocol.h"

@interface MessageFlags : NSObject <NSCoding>
{
    unsigned int realFlags;
}

- (void)encodeWithCoder:(id)fp8;	// IMP=0x30b601ed
- (id)initWithCoder:(id)fp8;	// IMP=0x30b60171

@end

