/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageCriterion.h>

@interface MessageCriterion (PrivateLibraryAdditions)
- (id)SQLExpressionWithContext:(CDAnonymousStruct1 *)fp8 depth:(unsigned int)fp12;	// IMP=0x30bbb37d
- (id)fixOnce;	// IMP=0x30bbae39
- (BOOL)hasNumberCriterion;	// IMP=0x30bbb2f1
@end

