/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopyingProtocol.h"

@class NSData;

@interface MessageHeaders : NSObject <NSCopying>
{
    NSData *_data;
    unsigned int _preferredEncoding;
}

+ (id)englishHeadersFromLocalizedHeaders:(id)fp8;	// IMP=0x30b5e939
+ (BOOL)isStructuredHeaderKey:(id)fp8;	// IMP=0x30b5dba1
+ (id)localizedHeaders;	// IMP=0x30b5e6bd
+ (id)localizedHeadersFromEnglishHeaders:(id)fp8;	// IMP=0x30b5e85d
+ (id)uniqueHeaderKeyStringForString:(id)fp8;	// IMP=0x30b5ea31
- (void)_appendAddressList:(id)fp8 toData:(id)fp12;	// IMP=0x30b5fb2d
- (void)_appendHeaderData:(id)fp8 andRecipients:(id)fp12 expandPrivate:(BOOL)fp16 includeComment:(BOOL)fp20;	// IMP=0x30b5e0b5
- (id)_capitalizedKeyForKey:(id)fp8;	// IMP=0x30b5de09
- (id)_copyHeaderValueForKey:(id)fp8;	// IMP=0x30b5de8d
- (id)_copyHeaderValueForKey:(id)fp8 offset:(unsigned int *)fp12;	// IMP=0x30b5fa89
- (id)_decodeHeaderKeysFromData:(id)fp8;	// IMP=0x30b5f329
- (id)_headerValueForKey:(id)fp8;	// IMP=0x30b5df19
- (id)_headerValueForKey:(id)fp8 offset:(unsigned int *)fp12;	// IMP=0x30b5de69
- (BOOL)_isStructuredHeaderKey:(id)fp8;	// IMP=0x30b5dd59
- (void)_setCapitalizedKey:(id)fp8 forKey:(id)fp12;	// IMP=0x30b5dd7d
- (id)allHeaderKeys;	// IMP=0x30b5dd67
- (void)appendHeaderData:(id)fp8 andRecipients:(id)fp12;	// IMP=0x30b5e659
- (id)copyFirstHeaderForKey:(id)fp8;	// IMP=0x30b5dfc5
- (id)copyFirstStringValueForKey:(id)fp8;	// IMP=0x30b5dfe5
- (id)copyHeadersForKey:(id)fp8;	// IMP=0x30b5df3d
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x30b5dc89
- (void)dealloc;	// IMP=0x30b5dcbd
- (id)encodedHeaders;	// IMP=0x30b5e091
- (id)firstHeaderForKey:(id)fp8;	// IMP=0x30b5dfa5
- (BOOL)hasHeaderForKey:(id)fp8;	// IMP=0x30b5f2ed
- (id)headerData;	// IMP=0x30b5dd2d
- (id)headersForKey:(id)fp8;	// IMP=0x30b5df81
- (id)initWithHeaderData:(id)fp8 encoding:(unsigned long)fp12;	// IMP=0x30b5dc59
- (id)isoLatin1CharsetHint;	// IMP=0x30b5f405
- (id)markupStringShowingHeaderDetailLevel:(int)fp8;	// IMP=0x30b5eb85
- (BOOL)messageIsFromEntourage;	// IMP=0x30b5f541
- (id)mutableCopy;	// IMP=0x30b5dcf9
- (unsigned long)preferredEncoding;	// IMP=0x30b5dd51
- (void)setPreferredEncoding:(unsigned long)fp8;	// IMP=0x30b5dd55

@end

