/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MimeCharset : NSObject
{
    unsigned int _encoding;
    NSString *_primaryLanguage;
    NSString *_charsetName;
    unsigned int _coversLargeUnicodeSubset:1;
    unsigned int _useBase64InHeaders:1;
    unsigned int _canBeUsedForOutgoingMessages:1;
}

+ (id)allMimeCharsets;	// IMP=0x30ba0145
+ (id)charsetForEncoding:(unsigned long)fp8;	// IMP=0x30ba0705
+ (id)preferredMimeCharset;	// IMP=0x30ba0107
- (BOOL)canBeUsedForOutgoingMessages;	// IMP=0x30ba0385
- (id)charsetName;	// IMP=0x30ba0349
- (BOOL)coversLargeUnicodeSubset;	// IMP=0x30ba038d
- (id)description;	// IMP=0x30ba03d1
- (id)displayName;	// IMP=0x30ba039f
- (unsigned long)encoding;	// IMP=0x30ba0345
- (id)initWithEncoding:(unsigned long)fp8;	// IMP=0x30ba0299
- (id)primaryLanguage;	// IMP=0x30ba03cd
- (void)release;	// IMP=0x30ba00ff
- (id)retain;	// IMP=0x30ba00fd
- (unsigned int)retainCount;	// IMP=0x30ba0101
- (BOOL)useBase64InHeaders;	// IMP=0x30ba0397

@end

