/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageInvocation.h>

@class ActivityMonitor;

@interface MonitoredInvocation : MessageInvocation
{
    ActivityMonitor *_monitor;
}

+ (id)invocationWithSelector:(SEL)fp8 target:(id)fp12 object1:(id)fp16 object2:(id)fp20 taskName:(id)fp24 priority:(unsigned char)fp28 canBeCancelled:(BOOL)fp32;	// IMP=0x30b96b2d
+ (id)invocationWithSelector:(SEL)fp8 target:(id)fp12 object:(id)fp16 taskName:(id)fp20 priority:(unsigned char)fp24 canBeCancelled:(BOOL)fp28;	// IMP=0x30b96afd
+ (id)invocationWithSelector:(SEL)fp8 target:(id)fp12 taskName:(id)fp16 priority:(unsigned char)fp20 canBeCancelled:(BOOL)fp24;	// IMP=0x30b96acd
- (void)dealloc;	// IMP=0x30b96c35
- (id)description;	// IMP=0x30b96dc5
- (id)init;	// IMP=0x30b96bc5
- (id)invoke;	// IMP=0x30b96ca1
- (id)monitor;	// IMP=0x30b96c71
- (void)setMonitor:(id)fp8;	// IMP=0x30b96c75

@end

