/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageHeaders.h>

@class NSMutableArray, NSMutableDictionary;

@interface MutableMessageHeaders : MessageHeaders
{
    NSMutableDictionary *_headersAdded;
    NSMutableArray *_headersRemoved;
}

- (void)_appendAddedHeaderKey:(id)fp8 value:(id)fp12 toData:(id)fp16;	// IMP=0x30b640e5
- (void)_appendHeaderKey:(id)fp8 value:(id)fp12 toData:(id)fp16;	// IMP=0x30b63f91
- (id)_copyHeaderValueForKey:(id)fp8;	// IMP=0x30b6419d
- (id)_copyHeaderValueForKey:(id)fp8 offset:(unsigned int *)fp12;	// IMP=0x30b6436d
- (id)_headerValueForKey:(id)fp8;	// IMP=0x30b63cf1
- (id)allHeaderKeys;	// IMP=0x30b63bd5
- (void)dealloc;	// IMP=0x30b63b91
- (id)encodedHeaders;	// IMP=0x30b64479
- (id)firstHeaderForKey:(id)fp8;	// IMP=0x30b63dc1
- (BOOL)hasHeaderForKey:(id)fp8;	// IMP=0x30b63c65
- (id)mutableCopy;	// IMP=0x30b63b4d
- (void)removeHeaderForKey:(id)fp8;	// IMP=0x30b63e91
- (void)setAddressList:(id)fp8 forKey:(id)fp12;	// IMP=0x30b64781
- (void)setHeader:(id)fp8 forKey:(id)fp12;	// IMP=0x30b63efd

@end

