/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (SortedMailboxes)
- (unsigned int)indexOfMailboxDictionaryWithName:(id)fp8;	// IMP=0x30b7b55d
@end

