/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (MimeDataEncoding)
+ (unsigned int)quotedPrintableLengthOfHeaderBytes:(const char *)fp8 length:(unsigned int)fp12;	// IMP=0x30b6d601
- (void)appendBase64EncodedDataToData:(id)fp8;	// IMP=0x30b6d4d5
- (id)decodeBase64;	// IMP=0x30b6d09d
- (id)decodeModifiedBase64;	// IMP=0x30b6d139
- (id)decodeQuotedPrintableForText:(BOOL)fp8;	// IMP=0x30b6ca57
- (id)encodeBase64;	// IMP=0x30b6d6e1
- (id)encodeBase64AllowCancel:(BOOL)fp8;	// IMP=0x30b6d6a1
- (id)encodeBase64HeaderData;	// IMP=0x30b6d62d
- (id)encodeBase64WithoutLineBreaks;	// IMP=0x30b6d499
- (id)encodeBase64WithoutLineBreaksOrPadding;	// IMP=0x30b6d71d
- (id)encodeModifiedBase64;	// IMP=0x30b6d669
- (id)encodeQuotedPrintableForText:(BOOL)fp8;	// IMP=0x30b6cbc1
- (id)encodeQuotedPrintableForText:(BOOL)fp8 allowCancel:(BOOL)fp12;	// IMP=0x30b6cbd9
- (BOOL)isValidBase64Data;	// IMP=0x30b6d0a9
@end

