/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (NSDataUtils)
- (id)MD5Digest;	// IMP=0x30b98821
- (id)componentsSeparatedByData:(id)fp8;	// IMP=0x30b99239
- (id)dataByConvertingUnixNewlinesToNetwork;	// IMP=0x30b986c9
- (struct _NSRange)rangeOfByteFromSet:(id)fp8;	// IMP=0x30b98bcd
- (struct _NSRange)rangeOfByteFromSet:(id)fp8 options:(unsigned int)fp12;	// IMP=0x30b98b6d
- (struct _NSRange)rangeOfByteFromSet:(id)fp8 options:(unsigned int)fp12 range:(struct _NSRange)fp16;	// IMP=0x30b98d75
- (struct _NSRange)rangeOfCString:(const char *)fp8;	// IMP=0x30b99149
- (struct _NSRange)rangeOfCString:(const char *)fp8 options:(unsigned int)fp12;	// IMP=0x30b991a5
- (struct _NSRange)rangeOfCString:(const char *)fp8 options:(unsigned int)fp12 range:(struct _NSRange)fp16;	// IMP=0x30b99201
- (struct _NSRange)rangeOfData:(id)fp8;	// IMP=0x30b9900d
- (struct _NSRange)rangeOfData:(id)fp8 options:(unsigned int)fp12;	// IMP=0x30b9907d
- (struct _NSRange)rangeOfData:(id)fp8 options:(unsigned int)fp12 range:(struct _NSRange)fp16;	// IMP=0x30b990ed
- (struct _NSRange)rangeOfRFC822HeaderData;	// IMP=0x30b98fb5
- (id)subdataFromIndex:(unsigned int)fp8;	// IMP=0x30b98c2d
- (id)subdataToIndex:(unsigned int)fp8;	// IMP=0x30b98c6d
@end

