/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SortedArrayExtensions)
- (unsigned int)indexOfObject:(id)fp8 usingSortFunction:(void *)fp12 context:(void *)fp16;	// IMP=0x30b98649
- (unsigned int)indexWhereObjectWouldBeInserted:(id)fp8 usingSortFunction:(void *)fp12 context:(void *)fp16;	// IMP=0x30b983c9
- (unsigned int)insertObject:(id)fp8 usingSortFunction:(void *)fp12 context:(void *)fp16;	// IMP=0x30b98455
@end

