/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (Convenience)
- (BOOL)addObjectIfAbsent:(id)fp8;	// IMP=0x30b98351
- (BOOL)addObjectIfAbsentAccordingToEquals:(id)fp8;	// IMP=0x30b9838d
@end

