/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (MainThreadMessaging)
- (void)performOnewaySelectorInMainThread:(SEL)fp8 withObject:(id)fp12;	// IMP=0x30b95aad
- (void)performOnewaySelectorInMainThread:(SEL)fp8 withObject:(id)fp12 withObject:(id)fp16;	// IMP=0x30b95b09
- (void)performSelectorInMainThread:(SEL)fp8;	// IMP=0x30b95995
- (void)performSelectorInMainThread:(SEL)fp8 withObject:(id)fp12;	// IMP=0x30b959ed
- (void)performSelectorInMainThread:(SEL)fp8 withObject:(id)fp12 withObject:(id)fp16;	// IMP=0x30b95a49
@end

