/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSSet.h"

@interface NSSet (MessageAdditions)
- (void)getAllObjects:(id *)fp8;	// IMP=0x30b9b59d
- (id)getAllObjectsAsArray;	// IMP=0x30b9b521
@end

