/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (MimeCharsetSupport)
- (id)_bestMimeCharset:(id)fp8;	// IMP=0x30ba04c9
- (id)bestMimeCharset;	// IMP=0x30ba0439
- (id)bestMimeCharsetUsingHint:(unsigned long)fp8;	// IMP=0x30ba057d
@end

