/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (IMAPNameEncoding)
- (id)decodedIMAPMailboxName;	// IMP=0x30b4e80d
- (id)encodedIMAPMailboxName;	// IMP=0x30b4e479
@end

