/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (FormatFlowedSupportInternal)
- (unsigned int)lineBreakBeforeIndex:(unsigned int)fp8 withinRange:(struct _NSRange)fp12;	// IMP=0x30b711a1
- (unsigned int)nextWordFromIndex:(unsigned int)fp8 forward:(BOOL)fp12;	// IMP=0x30b71583
@end

