/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/Message.h>

@class MessageBody, MutableMessageHeaders;

@interface OutgoingMessage : Message
{
    MessageBody *messageBody;
    MutableMessageHeaders *messageHeaders;
}

- (void)dealloc;	// IMP=0x30b615d5
- (id)headers;	// IMP=0x30b61785
- (id)messageBody;	// IMP=0x30b6164d
- (id)messageBodyIfAvailable;	// IMP=0x30b61651
- (id)messageData;	// IMP=0x30b61655
- (id)messageDataIsComplete:(char *)fp8 downloadIfNecessary:(BOOL)fp12;	// IMP=0x30b61705
- (unsigned int)messageSize;	// IMP=0x30b61799
- (id)messageStore;	// IMP=0x30b61649
- (id)mutableHeaders;	// IMP=0x30b61721
- (void)setMessageBody:(id)fp8;	// IMP=0x30b61619
- (void)setMutableHeaders:(id)fp8;	// IMP=0x30b61759

@end

