/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "SafeObserverProtocolProtocol.h"

@interface SafeObserver : NSObject <SafeObserverProtocol>
{
    unsigned int _retainCount;
}

+ (void)initialize;	// IMP=0x30b9455d
+ (void)lockSafeObservers;	// IMP=0x30b94609
+ (void)unlockSafeObservers;	// IMP=0x30b94629
- (id)copyWithZone:(struct _NSZone *)fp8;	// IMP=0x30b94649
- (id)init;	// IMP=0x30b945d9
- (void)release;	// IMP=0x30b94771
- (id)retain;	// IMP=0x30b95155
- (unsigned int)retainCount;	// IMP=0x30b9477d
- (id)willBeReleased;	// IMP=0x30b94699

@end

