/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/SMTPConnection.h>

@interface SMTPConnection (PrivateCommands)
- (BOOL)_connectUsingAccount:(id)fp8;	// IMP=0x30b8cddd
- (id)_dataForCommand:(const char *)fp8 length:(unsigned int)fp12 argument:(id)fp16 trailer:(unsigned char)fp20;	// IMP=0x30b8d06d
- (int)_doHandshakeUsingAccount:(id)fp8;	// IMP=0x30b8e07d
- (int)_getReply;	// IMP=0x30b8cce9
- (BOOL)_hasParameter:(id)fp8 forKeyword:(id)fp12;	// IMP=0x30b8cfb9
- (void)_readResponseRange:(struct _NSRange *)fp8 isContinuation:(char *)fp12;	// IMP=0x30b8ddd5
- (int)_sendCommand:(const char *)fp8 length:(unsigned int)fp12 argument:(id)fp16 trailer:(unsigned char)fp20;	// IMP=0x30b8dd5d
@end

