/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface SqliteMessageIDStore : NSObject
{
    NSString *_url;
    int _mailboxRowid;
}

- (void)_loadMailboxRowidIfNecessary:(struct sqlite3 *)fp8;	// IMP=0x30bbed59
- (void)dealloc;	// IMP=0x30bbf2d9
- (void)deleteAllUIDs;	// IMP=0x30bbf1e1
- (void)deleteUIDsNotInArray:(id)fp8;	// IMP=0x30bbef9d
- (unsigned long long)flagsForUID:(id)fp8;	// IMP=0x30bbf235
- (id)initWithURLString:(id)fp8;	// IMP=0x30bbed11
- (id)knownMessageIDsFromSet:(id)fp8;	// IMP=0x30bbedb9
- (id)messageIDsAddedBeforeDate:(double)fp8;	// IMP=0x30bbeea9
- (unsigned int)numberOfMessageIDs;	// IMP=0x30bbf175

@end

