/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSURL;

@interface WebAttachmentSource : NSObject
{
    NSURL *_baseURL;
    unsigned int _uniqueId:30;
}

+ (id)availableSources;	// IMP=0x30bc0331
+ (id)invalidBaseURL;	// IMP=0x30bc03ab
+ (id)sourceWithUniqueIdentifier:(unsigned int)fp8;	// IMP=0x30bc03d1
- (id)attachmentForURL:(id)fp8;	// IMP=0x30bc055d
- (id)baseURL;	// IMP=0x30bc0551
- (void)dealloc;	// IMP=0x30bc0405
- (id)init;	// IMP=0x30bc045d
- (unsigned int)uniqueIdentifier;	// IMP=0x30bc0555

@end

