/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@class NSRecursiveLock, NSString;

@interface YahooAccount : IMAPAccount
{
    struct __CFSocket *_socket;
    struct __CFRunLoopSource *_socketRunLoopSource;
    int _nonce;
    BOOL _initializedDeviceID;
    unsigned char _deviceID[16];
    unsigned short _sequenceNumber;
    NSRecursiveLock *_cookieLock;
    double _timeLastReceivedPacket;
    double _timeLastSentPacket;
    double _timeLastProvisioned;
    BOOL _shouldListenForNotifications;
    double _timeLastEncounteredAuthenticationError;
    NSString *_temporaryPassword;
    int _stores;
}

+ (id)accountInfoValueForKey:(id)fp8 value:(id)fp12;	// IMP=0x30bc4a61
+ (id)createAccountWithDictionary:(id)fp8;	// IMP=0x30bc34d1
+ (id)deliveryAccountHostname;	// IMP=0x30bc35b5
+ (unsigned int)deliveryAccountPortNumber;	// IMP=0x30bc3645
+ (BOOL)deliveryAccountUsesSSL;	// IMP=0x30bc35f5
+ (id)displayedAccountTypeString;	// IMP=0x30bc3395
+ (id)emailAddressHostPart;	// IMP=0x30bc3389
+ (void)initialize;	// IMP=0x30bc32ed
+ (BOOL)isPredefinedAccountType;	// IMP=0x30bc33a1
- (id)URLForMessage:(id)fp8;	// IMP=0x30bc47f9
- (id)_defaultSpecialMailboxNameForType:(int)fp8;	// IMP=0x30bc380d
- (void)_scheduleWakeAtDate:(id)fp8;	// IMP=0x30bc43f5
- (void)_setAccountInfo:(id)fp8;	// IMP=0x30bc3461
- (BOOL)acquireCredentialsWithPassword:(id)fp8;	// IMP=0x30bc3e89
- (BOOL)canForwardWithoutDownload;	// IMP=0x30bc48ed
- (void)cancelKeepalive;	// IMP=0x30bc42bd
- (void)closeSocket:(struct __CFSocket *)fp8 andRemoveSource:(struct __CFRunLoopSource *)fp12;	// IMP=0x30bc447d
- (id)connectionForStore:(id)fp8 delegate:(id)fp12 options:(int)fp16;	// IMP=0x30bc4791
- (id)cookieForKey:(id)fp8;	// IMP=0x30bc582d
- (void)cookiesExpired;	// IMP=0x30bc3dc1
- (void)dealloc;	// IMP=0x30bc4909
- (id)deliveryAccount;	// IMP=0x30bc3691
- (void)edgeStayedDown;	// IMP=0x30bc45d1
- (id)emailAddresses;	// IMP=0x30bc3e9d
- (id)hostname;	// IMP=0x30bc3861
- (id)init;	// IMP=0x30bc33a5
- (BOOL)isPasswordMissing;	// IMP=0x30bc48f1
- (int)minUID;	// IMP=0x30bc478d
- (BOOL)needsCredentials;	// IMP=0x30bc3e61
- (void)networkConfigurationChanged:(id)fp8;	// IMP=0x30bc466d
- (id)password;	// IMP=0x30bc3de9
- (unsigned int)portNumber;	// IMP=0x30bc38e1
- (id)preferredAuthScheme;	// IMP=0x30bc38e5
- (void)reallyScheduleRetry;	// IMP=0x30bc423d
- (BOOL)receivesNewMailNotifications;	// IMP=0x30bc4789
- (void)scheduleKeepaliveAfterDelay:(id)fp8;	// IMP=0x30bc42f1
- (void)scheduleRetryLater;	// IMP=0x30bc428d
- (void)scheduleSource;	// IMP=0x30bc41d5
- (void)sendKeepalive:(id)fp8;	// IMP=0x30bc5d99
- (void)sendUDPAuthentication;	// IMP=0x30bc5969
- (void)setPassword:(id)fp8;	// IMP=0x30bc3ded
- (BOOL)shouldAutoFetch;	// IMP=0x30bc4785
- (void)startListeningForNotifications;	// IMP=0x30bc50c5
- (void)stopListeningForNotifications;	// IMP=0x30bc44e9
- (BOOL)storesPassword;	// IMP=0x30bc3e5d
- (void)systemWillSleep;	// IMP=0x30bc45b9
- (id)temporaryPassword;	// IMP=0x30bc3e29
- (id)transferDisabledMailboxUids;	// IMP=0x30bc3ff1
- (id)valueInAccountInfoForKey:(id)fp8;	// IMP=0x30bc3f19

@end

