/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/DeliveryAccount.h>

@class YahooAccount;

@interface YahooDeliveryAccount : DeliveryAccount
{
    YahooAccount *_yahooAccount;
}

- (Class)deliveryClass;	// IMP=0x30bc31ed
- (id)mailAccountIfAvailable;	// IMP=0x30bc323d
- (id)preferredAuthScheme;	// IMP=0x30bc320d
- (void)setYahooAccount:(id)fp8;	// IMP=0x30bc3239
- (id)yahooAccount;	// IMP=0x30bc3235

@end

