/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIPickerView;

@interface _UIPickerViewSelectionBar : UIView
{
    UIPickerView *_pickerView;
}

- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323acb58
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323acacc
- (void)setPickerView:(id)fp8;	// IMP=0x323acb50

@end

