/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMElement.h"

@interface DOMElement (UIWebViewAdditions)
- (unsigned int)becomeFirstResponder;	// IMP=0x32437f14
- (BOOL)resignFirstResponder;	// IMP=0x32437f50
@end

