/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMNode.h"

@interface DOMNode (UIWebViewTextEditingAdditions)
- (void)autoscrollTimerFired:(id)fp8;	// IMP=0x32437bd4
- (struct CGRect)caretRect;	// IMP=0x324379e8
- (unsigned short)characterAfterCaretSelection;	// IMP=0x32436f60
- (unsigned short)characterBeforeCaretSelection;	// IMP=0x32436de0
- (unsigned short)characterInRelationToCaretSelection:(int)fp8;	// IMP=0x32436dac
- (struct CGPoint)constrainedPoint:(struct CGPoint)fp8;	// IMP=0x32437efc
- (struct CGRect)convertCaretRect:(struct CGRect)fp8;	// IMP=0x32437a3c
- (void)deleteBackward;	// IMP=0x32436cb0
- (id)editingDelegate;	// IMP=0x32437b7c
- (void)expandSelectionToStartOfWordContainingCaretSelection;	// IMP=0x3243731c
- (void *)fontForCaretSelection;	// IMP=0x32436f8c
- (BOOL)hasSelection;	// IMP=0x324375fc
- (int)initialSelectionBehavior;	// IMP=0x32437b70
- (void)insertText:(id)fp8;	// IMP=0x32436d04
- (BOOL)isProxyFor:(id)fp8;	// IMP=0x32436c90
- (BOOL)isSecure;	// IMP=0x32436c84
- (BOOL)isShowingPlaceholder;	// IMP=0x32437b2c
- (id)keyboardInputOverlayContainer:(id)fp8;	// IMP=0x32437b88
- (id)keyboardInputView;	// IMP=0x32437ae0
- (void)markCurrentWordForAutoCorrection:(id)fp8 correction:(id)fp12;	// IMP=0x324376f8
- (id)markedText;	// IMP=0x32436e0c
- (void)moveBackward:(unsigned int)fp8;	// IMP=0x32437764
- (void)moveForward:(unsigned int)fp8;	// IMP=0x32437768
- (id)previousNGrams:(unsigned int)fp8;	// IMP=0x324373b4
- (BOOL)rangeAtSentenceStart:(id)fp8;	// IMP=0x324376c0
- (struct CGRect)rectContainingCaretSelection;	// IMP=0x324370c0
- (void)replaceCurrentWordWithText:(id)fp8;	// IMP=0x32436e88
- (int)returnKeyType;	// IMP=0x32437b64
- (void)selectAll;	// IMP=0x3243776c
- (BOOL)selectionAtDocumentStart;	// IMP=0x32437630
- (BOOL)selectionAtSentenceStart;	// IMP=0x32437660
- (BOOL)selectionAtWordStart;	// IMP=0x32437690
- (struct _NSRange)selectionRange;	// IMP=0x324375ac
- (void)setCaretChangeListener:(id)fp8;	// IMP=0x324379b4
- (void)setEditingDelegate:(id)fp8;	// IMP=0x32437b84
- (void)setInitialSelectionBehavior:(int)fp8;	// IMP=0x32437b78
- (void)setMarkedText:(id)fp8;	// IMP=0x32438ed8
- (void)setReturnKeyType:(int)fp8;	// IMP=0x32437b6c
- (void)setSecure:(BOOL)fp8;	// IMP=0x32436c8c
- (void)setShowsExtraSuggestions:(BOOL)fp8;	// IMP=0x32437b48
- (void)setSuggestionBarTextSize:(int)fp8;	// IMP=0x32437b54
- (void)setText:(id)fp8;	// IMP=0x32437798
- (void)setTextDomain:(int)fp8;	// IMP=0x32436ca0
- (void)setTextLoupeVisibility:(int)fp8;	// IMP=0x32437b60
- (void)setTextSuggestionDelegate:(id)fp8;	// IMP=0x32437b3c
- (void)setTextTrimmingSet:(struct __CFCharacterSet *)fp8;	// IMP=0x32436cac
- (BOOL)showsExtraSuggestions;	// IMP=0x32437b40
- (BOOL)spaceFollowsWordInRange:(id)fp8;	// IMP=0x3243737c
- (int)suggestionBarTextSize;	// IMP=0x32437b4c
- (id)text;	// IMP=0x324377e4
- (void *)textColorForCaretSelection;	// IMP=0x324370ac
- (int)textDomain;	// IMP=0x32436c98
- (int)textLoupeVisibility;	// IMP=0x32437b58
- (id)textSuggestionDelegate;	// IMP=0x32437b34
- (id)textTraits;	// IMP=0x32436bb8
- (struct __CFCharacterSet *)textTrimmingSet;	// IMP=0x32436ca4
- (void)updateSelectionWithPoint:(struct CGPoint)fp8;	// IMP=0x3243782c
- (id)wordContainingCaretSelection;	// IMP=0x32437294
- (id)wordInRange:(id)fp8;	// IMP=0x324372e8
- (int)wordOffsetInRange:(id)fp8;	// IMP=0x32437348
- (id)wordRangeContainingCaretSelection;	// IMP=0x32437144
@end

