/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (UICollectionAdditions)
- (BOOL)boolForKey:(id)fp8;	// IMP=0x323c91d8
@end

