/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (UICollectionAdditions_Performance)
- (void)addObjectsFromArray:(id)fp8 range:(struct _NSRange)fp12;	// IMP=0x323c90e8
@end

