/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimator.h>

@interface UIAnimator (Static)
- (void)_addAnimation:(id)fp8 withDuration:(double)fp12 start:(BOOL)fp20 startTime:(double)fp24;	// IMP=0x323fc2a4
- (void)_advance:(BOOL)fp8;	// IMP=0x323fc5b4
- (void)_startAnimation:(id)fp8 withStartTime:(double)fp12;	// IMP=0x323fc3fc
@end

