/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIApplication.h>

@interface UIApplication (UIApplicationTesting)
- (void *)_getSymbol:(id)fp8 forFramework:(id)fp12;	// IMP=0x32408678
- (void)_leak;	// IMP=0x3240a2ac
- (void)_reportResults:(id)fp8;	// IMP=0x32408bd0
- (void)enableFramebufferStatisticsGathering;	// IMP=0x3240a0f8
- (void)failedTest:(id)fp8;	// IMP=0x32409950
- (void)finishedTest:(id)fp8;	// IMP=0x32409930
- (void)finishedTest:(id)fp8 extraResults:(id)fp12;	// IMP=0x32408c5c
- (BOOL)handleTestURL:(id)fp8;	// IMP=0x32409ad0
- (BOOL)isRunningTest;	// IMP=0x3240883c
- (BOOL)launchedToTest;	// IMP=0x324083b4
- (BOOL)runTest:(id)fp8 options:(id)fp12;	// IMP=0x324083c8
- (BOOL)shouldExitAfterQuitTest;	// IMP=0x32408538
- (void)startCHUDRecording:(id)fp8;	// IMP=0x32409e8c
- (void)startLeaking;	// IMP=0x3240a338
- (void)startedTest:(id)fp8;	// IMP=0x3240886c
- (void)stopCHUDRecording;	// IMP=0x3240a06c
- (void)stopLeaking;	// IMP=0x3240a410
@end

