/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIPushButton;

@interface UIButtonBarCustomizeHeader : UIControl
{
    UIPushButton *_doneButton;
}

- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x3242540c
- (void)dealloc;	// IMP=0x3242110c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x324211c8
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x32421164
- (id)initWithFrame:(struct CGRect)fp8 target:(id)fp24;	// IMP=0x32426414
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x324211a4

@end

