/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <QuartzCore/QuartzCore.h>

@interface UICoverFlowLayer : CALayer
{
    void *_private;
}

- (unsigned int)_coverAtScreenPosition:(struct CGPoint)fp8;	// IMP=0x3244f878
- (void)_notifySelectionDidChange;	// IMP=0x3244f5cc
- (void)_prefetch:(unsigned int)fp8 atIndex:(unsigned int)fp12;	// IMP=0x3244f160
- (void)_recycleLayer:(int)fp8 to:(int)fp12;	// IMP=0x3244fbc8
- (void)_requestBatch;	// IMP=0x3244f1bc
- (void)_requestImageAtIndex:(int)fp8;	// IMP=0x3244f364
- (void)_requestImageAtIndex:(int)fp8 quality:(unsigned int)fp12;	// IMP=0x3244f2e4
- (void)_setNewSelectedIndex:(int)fp8;	// IMP=0x32455c90
- (void)_setupFlippedCoverLayer:(id)fp8;	// IMP=0x3245290c
- (void)_updateTick;	// IMP=0x3245346c
- (void)benchmarkHeartbeatLongScrub;	// IMP=0x32450c98
- (void)benchmarkHeartbeatScrubAndWait;	// IMP=0x32452560
- (void)benchmarkHeartbeatShortScrub;	// IMP=0x32452768
- (BOOL)benchmarkImageManager:(void *)fp8;	// IMP=0x32450e5c
- (void)benchmarkImageMode:(int)fp8;	// IMP=0x32451604
- (BOOL)benchmarkLoadScrub;	// IMP=0x32451d94
- (void)benchmarkLongScrubSpeed:(float)fp8;	// IMP=0x324516e8
- (void)benchmarkMode:(int)fp8;	// IMP=0x32451500
- (void)benchmarkPerformanceLog:(BOOL)fp8;	// IMP=0x32451668
- (void)benchmarkSetEnv;	// IMP=0x324510dc
- (void)benchmarkSkipImageLoad:(BOOL)fp8;	// IMP=0x32451728
- (int)benchmarkTick;	// IMP=0x32450a64
- (void)benchmarkTickMode:(int)fp8;	// IMP=0x324515b4
- (void)benchmarkTightLoop;	// IMP=0x32450d94
- (void)benchmarkTightLoopScrub;	// IMP=0x3245202c
- (void)benchmarkTightLoopTime:(unsigned int)fp8;	// IMP=0x324516b0
- (unsigned int)coverIndexAtPosition:(float)fp8;	// IMP=0x3245090c
- (void)dealloc;	// IMP=0x3244ebf0
- (void)displayTick;	// IMP=0x324531c8
- (void)dragFlow:(unsigned int)fp8 atPoint:(struct CGPoint)fp12;	// IMP=0x3244fe7c
- (void)flipSelectedCover;	// IMP=0x32450914
- (unsigned int)indexOfSelectedCover;	// IMP=0x3244f86c
- (id)initWithFrame:(struct CGRect)fp8 numberOfCovers:(unsigned int)fp24;	// IMP=0x32456d50
- (void)selectCoverAtIndex:(unsigned int)fp8;	// IMP=0x324508a0
- (void)selectCoverAtOffset:(int)fp8;	// IMP=0x324508e4
- (void)setDelegate:(id)fp8;	// IMP=0x3244ee00
- (void)setDisplayedOrientation:(int)fp8 animate:(BOOL)fp12;	// IMP=0x3244f6b4
- (void)setImage:(void *)fp8 atIndex:(unsigned int)fp12;	// IMP=0x32451d14
- (void)setImage:(void *)fp8 atIndex:(unsigned int)fp12 type:(unsigned int)fp16;	// IMP=0x3244f80c
- (void)setImage:(void *)fp8 atIndex:(unsigned int)fp12 type:(unsigned int)fp16 imageSubRect:(struct _NSRect)fp20;	// IMP=0x32451868
- (void)setInfoLayer:(id)fp8;	// IMP=0x324561ec
- (void)setPlaceholderImage:(void *)fp8;	// IMP=0x3244f128
- (void)transition:(unsigned int)fp8 withCoverFrame:(struct CGRect)fp12;	// IMP=0x324563a0
- (void)transitionIn:(float)fp8;	// IMP=0x32456cec
- (void)transitionIn:(float)fp8 fromFrame:(struct CGRect)fp12;	// IMP=0x3244f614
- (void)transitionOut:(float)fp8;	// IMP=0x32456c88
- (void)transitionOut:(float)fp8 toFrame:(struct CGRect)fp12;	// IMP=0x3244f664

@end

