/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPickerView.h>

@class NSDate, NSDateComponents, NSString, UITextLabel;

@interface UIDatePicker : UIPickerView
{
    NSDate *_date;
    NSDateComponents *_referenceComponents;
    double _todaySinceReferenceDate;
    NSDateComponents *_todayDateComponents;
    NSString *_amString;
    NSString *_pmString;
    UITextLabel *_hourLabel;
    UITextLabel *_minuteLabel;
    id _datePickerDelegate;
    int _numberOfDaysInCurrentMonth;
    NSDateComponents *_minDateComponents;
    NSDateComponents *_maxDateComponents;
    unsigned int _24HourMode:1;
    unsigned int _isCountdownTimer:1;
    unsigned int _staggerTimeIntervals:1;
    unsigned int _datePickerMode:3;
    unsigned int _loadingDateOrTime:1;
    unsigned int _highlightsToday:1;
    unsigned int _reserverd:24;
}

- (id)_createAccessoryViewWithText:(id)fp8 andFont:(struct __GSFont *)fp12;	// IMP=0x3245bc78
- (id)_createLabelWithString:(id)fp8 above:(id)fp12;	// IMP=0x3245c9b0
- (struct __GSFont *)_datePickerCellFont;	// IMP=0x32458a3c
- (int)_dayForRow:(int)fp8;	// IMP=0x3245a478
- (void)_doneLoadingDateOrTime;	// IMP=0x32458228
- (unsigned int)_elementForColumn:(int)fp8;	// IMP=0x32458cc8
- (void)_ensureTodayIsSet;	// IMP=0x3245b2c0
- (id)_fadeLabel:(id)fp8 toNewLabelWithString:(id)fp12 ifAnimated:(BOOL)fp16;	// IMP=0x32459ff0
- (int)_hourForRow:(int)fp8;	// IMP=0x3245a4b4
- (id)_hoursString;	// IMP=0x3245a2a4
- (struct __GSFont *)_hrMinFont;	// IMP=0x32458acc
- (int)_incrementForElement:(unsigned int)fp8;	// IMP=0x32458204
- (int)_incrementedAmountForValue:(int)fp8 withElement:(unsigned int)fp12;	// IMP=0x32458fe0
- (void)_loadDateAnimated:(BOOL)fp8;	// IMP=0x3245944c
- (void)_loadDesignatorStrings;	// IMP=0x3245cb94
- (int)_maxNumberOfDaysInMonth;	// IMP=0x32458b00
- (int)_minuteForRow:(int)fp8;	// IMP=0x324598d8
- (id)_minutesString;	// IMP=0x3245a27c
- (int)_monthForRow:(int)fp8;	// IMP=0x3245b3d8
- (id)_monthLongNameAtIndex:(int)fp8;	// IMP=0x32458c74
- (int)_monthNameCount;	// IMP=0x3245cd04
- (int)_numberOfDaysInDate:(id)fp8;	// IMP=0x32458da4
- (int)_numberOfDaysInWeek;	// IMP=0x32458b08
- (BOOL)_scrollingAnyColumnExcept:(int)fp8;	// IMP=0x3245a84c
- (int)_secondForRow:(int)fp8;	// IMP=0x324598f8
- (int)_selectedHourForColumn:(int)fp8;	// IMP=0x32459860
- (int)_selectedMinuteForColumn:(int)fp8;	// IMP=0x3245989c
- (void)_setDateComponent:(id)fp8 forColumn:(int)fp12;	// IMP=0x32459918
- (void)_setupCell:(id)fp8 atRow:(int)fp12 inColumn:(int)fp16 withElementFlag:(unsigned int)fp20;	// IMP=0x3245bed4
- (BOOL)_shouldEnableDayForRow:(int)fp8 column:(int)fp12;	// IMP=0x3245a500
- (BOOL)_shouldEnableHourForValue:(int)fp8 column:(int)fp12;	// IMP=0x3245ab00
- (BOOL)_shouldEnableMinuteForValue:(int)fp8 column:(int)fp12;	// IMP=0x3245a8bc
- (BOOL)_shouldEnableMonthForRow:(int)fp8 column:(int)fp12;	// IMP=0x3245a700
- (BOOL)_shouldEnableWeekMonthDayForCell:(id)fp8;	// IMP=0x3245ad5c
- (BOOL)_shouldEnableYearForRow:(int)fp8;	// IMP=0x3245ace4
- (BOOL)_showingDate;	// IMP=0x32458238
- (struct __GSFont *)_timeSeparatorFont;	// IMP=0x32458ab0
- (struct CGColor *)_todayTextColor;	// IMP=0x3245b278
- (void)_updateBitsForDate:(id)fp8 andReload:(BOOL)fp12;	// IMP=0x32458554
- (BOOL)_updateDateOrTime;	// IMP=0x32459cb4
- (void)_updateEnabledCells:(BOOL)fp8;	// IMP=0x3245aff0
- (void)_updateLabels:(BOOL)fp8;	// IMP=0x3245a2cc
- (void)_updateMaxDaysForDate;	// IMP=0x32458e00
- (void)_updateReferenceBits;	// IMP=0x32458254
- (void)_updateRowInColumn:(int)fp8 toValue:(int)fp12 withRepeatingAmount:(int)fp16 element:(unsigned int)fp20 animated:(BOOL)fp24;	// IMP=0x324590f0
- (int)_weekdayNameCount;	// IMP=0x32458b6c
- (id)_weekdayShortNameAtIndex:(int)fp8;	// IMP=0x32458c20
- (id)date;	// IMP=0x32458a34
- (id)dateComponents;	// IMP=0x3245b42c
- (int)datePickerMode;	// IMP=0x32458f94
- (void)dealloc;	// IMP=0x324580ec
- (int)hour;	// IMP=0x324589b0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32457fc0
- (int)minute;	// IMP=0x324589dc
- (int)numberOfColumnsInPickerView:(id)fp8;	// IMP=0x32458d40
- (id)pickerImageNamePrefix;	// IMP=0x324581a8
- (void)pickerView:(id)fp8 createdTable:(id)fp12 forColumn:(int)fp16;	// IMP=0x3245bdfc
- (int)pickerView:(id)fp8 numberOfRowsInColumn:(int)fp12;	// IMP=0x32459078
- (id)pickerView:(id)fp8 tableCellForRow:(int)fp12 inColumn:(int)fp16 reusingCell:(id)fp20;	// IMP=0x3245baa8
- (float)pickerView:(id)fp8 tableWidthForColumn:(int)fp12;	// IMP=0x3245b73c
- (void)pickerViewLoaded:(id)fp8;	// IMP=0x32459838
- (void)pickerViewSelectionChanged:(id)fp8;	// IMP=0x3245a3f4
- (void)scrollerDidScroll:(id)fp8;	// IMP=0x324582e4
- (void)scrollerWillStartDragging:(id)fp8;	// IMP=0x3245afd0
- (int)second;	// IMP=0x32458a08
- (void)setDate:(id)fp8;	// IMP=0x32458868
- (void)setDateComponents:(id)fp8;	// IMP=0x3245b470
- (void)setDatePickerMode:(int)fp8;	// IMP=0x32458e28
- (void)setDelegate:(id)fp8;	// IMP=0x32459858
- (void)setHighlightsToday:(BOOL)fp8;	// IMP=0x3245b414
- (void)setMaximumDate:(id)fp8;	// IMP=0x3245891c
- (void)setMinimumDate:(id)fp8;	// IMP=0x32458888
- (void)setStaggerTimeIntervals:(BOOL)fp8;	// IMP=0x32458fa4
- (void)setTimeInterval:(double)fp8;	// IMP=0x3245b4d0
- (struct CGColor *)shadowColor;	// IMP=0x3245bc64
- (float)tableRowHeight;	// IMP=0x32458d98
- (double)timeInterval;	// IMP=0x3245b6b4

@end

