/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControlTargetAction.h>

@interface UIDelayedControlTargetAction : UIControlTargetAction
{
    struct __GSEvent *_event;
}

- (void)dealloc;	// IMP=0x323eeeb0

@end

