/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIDefaultWebViewFormEditingDelegate : NSObject
{
}

- (id)calloutSuperviewForWebView:(id)fp8;	// IMP=0x32405f60
- (int)orientationForWebView:(id)fp8;	// IMP=0x32405f58
- (void)webView:(id)fp8 didBeginEditingFormElement:(id)fp12;	// IMP=0x32405f50
- (void)webView:(id)fp8 didEndEditingFormElement:(id)fp12;	// IMP=0x32405f48
- (void)webView:(id)fp8 willBeginEditingFormElement:(id)fp12;	// IMP=0x32405f54
- (void)webView:(id)fp8 willEndEditingFormElement:(id)fp12;	// IMP=0x32405f4c
- (void)webViewDidBeginEditingFormElements:(id)fp8;	// IMP=0x32405f40
- (void)webViewDidEndEditingFormElements:(id)fp8;	// IMP=0x32405f38
- (void)webViewWillBeginEditingFormElements:(id)fp8;	// IMP=0x32405f44
- (void)webViewWillEndEditingFormElements:(id)fp8;	// IMP=0x32405f3c

@end

