/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UITable, UITextField;

@interface UIFontChooser : UIView
{
    UITable *_nameTable;
    UITable *_sizeTable;
    UITextField *_sizeField;
    struct __CFArray *_familyNames;
    id _delegate;
    unsigned int _sizes[15];
    unsigned int _sizeBeforeEditing;
}

+ (id)sharedFontChooser;	// IMP=0x3241e918
- (struct CGRect)_fieldBackgroundFrame;	// IMP=0x3241e648
- (void)_finishedEditing:(id)fp8;	// IMP=0x3241e458
- (struct CGRect)_nameTableFrame;	// IMP=0x3241d8fc
- (struct CGRect)_separatorFrame;	// IMP=0x3241d998
- (struct CGRect)_sizeFieldFrame;	// IMP=0x3241e82c
- (struct CGRect)_sizeTableFrame;	// IMP=0x3241da28
- (id)_tableWithFrame:(struct CGRect)fp8;	// IMP=0x3241d748
- (void)_updateSublayerFrames;	// IMP=0x3241dac0
- (void)acceptSizeFromSizeField;	// IMP=0x3241e3d4
- (id)delegate;	// IMP=0x3241e640
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3241e078
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3241dbc8
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x3241e110
- (void)selectFamilyName:(id)fp8;	// IMP=0x3241e2a0
- (void)selectFont:(struct __GSFont *)fp8;	// IMP=0x3241e378
- (void)selectSize:(float)fp8;	// IMP=0x3241e6f4
- (id)selectedFamilyName;	// IMP=0x3241e5ac
- (float)selectedSize;	// IMP=0x3241e5fc
- (void)setDelegate:(id)fp8;	// IMP=0x3241e638
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x3241df84
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;	// IMP=0x3241e144
- (void)tableSelectionDidChange:(id)fp8;	// IMP=0x3241e474
- (void)textFieldDidBecomeFirstResponder:(id)fp8;	// IMP=0x3241e4e8
- (void)textFieldDidResignFirstResponder:(id)fp8;	// IMP=0x3241e55c

@end

