/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIImage.h>

@interface UIImage (Internal)
- (BOOL)_isCached;	// IMP=0x323bc508
- (BOOL)_isNamed;	// IMP=0x323bc530
- (void)_setCached:(BOOL)fp8;	// IMP=0x323bc4f0
- (void)_setNamed:(BOOL)fp8;	// IMP=0x323bc518
@end

