/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UINavigationBar.h>

@interface UINavigationBar (Static)
- (void)_adjustVisibleItemsByDelta:(float)fp8;	// IMP=0x323d53a0
- (void)_backgroundFadeDidFinish:(id)fp8 finished:(id)fp12 context:(void *)fp16;	// IMP=0x323d4200
- (int)_barStyle:(BOOL)fp8;	// IMP=0x323d5778
- (float)_barWidth;	// IMP=0x323d743c
- (struct CGRect)_boundsForPrompt:(id)fp8 inRect:(struct CGRect)fp12 withFont:(struct __GSFont *)fp28 barStyle:(int)fp32;	// IMP=0x323d8b90
- (void)_broadcastNewTopToItems:(int)fp8 complete:(BOOL)fp12;	// IMP=0x323d54ec
- (id)_currentBackButton;	// IMP=0x323d532c
- (void)_drawPrompt:(id)fp8 inRect:(struct CGRect)fp12 withFont:(struct __GSFont *)fp28 barStyle:(int)fp32;	// IMP=0x323d8910
- (void)_fadeViewOut:(id)fp8;	// IMP=0x323d5194
- (void)_fadeViewsIn:(id)fp8;	// IMP=0x323d5288
- (void)_fadeViewsOut:(id)fp8;	// IMP=0x323d5210
- (void)_getBackButtonRect:(struct CGRect *)fp8 titleRect:(struct CGRect *)fp12;	// IMP=0x323d907c
- (BOOL)_hasBackButton;	// IMP=0x323d5300
- (void)_navBarButtonPressed:(id)fp8;	// IMP=0x323d5850
- (void)_removeAccessoryView;	// IMP=0x323d3ee0
- (void)_removeItemsFromSuperview:(id)fp8;	// IMP=0x323d50d4
- (void)_startBarStyleAnimation:(int)fp8;	// IMP=0x323d4040
- (void)_startPopAnimation;	// IMP=0x323d498c
- (void)_startPushAnimation;	// IMP=0x323d4238
- (void)layoutSubviews;	// IMP=0x323d562c
@end

