/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface UIOnePartImageView : UIView
{
    struct CGRect _fromRect;
    UIImage *_image;
}

- (void)dealloc;	// IMP=0x32412104
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x324121a0
- (void)setFromRect:(struct CGRect)fp8;	// IMP=0x32412184
- (void)setImage:(id)fp8;	// IMP=0x3241215c

@end

