/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, _UIPickerViewTopFrame;

@interface UIPickerView : UIView
{
    NSMutableArray *_tables;
    _UIPickerViewTopFrame *_topFrame;
    NSMutableArray *_dividers;
    id _delegate;
    UIView *_backgroundView;
    unsigned int _needsLayout:1;
    unsigned int _delegateRespondsToTableCellForColumn:1;
    unsigned int _delegateRespondsToTableCellForColumnReusingCell:1;
    unsigned int _delegateRespondsToTitleForRow:1;
    unsigned int _delegateRespondsToCreatedTable:1;
    unsigned int _showsSelectionBar:1;
    unsigned int _allowsMultipleSelection:1;
    unsigned int _allowSelectingCells:1;
    unsigned int _soundsEnabled:1;
    unsigned int _reserved:22;
}

+ (BOOL)_isLandscapeOrientation;	// IMP=0x323adb4c
+ (id)_orientationImageSuffix;	// IMP=0x323adba0
+ (struct CGSize)defaultSize;	// IMP=0x323b0794
- (id)_createViewForPickerPiece:(int)fp8;	// IMP=0x323ae2e8
- (int)_delegateNumberOfColumns;	// IMP=0x323ae864
- (int)_delegateNumberOfRowsInColumn:(int)fp8;	// IMP=0x323ae8b4
- (float)_delegateTableWidthAtColumn:(int)fp8 ofCount:(int)fp12 withSizeLeft:(float)fp16;	// IMP=0x323b0648
- (id)_delegateTitleForRow:(int)fp8 inColumn:(int)fp12;	// IMP=0x323ae90c
- (id)_selectionBarSuffix;	// IMP=0x323adfc0
- (void)_sendCheckedRow:(int)fp8 inTable:(id)fp12 checked:(BOOL)fp16;	// IMP=0x323af4a0
- (void)_sendSelectionChanged;	// IMP=0x323af3c4
- (void)_sendSelectionChangedFromTable:(id)fp8;	// IMP=0x323af63c
- (BOOL)allowsMultipleSelection;	// IMP=0x323af490
- (id)cellForRow:(int)fp8 column:(int)fp12;	// IMP=0x323af7a0
- (int)columnForTable:(id)fp8;	// IMP=0x323af8c0
- (id)createDividerWithFrame:(struct CGRect)fp8;	// IMP=0x323ae41c
- (id)_createTableWithFrame:(struct CGRect)fp8 forComponent:(id):fp8;	// IMP=0x323ae590
- (void)dealloc;	// IMP=0x323addec
- (id)imageForPickerPiece:(int)fp8;	// IMP=0x323adfec
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323adc58
- (void)layoutSubviews;	// IMP=0x323af99c
- (int)numberOfColumns;	// IMP=0x323ae9a0
- (int)numberOfRowsInColumn:(int)fp8;	// IMP=0x323ae948
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x323aec90
- (id)pickerImageNamePrefix;	// IMP=0x323adfb0
- (void)reloadAllPickerPieces;	// IMP=0x323ae9e0
- (void)reloadData;	// IMP=0x323adecc
- (void)reloadDataForColumn:(int)fp8;	// IMP=0x323adf74
- (double)scrollAnimationDuration;	// IMP=0x323ae57c
- (struct CGPoint)scroller:(id)fp8 adjustSmoothScrollEnd:(struct CGPoint)fp12 velocity:(struct CGSize)fp20;	// IMP=0x323af2a4
- (BOOL)scroller:(id)fp8 shouldAdjustSmoothScrollEndForVelocity:(struct CGSize)fp12;	// IMP=0x323af234
- (void)scrollerDidEndAnimatedScrolling:(id)fp8;	// IMP=0x323af784
- (void)scrollerDidEndDragging:(id)fp8 willSmoothScroll:(BOOL)fp12;	// IMP=0x323af6d8
- (void)scrollerDidEndSmoothScrolling:(id)fp8;	// IMP=0x323af728
- (void)scrollerDidScroll:(id)fp8;	// IMP=0x323af088
- (void)selectRow:(int)fp8 inColumn:(int)fp12 animated:(BOOL)fp16;	// IMP=0x323af958
- (int)selectedRowForColumn:(int)fp8;	// IMP=0x323af890
- (id)selectedTableCellForColumn:(int)fp8;	// IMP=0x323af928
- (struct CGRect)selectionBarRect;	// IMP=0x323ae1fc
- (void)setAllowsMultipleSelection:(BOOL)fp8;	// IMP=0x323af410
- (void)setDelegate:(id)fp8;	// IMP=0x323aefa4
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x323aea08
- (void)setNeedsLayout;	// IMP=0x323ade80
- (void)setSoundsEnabled:(BOOL)fp8;	// IMP=0x323adbec
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;	// IMP=0x323aef70
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16 reusing:(id)fp20;	// IMP=0x323aed8c
- (id)tableForColumn:(int)fp8;	// IMP=0x323af8e0
- (float)tableRowHeight;	// IMP=0x323ae538
- (struct _NSRange)visibleRowsForColumn:(int)fp8;	// IMP=0x323af7e0

@end

