/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPushButton.h>

@interface UIPushButton (Original)
- (id)image;	// IMP=0x323f16f8
- (void)setHighlightedTitleColor:(struct CGColor *)fp8;	// IMP=0x323f1738
- (void)setImage:(id)fp8;	// IMP=0x323f16b8
- (void)setPressedImage:(id)fp8;	// IMP=0x323f16d8
- (void)setShadowColor:(struct CGColor *)fp8;	// IMP=0x323f1778
- (void)setTitleColor:(struct CGColor *)fp8;	// IMP=0x323f1718
- (struct CGColor *)titleColor;	// IMP=0x323f1758
@end

