/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIResponder.h>

@interface UIResponder (Static)
- (unsigned int)_becomeFirstResponderWhenPossible;	// IMP=0x3240e0c8
- (id)_firstResponder;	// IMP=0x3240e098
- (id)_responderForBecomeFirstResponder;	// IMP=0x3240e0c4
- (void)_setFirstResponder:(id)fp8;	// IMP=0x3240e064
@end

