/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString;

@interface UIScrubberTimeView : UIView
{
    NSString *_time;
    unsigned int _align:2;
}

- (void)dealloc;	// IMP=0x32462a5c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x324648d4
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324629d4
- (void)setTime:(id)fp8;	// IMP=0x32462ab4
- (id)time;	// IMP=0x32462b2c

@end

