/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIScrollerScrollAnimation : UIAnimation
{
    struct CGPoint _originalOffset;
    struct CGPoint _targetOffset;
}

- (void)setOriginalOffset:(struct CGPoint)fp8;	// IMP=0x323c939c
- (void)setProgress:(float)fp8;	// IMP=0x323cdaa0
- (void)setTargetOffset:(struct CGPoint)fp8;	// IMP=0x323c9390
- (struct CGPoint)targetOffset;	// IMP=0x323c9380

@end

