/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface UISliderFillView : UIView
{
    UIImage *_sliderImage;
}

- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32448f7c
- (id)initWithFrame:(struct CGRect)fp8 image:(id)fp24;	// IMP=0x32448ec0

@end

