/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPushButton.h>

@interface UISliderButton : UIPushButton
{
}

- (BOOL)cancelMouseTracking;	// IMP=0x3244901c
- (BOOL)ignoresMouseEvents;	// IMP=0x32449014
- (BOOL)shouldTrack;	// IMP=0x3244900c

@end

