/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIImage;

@interface UISwitchControlButton : UIControl
{
    UIImage *_leftCap;
    UIImage *_middleFill;
    UIImage *_rightCap;
    UIImage *_leftCapDown;
    UIImage *_middleFillDown;
    UIImage *_rightCapDown;
    unsigned int _useShadowedLeft:1;
    unsigned int _useShadowedRight:1;
}

- (void)_drawThreePartButtonInRect:(struct CGRect)fp8;	// IMP=0x3244c098
- (void)dealloc;	// IMP=0x3244c000
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3244c4a8
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3244bf18
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x3244d4ec
- (BOOL)shouldTrack;	// IMP=0x3244bff8

@end

