/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITextTraits.h>

@interface UITextTraits (Deprecated)
- (id)autoSeparatorString;	// IMP=0x324ab564
- (BOOL)isSecure;	// IMP=0x324ab594
- (void)setAutoSeparatorString:(id)fp8;	// IMP=0x324ab56c
- (void)setSecure:(BOOL)fp8;	// IMP=0x324ab5b4
- (void)setShowsExtraSuggestions:(BOOL)fp8;	// IMP=0x324ab590
- (void)setSuggestionBarTextSize:(int)fp8;	// IMP=0x324ab584
- (void)setSuggestionBarVisibility:(int)fp8;	// IMP=0x324ab578
- (BOOL)showsExtraSuggestions;	// IMP=0x324ab588
- (int)suggestionBarTextSize;	// IMP=0x324ab57c
- (int)suggestionBarVisibility;	// IMP=0x324ab570
@end

