/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIWebView;

@interface UITextLoupe : UIView
{
    UIWebView *m_webView;
    struct {
        struct CGPoint point;
        double time;
    } m_points[16];
    int m_index;
    float m_yOffset;
    BOOL m_firstUpdate;
    BOOL m_topConstrained;
}

+ (void)cancelLoupeTimer;	// IMP=0x3249630c
+ (void)touchLoupeTimer:(id)fp8;	// IMP=0x32496228
- (void)clearPoints;	// IMP=0x32496e10
- (void)dealloc;	// IMP=0x32496430
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32496e5c
- (void)fade;	// IMP=0x32496d34
- (struct CGRect)frame;	// IMP=0x324964c8
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3249635c
- (void)remove;	// IMP=0x32496d70
- (void)setTopConstrained:(BOOL)fp8;	// IMP=0x32496580
- (void)setWebView:(id)fp8;	// IMP=0x32496520
- (id)superview;	// IMP=0x32496488
- (struct CGPoint)terminalPoint;	// IMP=0x324969a4
- (void)update:(struct CGPoint)fp8;	// IMP=0x324966ec
- (void)zoomDownAnimation;	// IMP=0x32496ad0
- (void)zoomDownAnimationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x32496d00
- (void)zoomUpAnimation;	// IMP=0x324965a8

@end

