/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITextFieldBackground : UIView
{
    BOOL _isActive;
    float _value;
}

- (BOOL)isActive;	// IMP=0x324adb8c
- (float)progress;	// IMP=0x324adb9c
- (void)setActive:(BOOL)fp8;	// IMP=0x324adb84
- (void)setProgress:(float)fp8;	// IMP=0x324adb94

@end

