/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITile : UIView
{
    struct CGRect _dirtyRect;
    BOOL _hasDrawnContent;
}

- (BOOL)_canDrawContent;	// IMP=0x32439194
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3243922c
- (BOOL)hasDrawnContent;	// IMP=0x324393c0
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x32439008
- (void)invalidateContents;	// IMP=0x324394e8
- (void)setDirtyRect:(struct CGRect)fp8;	// IMP=0x324393c8
- (void)setNeedsDisplay;	// IMP=0x3243912c
- (void)setNeedsDisplayInDirtyRect;	// IMP=0x32439434
- (void)setNeedsDisplayInRect:(struct CGRect)fp8;	// IMP=0x32439010
- (BOOL)willDrawContent;	// IMP=0x324391e0

@end

