/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "CALayer.h"

@interface WebLayer : CALayer
{
    BOOL _layoutsSuspended;
}

- (void)setLayoutsSuspended:(BOOL)fp8;	// IMP=0x324005ec
- (void)setNeedsLayout;	// IMP=0x324005a0

@end

