/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface _UIAlertStackWatcher : NSObject
{
}

- (void)_appSuspended:(id)fp8;	// IMP=0x32415bc4
- (void)_resumeWithNotification:(id)fp8;	// IMP=0x32415ca8
- (void)dealloc;	// IMP=0x32415c34
- (id)init;	// IMP=0x32415ac0

@end

