/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (UIKBExtras)
- (id)_kb_firstObject;	// IMP=0x324a1368
- (BOOL)_kb_firstObjectsEqual:(unsigned int)fp8;	// IMP=0x324a13cc
- (BOOL)_kb_firstTwoObjectsEqual;	// IMP=0x324a13a8
@end

