/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface NSString (UIStringDrawing)
- (void)clearStringDrawingOrigin;	// IMP=0x323be2f0
- (struct CGSize)drawAtPoint:(struct CGPoint)fp8 forWidth:(float)fp16 withFont:(struct __GSFont *)fp20 ellipsis:(int)fp24;	// IMP=0x323be420
- (struct CGSize)drawAtPoint:(struct CGPoint)fp8 withFont:(struct __GSFont *)fp16;	// IMP=0x323be3ac
- (void)drawAtPoint:(struct CGPoint)fp8 withStyle:(id)fp16;	// IMP=0x323be0b4
- (struct CGSize)drawInRect:(struct CGRect)fp8 withFont:(struct __GSFont *)fp24;	// IMP=0x323be5e8
- (struct CGSize)drawInRect:(struct CGRect)fp8 withFont:(struct __GSFont *)fp24 ellipsis:(int)fp28;	// IMP=0x323be4e4
- (struct CGSize)drawInRect:(struct CGRect)fp8 withFont:(struct __GSFont *)fp24 ellipsis:(int)fp28 alignment:(int)fp32;	// IMP=0x323be560
- (void)drawInRect:(struct CGRect)fp8 withStyle:(id)fp24;	// IMP=0x323be804
- (void)drawMarkupAtPoint:(struct CGPoint)fp8;	// IMP=0x323be160
- (void)drawMarkupInRect:(struct CGRect)fp8;	// IMP=0x323be1c0
- (void)setStringDrawingOrigin:(struct CGPoint)fp8;	// IMP=0x323be2a8
- (struct CGSize)sizeInRect:(struct CGRect)fp8 withFont:(struct __GSFont *)fp24;	// IMP=0x323be6dc
- (struct CGSize)sizeInRect:(struct CGRect)fp8 withFont:(struct __GSFont *)fp24 ellipsis:(int)fp28;	// IMP=0x323be65c
- (struct CGSize)sizeWithFont:(struct __GSFont *)fp8;	// IMP=0x323be328
- (struct CGSize)sizeWithFont:(struct __GSFont *)fp8 forWidth:(float)fp12 ellipsis:(int)fp16;	// IMP=0x323be360
- (struct CGSize)sizeWithMarkupForWidth:(float)fp8;	// IMP=0x323be240
- (struct CGSize)sizeWithStyle:(id)fp8 forWidth:(float)fp12;	// IMP=0x323be750
@end

