/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

@interface SBSuspensionWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x323b0fa8
- (BOOL)_canExistBeyondSuspension;	// IMP=0x323b0fcc

@end

