/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIImageAndTextTableCell.h>

@interface UIAlertSheetTableCell : UIImageAndTextTableCell
{
}

- (void)drawSeparatorInRect:(struct CGRect)fp8;	// IMP=0x32417b8c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32417428
- (void)setBackgroundColor:(struct CGColor *)fp8;	// IMP=0x32415d24
- (void)updateHighlightColors;	// IMP=0x32415d28

@end

