/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

typedef enum {
    kUIAnimationCurveEaseInEaseOut,
    kUIAnimationCurveEaseIn,
    kUIAnimationCurveEaseOut,
    kUIAnimationCurveLinear
} UIAnimationCurve;

@interface UIAnimation : NSObject {}

- (id)initWithTarget:(id)target;
- (id)target;

- (SEL)action;
- (void)setAction:(SEL)action;

- (void)setAnimationCurve:(UIAnimationCurve)animationCurve;

- (id)delegate;
- (void)setDelegate:(id)delegate;

- (float)progressForFraction:(float)fraction;
- (void)setProgress:(float)progress;

- (void)stopAnimation;

@end

@interface UIAnimation (Internal)
- (float)fractionForTime:(double)time;	
- (void)markStart:(double)fp8;	
- (void)markStop;	
- (void)setDuration:(double)duration;	
- (int)state;	
- (BOOL)tvOutput;	
@end
