/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface UIAnimator : NSObject
{
    NSMutableArray *_animations;
    double _lastUpdateTime;
    struct __GSHeartbeat *_lcdHeartbeat;
    struct __GSHeartbeat *_tvHeartbeat;
    int _lcdCount;
    int _tvCount;
}

+ (void)disableAnimation;	// IMP=0x323fbbe8
+ (void)enableAnimation;	// IMP=0x323fbc00
+ (id)sharedAnimator;	// IMP=0x323fbb1c
- (void)addAnimation:(id)fp8 withDuration:(double)fp12 start:(BOOL)fp20;	// IMP=0x323fbd08
- (void)addAnimations:(id)fp8 withDuration:(double)fp12 start:(BOOL)fp20;	// IMP=0x323fbd90
- (void)dealloc;	// IMP=0x323fbc18
- (float)fractionForAnimation:(id)fp8;	// IMP=0x323fc270
- (void)removeAnimationsForTarget:(id)fp8;	// IMP=0x323fbe80
- (void)removeAnimationsForTarget:(id)fp8 ofKind:(Class)fp12;	// IMP=0x323fbf2c
- (void)startAnimation:(id)fp8;	// IMP=0x323fc008
- (void)stopAnimation:(id)fp8;	// IMP=0x323fc04c

@end

