/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIAutocorrectShadowView : UIView
{
    int m_edgeType;
}

- (void)drawRect:(struct CGRect)fp8;	// IMP=0x324a1b9c
- (void)setEdgeType:(int)fp8;	// IMP=0x324a1b70

@end

