/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIButtonBar.h>

@interface UIButtonBar (UIButtonBarButtonItem)
- (id)initInView:(id)fp8 withFrame:(struct CGRect)fp12 withItems:(CDAnonymousStruct2 *)fp28 withCount:(int)fp32;	// IMP=0x324220d0
- (id)initInView:(id)fp8 withItems:(CDAnonymousStruct2 *)fp12 withCount:(int)fp16;	// IMP=0x32425940
@end

