/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIImageView, UIPushButton, UITextLabel;

@interface UICalloutView : UIControl
{
    UIImageView *_leftCap;
    UIImageView *_rightCap;
    UIImageView *_topAnchor;
    UIImageView *_bottomAnchor;
    UIImageView *_leftBackground;
    UIImageView *_rightBackground;
    UIPushButton *_button;
    UITextLabel *_title;
    UITextLabel *_subtitle;
    struct {
        struct CGPoint origin;
        struct CGPoint offset;
        int position;
    } _anchor;
    struct CGRect _frame;
    id _delegate;
    struct {
        unsigned int animated:1;
        unsigned int didMoveSelectorCalled:1;
        unsigned int reserved:30;
    } _flags;
}

+ (id)_backgroundImage;	// IMP=0x32465da8
+ (id)_bottomAnchorImage;	// IMP=0x32465e18
+ (id)_buttonImage;	// IMP=0x32465d70
+ (id)_buttonImagePressed;	// IMP=0x32465d8c
+ (id)_leftCapImage;	// IMP=0x32465dc4
+ (id)_rightCapImage;	// IMP=0x32465de0
+ (id)_topAnchorImage;	// IMP=0x32465dfc
+ (float)defaultHeight;	// IMP=0x32465e34
+ (id)sharedCalloutView;	// IMP=0x32465e40
- (void)_setOriginForScale:(float)fp8;	// IMP=0x32466e88
- (void)addTarget:(id)fp8 action:(SEL)fp12;	// IMP=0x324667e8
- (struct CGPoint)anchorPoint;	// IMP=0x32466658
- (void)animationDidStop:(id)fp8 finished:(id)fp12;	// IMP=0x32466a40
- (void)completeBounceAnimation;	// IMP=0x324668fc
- (void)dealloc;	// IMP=0x32466500
- (id)delegate;	// IMP=0x32466844
- (void)fadeOutWithDuration:(float)fp8;	// IMP=0x324666dc
- (void)getActualAnchorPoint:(struct CGPoint *)fp8 frame:(struct CGRect *)fp12 position:(int *)fp16 forDesiredAnchorPoint:(struct CGPoint)fp20 boundaryRect:(struct CGRect)fp28;	// IMP=0x32466f44
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3246684c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32465ec4
- (struct CGPoint)offset;	// IMP=0x32466648
- (void)removeTarget:(id)fp8;	// IMP=0x32466818
- (void)setAnchorPoint:(struct CGPoint)fp8 boundaryRect:(struct CGRect)fp16 animate:(BOOL)fp32;	// IMP=0x324673d0
- (void)setDelegate:(id)fp8;	// IMP=0x3246683c
- (void)setOffset:(struct CGPoint)fp8;	// IMP=0x3246663c
- (void)setSubtitle:(id)fp8;	// IMP=0x324665fc
- (void)setTitle:(id)fp8;	// IMP=0x324665bc
- (id)subtitle;	// IMP=0x3246661c
- (id)title;	// IMP=0x324665dc

@end

