/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UICheckbox.h>

@interface UICheckbox (Static)
+ (struct __GSFont *)_defaultFont;	// IMP=0x323f7b28
- (void)_sizeToFit;	// IMP=0x323f7b3c
@end

