/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@interface UIControl (Internal)
- (void)_cancelDelayedActions;	// IMP=0x323efda8
- (void)_delayActions;	// IMP=0x323efd78
- (BOOL)_hasActionForEventMask:(int)fp8;	// IMP=0x323efa64
- (void)_sendActionsForEventMask:(int)fp8 withEvent:(struct __GSEvent *)fp12;	// IMP=0x323efadc
- (void)_sendDelayedActions;	// IMP=0x323efd88
- (void)_setHighlightOnMouseDown:(BOOL)fp8;	// IMP=0x323efd58
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x323efde0
@end

