/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UICompletionTablePrivate;

@interface UICompletionTable : UIView
{
    UICompletionTablePrivate *_private;
}

+ (struct __GSFont *)_cellFont;	// IMP=0x324655e8
+ (id)_shadowImage;	// IMP=0x324655fc
- (id)_completionForRow:(int)fp8;	// IMP=0x32465b88
- (void)dealloc;	// IMP=0x3246599c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32465694
- (void)layoutSubviews;	// IMP=0x324659f4
- (int)numberOfRowsInTable:(id)fp8;	// IMP=0x32465b60
- (void)reloadData;	// IMP=0x32465af0
- (void)setDelegate:(id)fp8;	// IMP=0x32465ae4
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16 reusing:(id)fp20;	// IMP=0x32465bc0
- (void)tableSelectionDidChange:(id)fp8;	// IMP=0x32465cf0

@end

