/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIFingerInfo : NSObject
{
    struct __CFDictionary *_fingers;
    int _activeFinger;
    BOOL _activeFingerLocked;
}

- (BOOL)chordChanged:(CDAnonymousStruct12)fp8 withEvent:(struct __GSEvent *)fp28 adjustLocation:(BOOL)fp32;	// IMP=0x323c262c
- (void)dealloc;	// IMP=0x323beadc
- (BOOL)fingersMoved:(CDAnonymousStruct12)fp8 withEvent:(struct __GSEvent *)fp28 adjustLocation:(BOOL)fp32;	// IMP=0x323bebe0
- (BOOL)hasActiveFinger;	// IMP=0x323bed6c
- (void)startTouch:(CDAnonymousStruct12)fp8 withEvent:(struct __GSEvent *)fp28 adjustLocation:(BOOL)fp32;	// IMP=0x323beb30

@end

