/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIFrameAnimation : UIAnimation
{
    struct CGRect _startFrame;
    struct CGRect _endFrame;
    int _fieldsToChange;
}

- (struct CGRect)endFrame;	// IMP=0x323fcdec
- (id)initWithTarget:(id)fp8;	// IMP=0x323fcd68
- (void)setEndFrame:(struct CGRect)fp8;	// IMP=0x323fcdd0
- (void)setProgress:(float)fp8;	// IMP=0x323fd050
- (void)setSignificantRectFields:(int)fp8;	// IMP=0x323fce04
- (void)setStartFrame:(struct CGRect)fp8;	// IMP=0x323fcdb4

@end

