/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIGestureAnimation : UIAnimation
{
    SEL _progressSelector;
    int _gestureType;
}

- (int)gestureType;	// IMP=0x32432948
- (id)initWithTarget:(id)fp8 progressSelector:(SEL)fp12 gestureType:(int)fp16;	// IMP=0x324328a4
- (void)setProgress:(float)fp8;	// IMP=0x324328f8

@end

