/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIRemoveControl.h>

@interface UIInsertControl : UIRemoveControl
{
}

- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x32465508

@end

