/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UINavigationBar.h>

@interface UINavigationBar (Deprecated)
- (void)navigationItemChanged:(id)fp8;	// IMP=0x323d58b8
@end

