/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@interface UIPopup : UIControl
{
    int _selectedIndex;
    struct CGRect _saveFrame;
    struct CGRect _highlightRect;
    int _highlightIndex;
    struct {
        unsigned int stillTracking:1;
        unsigned int reserved:31;
    } _popupFlags;
}

- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x323ffe68
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x32400148
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323ffd64
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x32400178
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x323ffde4
- (int)indexOfSelectedItem;	// IMP=0x323ffd5c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323ffc9c
- (void)selectItemAtIndex:(int)fp8;	// IMP=0x323ffd30

@end

