/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface UIReachabilityManager : NSObject
{
    NSMutableDictionary *_requests;
}

+ (id)sharedReachabilityManager;	// IMP=0x324b3844
- (void)addObserver:(id)fp8 forHostname:(id)fp12;	// IMP=0x324b3968
- (void)dealloc;	// IMP=0x324b3910
- (id)init;	// IMP=0x324b3898
- (void)removeObserver:(id)fp8 forHostname:(id)fp12;	// IMP=0x324b3a6c

@end

