/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString;

@interface UISectionHeaderCell : UIView
{
    NSString *_title;
    struct {
        unsigned int style:1;
        unsigned int reserved:31;
    } _sectionHeaderCellFlags;
}

+ (struct __GSFont *)defaultTitleFont;	// IMP=0x323fb180
- (struct CGRect)_rectForTitle:(id)fp8;	// IMP=0x323fb91c
- (BOOL)_shouldTryPromoteDescendantToFirstResponder;	// IMP=0x323fb60c
- (void)dealloc;	// IMP=0x323fb21c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323fb6c8
- (void)drawTitle:(id)fp8 inRect:(struct CGRect)fp12;	// IMP=0x323fb4b4
- (void)drawTitle:(id)fp8 withColor:(struct CGColor *)fp12 withShadowColor:(struct CGColor *)fp16 inRect:(struct CGRect)fp20;	// IMP=0x323fb3cc
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323fb194
- (BOOL)isEqualToView:(id)fp8;	// IMP=0x323fb560
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x323fb614
- (void)setStyle:(int)fp8;	// IMP=0x323fb274
- (void)setTitle:(id)fp8;	// IMP=0x323fb28c
- (id)title;	// IMP=0x323fb558

@end

