/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPickerView.h>

#import "UIFormPeripheralProtocol.h"

@class NSMutableArray;

@interface UISelectionPeripheral : UIPickerView <UIFormPeripheral>
{
    id <UISelectionControl> _control;
    id <UIItemControl> _selectedItemControl;
    NSMutableArray *_cachedItems;
    int _orientation;
    unsigned int _firstSelectedIndex;
}

+ (BOOL)isUniqueForEachFormControl;	// IMP=0x3246a20c
- (void)dealloc;	// IMP=0x3246a33c
- (void)endEditing;	// IMP=0x3246a39c
- (id)initFormPeripheral;	// IMP=0x3246a214
- (int)numberOfColumnsInPickerView:(id)fp8;	// IMP=0x3246a6fc
- (int)orientation;	// IMP=0x3246a394
- (int)pickerView:(id)fp8 numberOfRowsInColumn:(int)fp12;	// IMP=0x3246a704
- (void)pickerView:(id)fp8 row:(int)fp12 column:(int)fp16 checked:(BOOL)fp20;	// IMP=0x3246a724
- (id)pickerView:(id)fp8 tableCellForRow:(int)fp12 inColumn:(int)fp16;	// IMP=0x3246a678
- (void)pickerViewLoaded:(id)fp8;	// IMP=0x3246a640
- (void)setFormControl:(id)fp8;	// IMP=0x3246a3a0

@end

