/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface UISelectionIndicatorView : UIView
{
    UIImage *_image;
    CDAnonymousStruct11 _slices;
}

- (void)dealloc;	// IMP=0x3241e9d8
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3241ea30
- (id)initWithFrame:(struct CGRect)fp8 withImageName:(id)fp24;	// IMP=0x32429f4c
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x324283d4

@end

