/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@class NSMutableArray, UISectionList;

@interface UISectionTable : UITable
{
    UISectionList *_sectionList;
    struct _NSRange _visibleHeaders;
    NSMutableArray *_visibleHeaderViews;
    float _rightMargin;
    NSMutableArray *_reusableHeaderCells;
    NSMutableArray *_reusableTransparentHeaderCells;
    int _reusableHeaderCapacity;
    struct {
        unsigned int style:1;
        unsigned int delegateHeaderForSection:1;
        unsigned int disableHideHeadersInShortLists:1;
        unsigned int disallowsScrollIndicators:1;
        unsigned int reserved:28;
    } _sectionTableFlags;
}

- (id)_createHeaderCellForHeaderAtIndex:(int)fp8 width:(float)fp12 opaque:(BOOL)fp16 adjustOrigin:(BOOL)fp20;	// IMP=0x323f906c
- (void)_reloadRowHeights;	// IMP=0x323f9608
- (void)_removeHeaderCellsForRange:(struct _NSRange)fp8;	// IMP=0x323f987c
- (void)_replaceCellWithOpaqueOneGapIndex:(int)fp8 viewIndex:(int)fp12 width:(float)fp16;	// IMP=0x323f9680
- (void)_replaceCellWithTransparentOneGapIndex:(int)fp8 viewIndex:(int)fp12 width:(float)fp16;	// IMP=0x323f9360
- (BOOL)_shouldHideHeaders;	// IMP=0x323f942c
- (void)_updateShowScrollIndicatorsFlag;	// IMP=0x323f9464
- (void)_updateVisibleCellsNow;	// IMP=0x323f9d90
- (id)createPreparedCellForRow:(int)fp8 column:(int)fp12;	// IMP=0x323f8fe8
- (void)dealloc;	// IMP=0x323f8d50
- (void)floatArray:(id)fp8 getValueCount:(int *)fp12 gapIndexCount:(int *)fp16;	// IMP=0x323f8f84
- (BOOL)floatArray:(id)fp8 loadGapIndexes:(int *)fp12 gapHeight:(float *)fp16 count:(int)fp20;	// IMP=0x323f8efc
- (id)indexTitles;	// IMP=0x323f95e8
- (id)initWithFrame:(struct CGRect)fp8 sectionList:(id)fp24;	// IMP=0x323f8c3c
- (id)initWithSize:(struct CGSize)fp8 sectionList:(id)fp16;	// IMP=0x323f8ce4
- (void)reloadData;	// IMP=0x323f9748
- (void)scrollRowToVisible:(int)fp8;	// IMP=0x323fa604
- (void)scrollToSection:(int)fp8;	// IMP=0x323f9c64
- (void)scrollToSectionWithTitle:(id)fp8;	// IMP=0x323f94f8
- (BOOL)sectionHeaderCellWasClicked:(id)fp8;	// IMP=0x323f9ac0
- (void)setAllowsScrollIndicators:(BOOL)fp8;	// IMP=0x323f9540
- (void)setDelegate:(id)fp8;	// IMP=0x323f8e84
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x323f8dc4
- (void)setRightMargin:(float)fp8;	// IMP=0x323f9538
- (void)setSectionListStyle:(int)fp8;	// IMP=0x323f95d0
- (void)setShouldHideHeaderInShortLists:(BOOL)fp8;	// IMP=0x323f9588
- (BOOL)showsSectionHeaders;	// IMP=0x323f94d0

@end

