/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UISwitchControl.h>

@interface UISwitchControl (SyntheticEvents)
- (id)_automationID;	// IMP=0x3244be9c
- (id)_automationValue;	// IMP=0x3244bee0
@end

