/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPushButton.h>

@interface UITableCellDisclosureView : UIPushButton
{
}

- (BOOL)_alwaysHandleScrollerMouseEvent;	// IMP=0x323e8910

@end

