/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITextField.h>

@interface UITextField (SyntheticEvents)
- (id)_automationID;	// IMP=0x323f6d54
- (id)_automationValue;	// IMP=0x323f6de4
@end

