/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITextField.h>

@interface UITextField (Internal)
- (id)_backgroundView;	// IMP=0x323f6ba0
- (struct CGRect)_textRectExcludingButtons;	// IMP=0x323f6aa8
- (id)keyboardInputOverlayContainer:(id)fp8;	// IMP=0x323f6d2c
@end

