/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UITransformAnimation : UIAnimation
{
    struct CGAffineTransform _startTransform;
    struct CGAffineTransform _endTransform;
}

- (struct CGAffineTransform)_transformWithMultiplier:(float)fp8;	// IMP=0x323fcbec
- (void)setEndTransform:(struct CGAffineTransform)fp8;	// IMP=0x323fcbb4
- (void)setProgress:(float)fp8;	// IMP=0x323fcc6c
- (void)setStartTransform:(struct CGAffineTransform)fp8;	// IMP=0x323fcb7c
- (struct CGAffineTransform)transformForFraction:(float)fp8;	// IMP=0x323fccec

@end

