/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (Gestures)
- (BOOL)_canStartRotationFromEvent:(struct __GSEvent *)fp8;	// IMP=0x3243150c
- (BOOL)_canStartZoomFromEvent:(struct __GSEvent *)fp8;	// IMP=0x32430f38
- (void)_gestureChanged:(int)fp8 event:(struct __GSEvent *)fp12;	// IMP=0x324301a4
- (BOOL)_isRubberBanding;	// IMP=0x32430be4
- (void)_resetZoomingWithEvent:(struct __GSEvent *)fp8;	// IMP=0x32431dd0
- (void)_rotateFromEvent:(struct __GSEvent *)fp8;	// IMP=0x324316dc
- (void)_rotateToDegrees:(float)fp8 duration:(float)fp12 event:(struct __GSEvent *)fp16;	// IMP=0x32431328
- (float)_rubberBandScaleForScale:(float)fp8;	// IMP=0x32430d88
- (void)_rubberbandZoomToEvent:(struct __GSEvent *)fp8 scale:(float)fp12;	// IMP=0x32430b0c
- (struct CGPoint)_scrollPointForPoint:(struct CGPoint)fp8 scale:(float)fp16 constrain:(BOOL)fp20 snapToEdge:(BOOL)fp24;	// IMP=0x3243069c
- (void)_setRotationAnimationProgress:(id)fp8;	// IMP=0x32431488
- (void)_setZoomAnimationProgress:(id)fp8;	// IMP=0x32430c4c
- (void)_startGesture:(int)fp8 event:(struct __GSEvent *)fp12;	// IMP=0x3242ff54
- (BOOL)_startRotationFromEvent:(struct __GSEvent *)fp8;	// IMP=0x3243166c
- (BOOL)_startZoomFromEvent:(struct __GSEvent *)fp8;	// IMP=0x32430fec
- (void)_stopGesture:(int)fp8 event:(struct __GSEvent *)fp12;	// IMP=0x32430080
- (void)_stopRotationFromEvent:(struct __GSEvent *)fp8;	// IMP=0x3243186c
- (void)_stopZoomFromEvent:(struct __GSEvent *)fp8;	// IMP=0x324310fc
- (void)_zoomToEvent:(struct __GSEvent *)fp8 scale:(float)fp12 animate:(BOOL)fp16 constrainScrollPoint:(BOOL)fp20;	// IMP=0x32430a40
- (void)_zoomToScale:(float)fp8 event:(struct __GSEvent *)fp12;	// IMP=0x32430958
- (void)_zoomWithEvent:(struct __GSEvent *)fp8;	// IMP=0x32432ff4
- (void)animator:(id)fp8 startAnimation:(id)fp12;	// IMP=0x32430224
- (void)animator:(id)fp8 stopAnimation:(id)fp12;	// IMP=0x324303f0
- (BOOL)canHandleGestures;	// IMP=0x3243195c
- (int)enabledGestures;	// IMP=0x324319c4
- (void)gestureChanged:(struct __GSEvent *)fp8;	// IMP=0x32431f90
- (id)gestureDelegate;	// IMP=0x32431990
- (void)gestureEnded:(struct __GSEvent *)fp8;	// IMP=0x324320e0
- (void)gestureStarted:(struct __GSEvent *)fp8;	// IMP=0x32431e3c
- (void)rotateToDegrees:(float)fp8;	// IMP=0x324312a0
- (float)rotationDegrees;	// IMP=0x32431d70
- (void)setEnabledGestures:(int)fp8;	// IMP=0x324319a0
- (void)setGestureDelegate:(id)fp8;	// IMP=0x3243196c
- (void)setRotationDegrees:(float)fp8 duration:(double)fp12;	// IMP=0x32431ccc
- (void)setValue:(id)fp8 forGestureAttribute:(int)fp12;	// IMP=0x324319d4
- (void)setZoomScale:(float)fp8 duration:(double)fp12;	// IMP=0x32432e28
- (int)stateForGestureType:(int)fp8;	// IMP=0x32431d98
- (id)valueForGestureAttribute:(int)fp8;	// IMP=0x32431b48
- (float)zoomScale;	// IMP=0x32431d84
- (void)zoomToScale:(float)fp8;	// IMP=0x32432adc
@end

