/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (SyntheticEvents)
- (id)_plist:(struct CGPoint)fp8;	// IMP=0x323c7028
- (id)plistWithChildren:(struct CGPoint)fp8;	// IMP=0x323c727c
@end

