/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>
#import <UIKit/UIAnimation.h>

@interface UIView (Animation)
+ (void)disableAnimation;
+ (void)enableAnimation;

/* For example:
 [UIView beginAnimations:nil];
 [UIView setAnimationDuration:2.0];
 [view setFrame:CGRectMake(0, 0, 100, 100)]; // animate to the new frame in 2 seconds
 [UIView endAnimations];
*/

+ (void)beginAnimations:(id)fp8;	
+ (void)beginAnimations:(id)fp8 context:(void *)fp12;
+ (void)endAnimations;

+ (void)setAnimationAutoreverses:(BOOL)autoreverses;	
+ (void)setAnimationCurve:(UIAnimationCurve)animationCurve;	
+ (void)setAnimationDelay:(double)delay;	
+ (void)setAnimationDelegate:(id)delegate;	
+ (void)setAnimationDidStopSelector:(SEL)didStopSelector;	
+ (void)setAnimationDuration:(double)duration;	
+ (void)setAnimationFrameInterval:(double)frameInterval;	
+ (void)setAnimationFromCurrentState:(BOOL)shouldAnimateFromCurrentState;	
+ (void)setAnimationPosition:(CGPoint)position;	
+ (void)setAnimationRepeatCount:(float)repeatCount;	
+ (void)setAnimationRoundsToInteger:(BOOL)roundsToInteger;	
+ (void)setAnimationStartTime:(double)startTime;	
+ (void)setAnimationTransition:(int)transition forView:(id)view cache:(BOOL)shouldCache; // enum needed
+ (void)setAnimationWillStartSelector:(SEL)willStartSelector;

- (void)addAnimation:(UIAnimation *)animation forKey:(id)key;

@end

