/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@interface _UIAlertSheetTable : UITable
{
}

- (void)drawExtraSeparator:(struct CGRect)fp8;	// IMP=0x32417ba0

@end

