/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

@interface _UIAlertOvelayWindow : UIWindow
{
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)fp8;	// IMP=0x324158dc
- (BOOL)_canExistBeyondSuspension;	// IMP=0x32415994
- (void)_handleMouseUp:(struct __GSEvent *)fp8;	// IMP=0x32415900

@end

