/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface _UIPickerViewTopFrame : UIView
{
    UIImage *_leftImage;
    UIImage *_middleImage;
    UIImage *_rightImage;
    float _inset;
}

- (void)dealloc;	// IMP=0x323ac5ac
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323ac660
- (BOOL)ignoresMouseEvents;	// IMP=0x323ac620
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323ac438
- (void)setInset:(float)fp8;	// IMP=0x323ac628
- (void)setLeftImage:(id)fp8 middleImage:(id)fp12 rightImage:(id)fp16;	// IMP=0x323ac4ec

@end

