/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMHTMLAreaElement.h"

@interface DOMHTMLAreaElement (UIWebViewScrubbingExtensions)
- (struct CGRect)boundingBoxAtPoint:(struct CGPoint)fp8;	// IMP=0x324382a4
- (id)boundingBoxesAtPoint:(struct CGPoint)fp8;	// IMP=0x324383ac
@end

