/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "DOMNode.h"

@interface DOMNode (UIWebViewAdditions)
+ (id)approvedFocusNode;	// IMP=0x324369d8
- (struct CGRect)boundingBoxAtPoint:(struct CGPoint)fp8;	// IMP=0x324369f0
- (id)boundingBoxesAtPoint:(struct CGPoint)fp8;	// IMP=0x32436a3c
- (id)calloutSubtitle;	// IMP=0x32436938
- (id)calloutTitle;	// IMP=0x3243690c
- (BOOL)canBecomeFirstResponder;	// IMP=0x324369e8
- (struct CGRect)convertRect:(struct CGRect)fp8 toView:(id)fp24;	// IMP=0x32436a60
- (BOOL)hasApprovedFocus;	// IMP=0x324369ac
- (BOOL)isLikelyToBeginPageLoad;	// IMP=0x32436ba0
- (BOOL)isTextControl;	// IMP=0x32436ba8
- (void)setApprovedFocus:(BOOL)fp8;	// IMP=0x32436948
- (BOOL)showsHighlight;	// IMP=0x32436a58
@end

