/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface KBDynamicDictionaryGlue : NSObject
{
    struct DynamicDictionary *m_dict;
}

- (void)performBackgroundLoad;	// IMP=0x3247601c
- (void)setDictionary:(struct DynamicDictionary *)fp8;	// IMP=0x32476014

@end

