/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (UICollectionAdditions)
- (void *)pop;	// IMP=0x323c8e8c
- (void)push:(void *)fp8;	// IMP=0x323c8e70
- (void *)top;	// IMP=0x323c8ef0
@end

