/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIAlphaAnimation : UIAnimation
{
    float _startAlpha;
    float _endAlpha;
}

- (float)_alphaForMultiplier:(float)fp8;	// IMP=0x323fce1c
- (float)alphaForFraction:(float)fp8;	// IMP=0x323fce74
- (void)setEndAlpha:(float)fp8;	// IMP=0x323fce14
- (void)setProgress:(float)fp8;	// IMP=0x323fce38
- (void)setStartAlpha:(float)fp8;	// IMP=0x323fce0c

@end

