/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITextField.h>

@class UIThreePartImageView;

@interface UIAlertSheetTextField : UITextField
{
    UIThreePartImageView *_sheetBackgroundView;
}

- (id)backgroundView;	// IMP=0x32412304
- (void)dealloc;	// IMP=0x32412264
- (void)setBackgroundView:(id)fp8;	// IMP=0x324122bc

@end

