/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString;

@interface UIAutocorrectInlinePrompt : UIView
{
    struct CGRect m_originalTypedTextRect;
    NSString *m_typedText;
    NSString *m_correction;
    UIView *m_typedTextView;
    UIView *m_correctionView;
    UIView *m_correctionAnimationView;
    UIView *m_typedTextAnimationView;
    UIView *m_correctionShadowView;
    int m_position;
    BOOL m_fits;
    BOOL m_mouseDown;
}

- (struct CGRect)bottomRect;	// IMP=0x324a27f0
- (id)correction;	// IMP=0x324a254c
- (id)correctionAnimationView;	// IMP=0x324a2598
- (id)correctionShadowView;	// IMP=0x324a25a8
- (id)correctionView;	// IMP=0x324a2590
- (void)dealloc;	// IMP=0x324a23a0
- (void)dismiss;	// IMP=0x324a26d0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324a22e0
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x324a2708
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x324a2714
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x324a2718
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x324a25b0
- (int)position;	// IMP=0x324a2580
- (BOOL)prepareForAnimation:(struct CGRect)fp8;	// IMP=0x324a2858
- (void)removePromptSubviews;	// IMP=0x324a241c
- (void)setCorrection:(id)fp8 typedText:(id)fp12 inRect:(struct CGRect)fp16 maxX:(float)fp32;	// IMP=0x324a2d0c
- (void)setPosition:(int)fp8;	// IMP=0x324a2554
- (struct CGRect)shadowFrameForFrame:(struct CGRect)fp8;	// IMP=0x324a24dc
- (struct CGRect)topRect;	// IMP=0x324a2788
- (id)typedTextAnimationView;	// IMP=0x324a25a0
- (id)typedTextView;	// IMP=0x324a2588

@end

