/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIBezierPath.h>

@interface UIBezierPath (UIAutocorrectShadow)
+ (id)shadowBezierPath:(struct CGRect)fp8 withRoundedEdges:(int)fp24;	// IMP=0x324a313c
@end

