/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIButtonBar.h>

@interface UIButtonBar (Internal)
+ (float)_buttonGap;	// IMP=0x32422380
- (void)_alertDidHide;	// IMP=0x32422728
- (void)_alertWillShow:(BOOL)fp8 duration:(float)fp12;	// IMP=0x3242238c
@end

