/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIButtonBarButtonBadge, UISelectionIndicatorView, UITextLabel, UIView;

@interface UIButtonBarButton : UIControl
{
    struct CGRect _hitRect;
    UIView *_info;
    UITextLabel *_label;
    UIButtonBarButtonBadge *_badge;
    UISelectionIndicatorView *_selectedIndicator;
    int _barStyle;
    int _style;
    BOOL _onState;
    BOOL _barHeight;
    float _width;
    float _labelHeight;
    struct CGSize _infoOffset;
}

+ (struct CGColor *)_defaultLabelColor;	// IMP=0x3241f488
+ (struct __GSFont *)_defaultLabelFont;	// IMP=0x3241f474
+ (id)_pushButtonWithBarStyle:(int)fp8 withStyle:(int)fp12;	// IMP=0x3241f4c0
- (void)_adjustPushButton:(BOOL)fp8;	// IMP=0x3241fdc8
- (void)_animateImage:(float)fp8 withButtonBar:(id)fp12;	// IMP=0x3242004c
- (struct CGRect)_buttonBarHitRect;	// IMP=0x3241f88c
- (BOOL)_isBordered;	// IMP=0x3241fffc
- (BOOL)_isOn;	// IMP=0x32420044
- (void)_positionBadge;	// IMP=0x32427efc
- (void)_setBadgeGlyph:(id)fp8;	// IMP=0x3241fb00
- (void)_setBadgeValue:(id)fp8;	// IMP=0x3242437c
- (void)_setBarHeight:(float)fp8;	// IMP=0x324200f4
- (void)_setButtonBarHitRect:(struct CGRect)fp8;	// IMP=0x3241f870
- (void)_setInfoWidth:(float)fp8;	// IMP=0x32424280
- (void)_setOn:(BOOL)fp8;	// IMP=0x3242000c
- (void)_setSelected:(BOOL)fp8;	// IMP=0x3241fa24
- (void)_showSelectedIndicator:(BOOL)fp8 changeSelection:(BOOL)fp12;	// IMP=0x3241f8a4
- (BOOL)_useBarHeight;	// IMP=0x3242016c
- (void)dealloc;	// IMP=0x3241f7a0
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3241fd50
- (id)initWithImage:(id)fp8 selectedImage:(id)fp12 label:(id)fp16 labelHeight:(float)fp20 withBarStyle:(int)fp24 withStyle:(int)fp28 withOffset:(struct _NSSize)fp32;	// IMP=0x32428954
- (void)layoutSubviews;	// IMP=0x32427634
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3241fd28
- (void)setEnabled:(BOOL)fp8;	// IMP=0x3241fc48
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x3241fbc8
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x32427b58
- (void)setImage:(id)fp8;	// IMP=0x3241f850

@end

