/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIButtonBarButton.h>

@class NSString;

@interface UIButtonBarTextButton : UIButtonBarButton
{
    NSString *_title;
    NSString *_selectedTitle;
}

- (id)_automationID;	// IMP=0x32420280
- (void)_setSelected:(BOOL)fp8;	// IMP=0x324201dc
- (void)dealloc;	// IMP=0x32420174
- (id)initWithTitle:(id)fp8 selectedTitle:(id)fp12 withFont:(struct __GSFont *)fp16 withBarStyle:(int)fp20 withStyle:(int)fp24 withTitleWidth:(float)fp28;	// IMP=0x32423e68

@end

