/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIButtonBar.h>

@interface UIButtonBar (SynthEvents)
- (id)_buttonName:(id)fp8 withType:(int)fp12;	// IMP=0x324238a8
- (BOOL)_isHidden:(id)fp8;	// IMP=0x32423848
- (id)plistWithChildren:(struct CGPoint)fp8;	// IMP=0x32423a7c
@end

