/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIContinuationProtocol.h"

@class NSMutableDictionary;

@interface UIContinuation : NSObject <UIContinuation>
{
    NSMutableDictionary *_properties;
    id _continuationContext;
    id _continuationTarget;
    SEL _continuationSelector;
}

- (id)context;	// IMP=0x323def1c
- (void)dealloc;	// IMP=0x323def24
- (void)doContinuation;	// IMP=0x323defd8
- (id)initWithTarget:(id)fp8 context:(id)fp12 continuationSelector:(SEL)fp16;	// IMP=0x323dee60
- (void)setValue:(id)fp8 forProperty:(id)fp12;	// IMP=0x323def98
- (id)valueForProperty:(id)fp8;	// IMP=0x323defb8

@end

