/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface UIControl : UIView
{
    NSMutableArray *_targetActions;
    struct CGPoint _previousPoint;
    double _downTime;
    struct {
        unsigned int tracking:1;
        unsigned int mouseInside:1;
        unsigned int mouseDragged:1;
        unsigned int needsDisplay:1;
        unsigned int highlighted:1;
        unsigned int dontHighlightOnMouseDown:1;
        unsigned int delayActions:1;
        unsigned int allowActionsToQueue:1;
        unsigned int pendingUnhighlight:1;
        unsigned int reserved:23;
    } _controlFlags;
}

- (void)_didMoveFromWindow:(id)fp8 toWindow:(id)fp12;	// IMP=0x323ef760
- (void)addTarget:(id)fp8 action:(SEL)fp12 forEvents:(int)fp16;	// IMP=0x323ef7f0
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x323eef84
- (BOOL)cancelMouseTracking;	// IMP=0x323eefa4
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x323eef8c
- (void)dealloc;	// IMP=0x323eef04
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x323eef94
- (BOOL)hasOneOrMoreTargets;	// IMP=0x323ef7cc
- (BOOL)isHighlighted;	// IMP=0x323ef0ec
- (BOOL)isTracking;	// IMP=0x323eef78
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x323ef11c
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x323ef2a0
- (BOOL)mouseInside;	// IMP=0x323ef01c
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x323ef484
- (void)removeTarget:(id)fp8 forEvents:(int)fp12;	// IMP=0x323ef944
- (void)sendAction:(SEL)fp8 toTarget:(id)fp12 forEvent:(struct __GSEvent *)fp16;	// IMP=0x323ef9fc
- (void)sendActionsForEvents:(int)fp8;	// IMP=0x323efa44
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x323ef044
- (void)setRequiresDisplayOnTracking:(BOOL)fp8;	// IMP=0x323ef02c
- (BOOL)shouldTrack;	// IMP=0x323ef0fc

@end

