/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIImageAndTextTableCell.h>

@interface UIDateTableCell : UIImageAndTextTableCell
{
    float _horizontalOffset;
    float _verticalOffset;
}

- (struct CGRect)contentBounds;	// IMP=0x323b09a4
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323b0890
- (void)setHorizontalOffset:(float)fp8;	// IMP=0x323b0994
- (void)setVerticalOffset:(float)fp8;	// IMP=0x323b099c
- (struct CGColor *)shadowColor;	// IMP=0x323b0a50

@end

