/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIDefaultFormAssistantDelegate : NSObject
{
}

- (void)formAssistant:(id)fp8 didStartAssistingFormControl:(id)fp12;	// IMP=0x32468980
- (void)formAssistant:(id)fp8 didStopAssistingFormControl:(id)fp12;	// IMP=0x32468988
- (void)formAssistant:(id)fp8 willStartAssistingFormControl:(id)fp12;	// IMP=0x32468984
- (void)formAssistant:(id)fp8 willStopAssistingFormControl:(id)fp12;	// IMP=0x3246898c

@end

