/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, UIImageView, UIView;

@interface UIDragger : NSObject
{
    void *_interpolator;
    UIView *_target;
    id _delegate;
    SEL _action;
    struct CGPoint _startLocation;
    struct CGPoint _stopLocation;
    double _duration;
    BOOL _showFinger;
    unsigned int _port;
    NSArray *_modes;
    unsigned long long _startTimestamp;
    unsigned long long _stopTimestamp;
    unsigned long long _lastTimestamp;
    BOOL _waitingForSmoothScrolling;
    UIImageView *_fingerView;
}

- (void)_continueDrag:(id)fp8;	// IMP=0x32433f18
- (double)_delayUntilNextEvent;	// IMP=0x32433d80
- (void)_postMouseEvent:(int)fp8 timestamp:(unsigned long long)fp12 location:(struct CGPoint)fp20;	// IMP=0x32433c10
- (void)_smoothScrollingDidEnd:(id)fp8;	// IMP=0x32433ed4
- (void)_smoothScrollingWillStart:(id)fp8;	// IMP=0x32433ec8
- (void)_stopDrag:(id)fp8;	// IMP=0x32433ef0
- (void)dealloc;	// IMP=0x32433b30
- (void)dragDidEnd;	// IMP=0x32433e70
- (id)init;	// IMP=0x32433a10
- (void)run;	// IMP=0x324341e0
- (void)setAction:(SEL)fp8;	// IMP=0x32433bd8
- (void)setDelegate:(id)fp8;	// IMP=0x32433bd0
- (void)setDuration:(double)fp8;	// IMP=0x32433bf8
- (void)setInterpolation:(void *)fp8;	// IMP=0x32433bc0
- (void)setStartLocation:(struct CGPoint)fp8;	// IMP=0x32433be0
- (void)setStopLocation:(struct CGPoint)fp8;	// IMP=0x32433bec
- (void)setTarget:(id)fp8;	// IMP=0x32433bc8
- (void)showFinger;	// IMP=0x32433c04

@end

