/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableDictionary, UIImageView, UIInformalDelegate, UIThreePartButton, UITransitionView, UIView<UIFormPeripheral>;

@interface UIFormAssistant : UIView
{
    UIThreePartButton *_done;
    UIThreePartButton *_next;
    UIThreePartButton *_previous;
    UIImageView *_navigation;
    UITransitionView *_transition;
    BOOL _isTransitioning;
    id <UIFormControl> _control;
    id <UIFormControl> _nextControl;
    UIView<UIFormPeripheral> *_peripheral;
    UIView<UIFormPeripheral> *_nextPeripheral;
    NSMutableDictionary *_primaryCache;
    NSMutableDictionary *_secondaryCache;
    UIInformalDelegate *_delegate;
    int _orientation;
}

+ (id)_navigationImage;	// IMP=0x32467ec8
+ (double)defaultTransitionDuration;	// IMP=0x32467f68
+ (id)sharedFormAssistant;	// IMP=0x32467ee4
- (id)_formPeripheralForFormControl:(id)fp8;	// IMP=0x32467f94
- (void)advanceToNextFormControl:(id)fp8;	// IMP=0x324681a0
- (void)dealloc;	// IMP=0x32468094
- (void)done:(id)fp8;	// IMP=0x32468150
- (id)formControl;	// IMP=0x3246861c
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324694bc
- (BOOL)isTransitioning;	// IMP=0x32468664
- (BOOL)isTransitioningToNextPeripheral;	// IMP=0x3246866c
- (void)layoutSubviews;	// IMP=0x32469218
- (struct CGRect)peripheralFrame;	// IMP=0x3246867c
- (void)recedeToPreviousFormControl:(id)fp8;	// IMP=0x324681f0
- (struct CGRect)remainingDeviceRect;	// IMP=0x324686d8
- (id)sessionDelegate;	// IMP=0x32468644
- (void)setFormControl:(id)fp8;	// IMP=0x32468990
- (void)setSessionDelegate:(id)fp8;	// IMP=0x32468624
- (void)synchronizeOrientationWithAnimation:(BOOL)fp8;	// IMP=0x32468240
- (void)transitionViewDidComplete:(id)fp8;	// IMP=0x32468460

@end

