/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class UIGestureAnimation, UIScrollAnimation;

@interface UIGestureInfo : NSObject
{
    id delegate;
    int enabledGestures;
    int rotationState;
    int zoomState;
    int panState;
    struct CGPoint startGestureInner;
    struct CGPoint startGestureOuter;
    struct CGPoint startScrollPoint;
    struct CGPoint endScrollPoint;
    struct CGSize visibleSize;
    struct CGRect centerRect;
    UIGestureAnimation *rotationAnimation;
    float rotationDegrees;
    float recentRotationDegrees;
    float minDegrees;
    float maxDegrees;
    float startDegrees;
    float endDegrees;
    UIGestureAnimation *zoomAnimation;
    int zoomRubberBandHysteresisCount;
    float zoomScale;
    float startScale;
    float endScale;
    float unadjustedScale;
    float zoomMultiplier;
    float minScale;
    float maxScale;
    float temporaryMaxScale;
    struct CGPoint zoomFailureWindowPoint;
    float zoomFailureDuration;
    float zoomFailureStartScale;
    float zoomAnimationProgress;
    UIScrollAnimation *scrollAnimation;
    struct {
        unsigned int pushedRunLoop:1;
        unsigned int isRotatingRight:1;
        unsigned int isZoomRubberBandEnabled:1;
        unsigned int zoomsFromCurrentToMinOrMax:1;
        unsigned int updatesScroller:1;
        unsigned int isAnimatingZoomFailure:1;
    } flags;
}

- (void)dealloc;	// IMP=0x32432a00
- (id)init;	// IMP=0x32432950
- (float)maxScale;	// IMP=0x32432ac0

@end

