/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSIndexSet;

@interface UIGroupDeletionItem : NSObject
{
    unsigned int _lastIndex;
    int _group;
    NSIndexSet *_indexes;
}

- (void)dealloc;	// IMP=0x3243ebd8
- (int)group;	// IMP=0x3243ec30
- (id)indexes;	// IMP=0x3243ec38
- (id)initWithGroup:(int)fp8;	// IMP=0x3243eafc
- (id)initWithGroup:(int)fp8 andIndexes:(id)fp12;	// IMP=0x3243eb1c
- (id)initWithIndexes:(id)fp8 inGroup:(int)fp12;	// IMP=0x3243ebb0
- (unsigned int)lastIndex;	// IMP=0x3243ec40
- (void)setLastIndex:(unsigned int)fp8;	// IMP=0x3243ec48

@end

