/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIGroupInsertionItem : NSObject
{
    int _index;
    struct _NSRange _range;
}

- (int)groupIndex;	// IMP=0x3243eae4
- (id)initWithExistingGroup:(int)fp8 andRowRange:(struct _NSRange)fp12;	// IMP=0x3243ea48
- (id)initWithNewGroupBeforeGroup:(int)fp8 andRowCount:(int)fp12;	// IMP=0x3243eab0
- (struct _NSRange)range;	// IMP=0x3243eaec

@end

