/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;

@interface UIHighlightView : UIView
{
    struct CGColor *_color;
    float _cornerRadius;
    NSArray *_cornerRadii;
    NSMutableArray *_innerBounds;
}

- (struct CGColor *)color;	// IMP=0x3246c408
- (id)cornerRadii;	// IMP=0x3246c468
- (float)cornerRadius;	// IMP=0x3246c418
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3246c8b0
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;	// IMP=0x3246cab0
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x3246c378
- (void)setColor:UIColor *fp8;	// IMP=0x3246c400
- (void)setCornerRadii:(id)fp8;	// IMP=0x3246c420
- (void)setCornerRadius:(float)fp8;	// IMP=0x3246c410
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x3246c828
- (void)setFrames:(id)fp8 boundaryRect:(struct CGRect)fp12;	// IMP=0x3246c470

@end

