/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@interface UIImageView : UIControl
{
}

- (id)image;	// IMP=0x3240d540
- (struct CGImage *)imageRef;	// IMP=0x3240d650
- (id)initWithImage:(id)fp8;	// IMP=0x3240d500
- (void)setCGImageRef:(struct CGImage *)fp8;	// IMP=0x3240d630
- (void)setImage:(id)fp8;	// IMP=0x3240d580
- (BOOL)shouldTrack;	// IMP=0x3240d5c0

@end

