/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface UIImage : NSObject
{
    void *_imageRef;
    struct {
        unsigned int named:1;
        unsigned int cached:1;
        unsigned int orientation:3;
        unsigned int isCoreSurfaceBuffer:1;
        unsigned int reserved:26;
    } _imageFlags;
}

+ (void)_flushCacheOnSuspend:(id)fp8;	// IMP=0x323bbd40
+ (id)applicationImageNamed:(id)fp8;	// IMP=0x323bbdbc
+ (id)defaultDesktopImage;	// IMP=0x323bc1f4
+ (id)imageAtPath:(id)fp8;	// IMP=0x323bbda4
+ (id)imageFromAlbumArtData:(id)fp8 height:(int)fp12 width:(int)fp16 cache:(BOOL)fp20;	// IMP=0x323bc3d8
+ (id)imageNamed:(id)fp8;	// IMP=0x323bbd54
+ (id)imageNamed:(id)fp8 inBundle:(id)fp12;	// IMP=0x323bbd8c
+ (void)initialize;	// IMP=0x323bbc88
+ (void)removeImageNameFromCache:(id)fp8;	// IMP=0x323bbd2c
+ (void)setDesktopImageData:(id)fp8;	// IMP=0x323bc35c
- (id)_automationID;	// IMP=0x323bc4e0
- (void)compositeToPoint:(struct CGPoint)fp8 fromRect:(struct CGRect)fp16 operation:(int)fp32 fraction:(float)fp36;	// IMP=0x323bd748
- (void)compositeToPoint:(struct CGPoint)fp8 operation:(int)fp16;	// IMP=0x323bc18c
- (void)compositeToPoint:(struct CGPoint)fp8 operation:(int)fp16 fraction:(float)fp20;	// IMP=0x323bdd48
- (void)compositeToRect:(struct CGRect)fp8 fromRect:(struct CGRect)fp24 operation:(int)fp40 fraction:(float)fp44;	// IMP=0x323bde00
- (struct __CoreSurfaceBuffer *)coreSurfaceBuffer;	// IMP=0x323bc0d4
- (void)dealloc;	// IMP=0x323bc04c
- (void)draw1PartImageInRect:(struct CGRect)fp8;	// IMP=0x323bcf14
- (void)draw1PartImageInRect:(struct CGRect)fp8 fraction:(float)fp24;	// IMP=0x323bcf74
- (void)draw1PartImageInRect:(struct CGRect)fp8 fraction:(float)fp24 operation:(int)fp28;	// IMP=0x323bcfd4
- (void)draw3PartImageWithSliceRects:(CDAnonymousStruct4)fp8 inRect:(struct CGRect)fp56;	// IMP=0x323bdb98
- (void)draw3PartImageWithSliceRects:(CDAnonymousStruct4)fp8 inRect:(struct CGRect)fp56 fraction:(float)fp72;	// IMP=0x323bdc28
- (void)draw3PartImageWithSliceRects:(CDAnonymousStruct4)fp8 inRect:(struct CGRect)fp56 operation:(int)fp72 fraction:(float)fp76;	// IMP=0x323bdcb8
- (void)draw9PartImageWithSliceRects:(CDAnonymousStruct11)fp8 inRect:(struct CGRect)fp152;	// IMP=0x323bcbe4
- (void)draw9PartImageWithSliceRects:(CDAnonymousStruct11)fp8 inRect:(struct CGRect)fp152 fraction:(float)fp168;	// IMP=0x323bcc64
- (void)draw9PartImageWithSliceRects:(CDAnonymousStruct11)fp8 inRect:(struct CGRect)fp152 operation:(int)fp168 fraction:(float)fp172;	// IMP=0x323bcce4
- (void)drawAsPatternInRect:(struct CGRect)fp8;	// IMP=0x323bc128
- (struct CGImage *)imageRef;	// IMP=0x323bc0c0
- (id)initWithContentsOfFile:(id)fp8;	// IMP=0x323bbe74
- (id)initWithContentsOfFile:(id)fp8 cache:(BOOL)fp12;	// IMP=0x323bbdd0
- (id)initWithCoreSurfaceBuffer:(struct __CoreSurfaceBuffer *)fp8;	// IMP=0x323bbfd8
- (id)initWithData:(id)fp8 cache:(BOOL)fp12;	// IMP=0x323bbe94
- (id)initWithImageRef:(struct CGImage *)fp8;	// IMP=0x323bbfb8
- (id)initWithImageRef:(struct CGImage *)fp8 orientation:(int)fp12;	// IMP=0x323bbf38
- (int)orientation;	// IMP=0x323bc0f0
- (struct CGColor *)patternColor;	// IMP=0x323bd034
// GONE: - (void)setOrientation:(int)fp8;	// IMP=0x323bc100
- (struct CGSize)size;	// IMP=0x323bd2b8

@end

