/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface UIInformalDelegate : NSObject
{
    id _target;
    id _default;
}

+ (id)informalDelegateWithDefaultTarget:(id)fp8;	// IMP=0x324350e8
- (void)dealloc;	// IMP=0x32435080
- (void)forwardInvocation:(id)fp8;	// IMP=0x32435138
- (id)initWithDefaultTarget:(id)fp8;	// IMP=0x32435018
- (id)methodSignatureForSelector:(SEL)fp8;	// IMP=0x324351f4
- (BOOL)respondsToSelector:(SEL)fp8;	// IMP=0x32435260
- (void)setTarget:(id)fp8;	// IMP=0x324350d8
- (id)target;	// IMP=0x324350e0

@end

