/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class NSString;

@interface UIKBSuggestionBubble : UIControl
{
    NSString *m_suggestion;
    float m_extraMargin;
    float m_maxWidth;
    int m_textSize;
}

+ (struct CGSize)sizeForSuggestion:(id)fp8 textSize:(int)fp12 maxWidth:(float)fp16;	// IMP=0x3249e668
- (void)action:(id)fp8;	// IMP=0x3249e5cc
- (void)dealloc;	// IMP=0x3249e56c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3249e6c4
- (id)initWithSuggestion:(id)fp8 textSize:(int)fp12 maxWidth:(float)fp16;	// IMP=0x3249e468
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x3249e60c
- (id)suggestion;	// IMP=0x3249e5c4

@end

