/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIKeyboardLayoutQWERTYLandscape.h>

@interface UIKeyboardLayoutQWERTYLandscape (UI_QWERTYLandscape_Alphabet)
- (id)buildUIKeyboardLayoutAlphabet;	// IMP=0x324b1bec
@end

