/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIKeyboardLayoutQWERTY.h>

@interface UIKeyboardLayoutQWERTY (UI_QWERTY_SingleEmailAddressAlt)
- (id)buildUIKeyboardLayoutSingleEmailAddressAlt;	// IMP=0x324b30e4
@end

