/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, NSMutableDictionary, NSString, UIClippedImageView, UIImageView;

@interface UIKeyboardSublayout : UIView
{
    UIImageView *m_imageView;
    UIClippedImageView *m_activeImageView;
    UIImageView *m_shiftImageView;
    UIClippedImageView *m_shiftActiveImageView;
    UIImageView *m_shiftButtonImageView;
    UIImageView *m_autoShiftButtonImageView;
    UIImageView *m_shiftLockedButtonImageView;
    UIClippedImageView *m_groupActiveImageView;
    UIClippedImageView *m_groupShiftActiveImageView;
    NSMutableDictionary *m_compositeImages;
    NSMutableDictionary *m_activeKeyViews;
    NSMutableArray *m_returnKeyImageViews;
    NSMutableArray *m_returnKeyActiveImageViews;
    NSMutableArray *m_returnKeyDisabledImageViews;
    struct {
        struct CGRect;
        struct CGRect;
        struct CGRect;
        struct CGRect;
        struct CGRect;
        NSString *;
        NSString *;
        unsigned int;
        unsigned int;
        unsigned int;
        id;
    } *m_keys;
    unsigned int m_keysCount;
    BOOL m_usesAutoShift;
    BOOL m_registersKeyCentroids;
    BOOL m_usesKeyCharges;
}

+ (id)compositedSublayoutWithFrame:(struct CGRect)fp8 compositeImagePaths:(id)fp24 keys:(const CDAnonymousStruct5 *)fp28 keysCount:(unsigned int)fp32;	// IMP=0x324a4a38
+ (id)sublayoutWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24 keys:(const CDAnonymousStruct5 *)fp28 keysCount:(unsigned int)fp32;	// IMP=0x324a4704
- (void)addReturnKeyImageViewsForKey:(id)fp8;	// IMP=0x324a50e4
- (id)compositeImageForKey:(id)fp8;	// IMP=0x324a50c4
- (void)createGroupKeyViewsWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24;	// IMP=0x324a4ac4
- (void)dealloc;	// IMP=0x324a4bf0
- (id)initWithFrame:(struct CGRect)fp8 compositeImagePaths:(id)fp24 keys:(const CDAnonymousStruct5 *)fp28 keysCount:(unsigned int)fp32;	// IMP=0x324a4790
- (id)initWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24 keys:(const CDAnonymousStruct5 *)fp28 keysCount:(unsigned int)fp32;	// IMP=0x324a4414
- (void)registerKeyCentroids;	// IMP=0x324a4d00
- (void)setAutoShiftButtonImage:(id)fp8 frame:(struct CGRect)fp12;	// IMP=0x324a4f18
- (void)setCompositeImage:(id)fp8 forKey:(id)fp12;	// IMP=0x324a5098
- (void)setRegistersKeyCentroids:(BOOL)fp8;	// IMP=0x324a4e40
- (void)setShiftButtonImage:(id)fp8 frame:(struct CGRect)fp12;	// IMP=0x324a4e58
- (void)setShiftLockedButtonImage:(id)fp8 frame:(struct CGRect)fp12;	// IMP=0x324a4fd8
- (void)setUsesAutoShift:(BOOL)fp8;	// IMP=0x324a4ce8
- (void)setUsesKeyCharges:(BOOL)fp8;	// IMP=0x324a4e50
- (BOOL)usesAutoShift;	// IMP=0x324a4cf0
- (BOOL)usesGroupKeys;	// IMP=0x324a4cf8
- (BOOL)usesKeyCharges;	// IMP=0x324a4e48

@end

