/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UINavigationItemView.h>

@class UINavigationBar;

@interface UINavigationItemButtonView : UINavigationItemView
{
    int _style;
    BOOL _pressed;
    UINavigationBar *_navBar;
}

- (id)_automationID;	// IMP=0x323d65c4
- (struct __GSFont *)_defaultFont;	// IMP=0x323d7728
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323d859c
- (id)initWithNavigationItem:(id)fp8 navBar:(id)fp12;	// IMP=0x323d64d0
- (BOOL)pressed;	// IMP=0x323d65bc
- (void)setPressed:(BOOL)fp8;	// IMP=0x323d6588
- (void)setStyle:(int)fp8;	// IMP=0x323d655c
- (id)title;	// IMP=0x323d651c

@end

