/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIImageAndTextTableCell.h>

@interface UIPickerTableCell : UIImageAndTextTableCell
{
    unsigned int _checked:1;
    unsigned int _reserved:31;
}

- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324af324
- (BOOL)isChecked;	// IMP=0x324af534
- (void)layoutSubviews;	// IMP=0x324af540
- (void)setChecked:(BOOL)fp8;	// IMP=0x324af3d4

@end

