/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIPickerScrollAnimation : UIAnimation
{
    float _initialDuration;
    struct CGPoint _originalOffset;
    struct CGPoint _targetOffset;
}

- (float)initialDuration;	// IMP=0x323acf04
- (void)setInitialDuration:(float)fp8;	// IMP=0x323acf0c
- (void)setOriginalOffset:(struct CGPoint)fp8;	// IMP=0x323acef8
- (void)setProgress:(float)fp8;	// IMP=0x323b06f0
- (void)setTargetOffset:(struct CGPoint)fp8;	// IMP=0x323aceec
- (struct CGPoint)targetOffset;	// IMP=0x323acedc

@end

