/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UIImageView, UIProgressIndicator, UIWindow;

@interface UIProgressHUD : UIView
{
    UIProgressIndicator *_progressIndicator;
    BOOL _isShowing;
    UIWindow *_hostWindow;
    NSString *_text;
    struct __GSFont *_font;
    UIImageView *_doneView;
    int _fontSize;
}

+ (struct __GSFont *)loadingFont;	// IMP=0x32461b68
- (id)_progressIndicator;	// IMP=0x32461b18
- (void)dealloc;	// IMP=0x32461db0
- (void)done;	// IMP=0x32461c68
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32461e80
- (id)initWithWindow:(id)fp8;	// IMP=0x324620b4
- (void)setFontSize:(int)fp8;	// IMP=0x32461b9c
- (void)setText:(id)fp8;	// IMP=0x32461b20
- (void)show:(BOOL)fp8;	// IMP=0x32461bd8

@end

