/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPreferencesTableCell.h>

@class UIControl;

@interface UIPreferencesControlTableCell : UIPreferencesTableCell
{
    UIControl *_control;
}

- (void)_controlClicked:(id)fp8;	// IMP=0x32457bc8
- (id)control;	// IMP=0x32457bc0
- (void)setControl:(id)fp8;	// IMP=0x32457aac
- (void)setEnabled:(BOOL)fp8;	// IMP=0x32457c7c

@end

