/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIRemoveControl.h>

@interface UIPreferencesTableCellRemoveControl : UIRemoveControl
{
}

- (float)_removeConfirmationButtonVerticalOffset;	// IMP=0x32444b40
- (float)_verticalOffsetFromTarget;	// IMP=0x32444b34
- (void)addConfirmationButtonSubview:(id)fp8 withWidth:(float)fp12 target:(id)fp16;	// IMP=0x32444a44
- (float)removeButtonAnimationDuration;	// IMP=0x32444a84
- (struct CGRect)removeButtonEndingFrame;	// IMP=0x32444aa4
- (struct CGRect)removeButtonStartingFrame;	// IMP=0x32444af8
- (struct CGRect)targetContentBounds;	// IMP=0x32444b48

@end

