/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIPreferencesControlTableCell.h>

@interface UIPreferencesDeleteTableCell : UIPreferencesControlTableCell
{
}

+ (float)defaultHeight;	// IMP=0x324b2934
- (id)button;	// IMP=0x324b2c04
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324b2974

@end

