/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/CDStructures.h>
#import <UIKit/UIControl.h>

@class NSString;

@interface UIPushButton : UIControl
{
    NSString *_title;
    struct __GSFont *_font;
    struct CGSize _shadowOffset;
    struct CGSize _titlePadding;
    struct __CFDictionary *_info;
    struct {
        unsigned int selected:1;
        unsigned int drawShadow:1;
        unsigned int disableAutosizeToFit:1;
        unsigned int drawContentsCentered:1;
        unsigned int reverseShadowDirectionWhenHighlighted:1;
        unsigned int stretchBackground:1;
        unsigned int showPressFeedback:1;
        unsigned int reserved:25;
    } _pushButtonFlags;
}

+ (struct __GSFont *)defaultFont;	// IMP=0x323f0440
- (CDAnonymousStruct4)_backgroundSlices:(struct CGSize)fp8;	// IMP=0x323f10c8
- (void)_drawBezelPartInRect:(struct CGRect)fp8;	// IMP=0x323f211c
- (void)_drawImageAndTextPartInRect:(struct CGRect)fp8;	// IMP=0x323f1d8c
- (BOOL)autosizesToFit;	// IMP=0x323f0a5c
- (id)backgroundForState:(unsigned int)fp8;	// IMP=0x323f0e64
- (id)currentBackground;	// IMP=0x323f0ff8
- (id)currentImage;	// IMP=0x323f0e88
- (struct CGColor *)currentShadowColor;	// IMP=0x323f0f70
- (struct CGColor *)currentTitleColor;	// IMP=0x323f0ef0
- (void)dealloc;	// IMP=0x323f0660
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;	// IMP=0x323f12c0
- (void)drawImageAtPoint:(struct CGPoint)fp8 fraction:(float)fp16;	// IMP=0x323f114c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x323f1330
- (void)drawTitleAtPoint:(struct CGPoint)fp8 width:(float)fp16;	// IMP=0x323f11a0
- (id)imageForState:(unsigned int)fp8;	// IMP=0x323f0df8
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323f0454
- (id)initWithImage:(id)fp8;	// IMP=0x323f05ec
- (id)initWithTitle:(id)fp8;	// IMP=0x323f0540
- (id)initWithTitle:(id)fp8 autosizesToFit:(BOOL)fp12;	// IMP=0x323f0560
- (BOOL)isPressed;	// IMP=0x323f081c
- (BOOL)isSelected;	// IMP=0x323f08d0
- (struct CGPoint)pressFeedbackPosition;	// IMP=0x323f0a70
- (void)setAutosizesToFit:(BOOL)fp8;	// IMP=0x323f0a0c
- (void)setBackground:(id)fp8 forState:(unsigned int)fp12;	// IMP=0x323f2310
- (void)setDrawContentsCentered:(BOOL)fp8;	// IMP=0x323f0bd8
- (void)setDrawsShadow:(BOOL)fp8;	// IMP=0x323f0aec
- (void)setEnabled:(BOOL)fp8;	// IMP=0x323f0758
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x323f1060
- (void)setHighlighted:(BOOL)fp8;	// IMP=0x323f182c
- (void)setImage:(id)fp8 forState:(unsigned int)fp12;	// IMP=0x323f0d00
- (void)setNeedsDisplay;	// IMP=0x323f13ac
- (void)setReverseShadowDirectionWhenHighlighted:(BOOL)fp8;	// IMP=0x323f0b3c
- (void)setSelected:(BOOL)fp8;	// IMP=0x323f083c
- (void)setShadowColor:(struct CGColor *)fp8 forState:(unsigned int)fp12;	// IMP=0x323f23e8
- (void)setShadowOffset:(float)fp8;	// IMP=0x323f0b04
- (void)setShowPressFeedback:(BOOL)fp8;	// IMP=0x323f0c20
- (void)setStretchBackground:(BOOL)fp8;	// IMP=0x323f0b84
- (void)setTitle:(id)fp8;	// IMP=0x323f08dc
- (void)setTitleColor:(struct CGColor *)fp8 forState:(unsigned int)fp12;	// IMP=0x323f24bc
- (void)setTitleFont:(struct __GSFont *)fp8;	// IMP=0x323f0960
- (void)setTitlePadding:(struct CGSize)fp8;	// IMP=0x323f0ae0
- (struct CGColor *)shadowColorForState:(unsigned int)fp8;	// IMP=0x323f0e40
- (void)sizeToFit;	// IMP=0x323f1bb4
- (unsigned int)state;	// IMP=0x323f06f0
- (id)title;	// IMP=0x323f0958
- (struct CGColor *)titleColorForState:(unsigned int)fp8;	// IMP=0x323f0e1c
- (struct __GSFont *)titleFont;	// IMP=0x323f09cc

@end

