/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIResponder.h>

@interface UIResponder (Internal)
- (void)_controlMouseDown:(struct __GSEvent *)fp8;	// IMP=0x3240e168
- (void)_controlMouseDragged:(struct __GSEvent *)fp8;	// IMP=0x3240e0d0
- (void)_controlMouseUp:(struct __GSEvent *)fp8;	// IMP=0x3240e11c
@end

