/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIFrameAnimation.h>

@interface UIRemoveControlTextFrameAnimation : UIFrameAnimation
{
}

- (void)setProgress:(float)fp8;	// IMP=0x3241d1d8

@end

