/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class NSString, UITableCell;

@interface UIRemoveControlTextButton : UIControl
{
    UITableCell *_tableCell;
    NSString *_label;
}

- (BOOL)_alwaysHandleScrollerMouseEvent;	// IMP=0x3241aef8
- (id)_automationID;	// IMP=0x3241af18
- (void)_controlMouseDown:(struct __GSEvent *)fp8;	// IMP=0x3241ae60
- (void)_controlMouseDragged:(struct __GSEvent *)fp8;	// IMP=0x3241ae04
- (void)_controlMouseUp:(struct __GSEvent *)fp8;	// IMP=0x3241ae64
- (float)buttonWidth;	// IMP=0x3241cb6c
- (void)dealloc;	// IMP=0x3241ae08
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3241d354
- (id)initWithRemoveControl:(id)fp8 withTarget:(id)fp12 withLabel:(id)fp16;	// IMP=0x3241c034
- (void)sizeToFit;	// IMP=0x3241ae68

@end

