/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UIRemoveControlMinusButton;

@interface UIRemoveControl : UIView
{
    UIView *_target;
    id _delegate;
    UIView *_removeConfirmationButton;
    UIRemoveControlMinusButton *_minusButton;
    NSString *_label;
    struct {
        unsigned int removeButtonVisible:1;
        unsigned int removeConfirmationVisible:1;
        unsigned int removedFromTargetWhenHidden:1;
        unsigned int disableToggleRotate:1;
        unsigned int tableCellTarget:1;
        unsigned int alwaysHideRemoveButton:1;
        unsigned int showAsPlus:1;
        unsigned int reserved:25;
    } _removeControlFlags;
}

+ (void)hideAllRemoveConfirmationsInView:(id)fp8;	// IMP=0x3241b0fc
+ (float)removeButtonWidth;	// IMP=0x3241afd0
+ (BOOL)removeConfirmationsVisibleInView:(id)fp8;	// IMP=0x3241aff8
- (id)_automationID;	// IMP=0x3241bbf8
- (void)_confirmationAnimationDidEnd;	// IMP=0x3241b680
- (void)_doInsert:(id)fp8;	// IMP=0x3241be20
- (void)_doRemove:(id)fp8;	// IMP=0x3241be70
- (void)_hideRemoveAnimationDone;	// IMP=0x3241bfbc
- (void)_hideRemoveConfirmation;	// IMP=0x3241bd64
- (id)_interceptMouseEvent:(struct __GSEvent *)fp8;	// IMP=0x3241b904
- (BOOL)_isInsertControl;	// IMP=0x3241bce0
- (void)_minusButtonFadeAnimationStopped;	// IMP=0x3241b53c
- (void)_setInsertControl:(BOOL)fp8;	// IMP=0x3241bcf0
- (void)_setInterceptMouseEvent:(BOOL)fp8;	// IMP=0x3241b3ec
- (void)_setRemoveConfirmationShowing:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x3241c890
- (void)_shouldRemoveTarget;	// IMP=0x3241bf18
- (void)_showDeleteConfirmation:(id)fp8;	// IMP=0x3241bd90
- (float)_verticalOffsetFromTarget;	// IMP=0x3241bcd8
- (void)addConfirmationButtonSubview:(id)fp8 withWidth:(float)fp12 target:(id)fp16;	// IMP=0x3241bd08
- (void)animator:(id)fp8 stopAnimation:(id)fp12;	// IMP=0x3241bf68
- (void)dealloc;	// IMP=0x3241b26c
- (id)delegate;	// IMP=0x3241b3a4
- (void)hideControlsUsingRemoveAnimation;	// IMP=0x3241ba78
- (id)initWithTarget:(id)fp8;	// IMP=0x3241b160
- (BOOL)isRemoveButtonVisible;	// IMP=0x3241b674
- (BOOL)isRemoveConfirmationVisible;	// IMP=0x3241b6f0
- (void)minusButtonDidHide:(id)fp8;	// IMP=0x3241b468
- (float)removeButtonAnimationDuration;	// IMP=0x3241b668
- (struct CGRect)removeButtonEndingFrame;	// IMP=0x3241b5bc
- (struct CGRect)removeButtonStartingFrame;	// IMP=0x3241b610
- (id)removeConfirmationButton;	// IMP=0x3241bbf0
- (id)removeConfirmationView;	// IMP=0x3241b8fc
- (BOOL)removedFromTargetWhenHidden;	// IMP=0x3241b3dc
- (void)setAlpha:(float)fp8;	// IMP=0x3241ba1c
- (void)setAlwaysHideRemoveButton:(BOOL)fp8;	// IMP=0x3241b3c4
- (void)setDelegate:(id)fp8;	// IMP=0x3241b39c
- (void)setLabel:(id)fp8;	// IMP=0x3241bb74
- (void)setRemoveConfirmationLabel:(id)fp8;	// IMP=0x3241bbb0
- (void)setRemoveConfirmationVisible:(BOOL)fp8;	// IMP=0x3241b700
- (void)setRemoveConfirmationVisible:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x3241b724
- (void)setRemovedFromTargetWhenHidden:(BOOL)fp8;	// IMP=0x3241b3ac
- (void)setTarget:(id)fp8;	// IMP=0x3241b338
- (void)showRemoveButton:(BOOL)fp8 animated:(BOOL)fp12;	// IMP=0x3241c250
- (struct CGRect)targetContentBounds;	// IMP=0x3241b6b0

@end

