/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

@interface UIResponder : NSObject
{
}

- (BOOL)_containedInAbsoluteResponderChain;	// IMP=0x3240de80
- (unsigned int)becomeFirstResponder;	// IMP=0x3240dec0
- (BOOL)canBecomeFirstResponder;	// IMP=0x3240df84
- (BOOL)canResignFirstResponder;	// IMP=0x3240e004
- (id)firstResponder;	// IMP=0x3240e038
- (void)gestureChanged:(struct __GSEvent *)fp8;	// IMP=0x3240e1b4
- (void)gestureEnded:(struct __GSEvent *)fp8;	// IMP=0x3240e200
- (void)gestureStarted:(struct __GSEvent *)fp8;	// IMP=0x3240e24c
- (BOOL)isFirstResponder;	// IMP=0x3240e00c
- (void)keyDown:(struct __GSEvent *)fp8;	// IMP=0x3240e2e4
- (void)keyUp:(struct __GSEvent *)fp8;	// IMP=0x3240e298
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x3240de34
- (void)mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x3240e460
- (void)mouseEntered:(struct __GSEvent *)fp8;	// IMP=0x3240e414
- (void)mouseExited:(struct __GSEvent *)fp8;	// IMP=0x3240e3c8
- (void)mouseMoved:(struct __GSEvent *)fp8;	// IMP=0x3240e37c
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x3240e4ac
- (id)nextResponder;	// IMP=0x3240de2c
- (BOOL)resignFirstResponder;	// IMP=0x3240df8c
- (void)scrollWheel:(struct __GSEvent *)fp8;	// IMP=0x3240e330

@end

