/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface UIRemoteApplication : NSObject
{
    NSString *_bundleID;
    unsigned int _port;
    struct __CFMachPort *_portRef;
}

- (BOOL)available;	// IMP=0x324ac688
- (void)dealloc;	// IMP=0x324ac414
- (BOOL)disableMiniAlerts:(int)fp8;	// IMP=0x324ac6c4
- (void)disconnected;	// IMP=0x324ac4c4
- (BOOL)enableMiniAlerts:(char *)fp8;	// IMP=0x324ac708
- (id)initWithBundleIdentifier:(id)fp8;	// IMP=0x324ac398
- (void)invalidatePort;	// IMP=0x324ac480
- (BOOL)statusBarWillAnimateToHeight:(float)fp8 duration:(double)fp12 fence:(int)fp20;	// IMP=0x324ac790
- (BOOL)updatePort;	// IMP=0x324ac500
- (BOOL)wantsToShowMiniAlert:(char *)fp8;	// IMP=0x324ac74c

@end

