/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIRotationAnimation : UIAnimation
{
    float _startAngle;
    float _endAngle;
}

- (void)setEndRotationAngle:(float)fp8;	// IMP=0x323fcefc
- (void)setProgress:(float)fp8;	// IMP=0x323fcf30
- (void)setStartRotationAngle:(float)fp8;	// IMP=0x323fcec8

@end

