/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIScroller.h>

@interface UIScroller (Internal)
+ (void)_registerForNotifications;	// IMP=0x323cb3c4
+ (void)_unregisterForNotifications;	// IMP=0x323cb428
- (void)_addScrollNotificationView:(id)fp8;	// IMP=0x323cb6cc
- (void)_adjustBackgroundShadowsForContentSize:(struct CGSize)fp8;	// IMP=0x323cdb44
- (void)_adjustSpecialViews;	// IMP=0x323cb610
- (BOOL)_alwaysHandleInteractionEvents;	// IMP=0x323cb5e0
- (id)_bottomShadowView;	// IMP=0x323cb608
- (id)_bottomSpecialView;	// IMP=0x323cb600
- (void)_cancelContentHighlight;	// IMP=0x323cb8b8
- (BOOL)_isUserScrolling;	// IMP=0x323cb5e8
- (void)_removeScrollNotificationView:(id)fp8;	// IMP=0x323cb7bc
- (void)_resetScrollingWithEvent:(struct __GSEvent *)fp8;	// IMP=0x323cdf1c
- (void)_stopScrollingNotify:(BOOL)fp8;	// IMP=0x323cb470
- (id)_topSpecialView;	// IMP=0x323cb5f8
@end

