/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIImageView.h>

@interface UISegmentedSelectionIndicator : UIImageView
{
}

- (id)initWithStyle:(int)fp8;	// IMP=0x324107f4
- (void)setPosition:(int)fp8 withStyle:(int)fp12;	// IMP=0x32410d04

@end

