/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UISegment : UIView
{
    UIView *_info;
    float _width;
    struct CGSize _imagePadding;
    struct {
        unsigned int style:2;
        unsigned int selected:1;
        unsigned int showDivider:1;
        unsigned int hasImage:1;
        unsigned int isDisclosure:1;
        unsigned int position:3;
        unsigned int reserved:23;
    } _segmentFlags;
}

- (void)_positionInfo;	// IMP=0x324111b4
- (void)animateAdd:(BOOL)fp8;	// IMP=0x3240ef58
- (void)animateRemove;	// IMP=0x3240ef94
- (struct CGRect)contentRect;	// IMP=0x3240f08c
- (void)dealloc;	// IMP=0x3240edb4
- (id)infoName;	// IMP=0x3240f1b8
- (id)initWithInfo:(id)fp8 style:(int)fp12 position:(unsigned int)fp16 isDisclosure:(BOOL)fp20;	// IMP=0x3240eb00
- (void)setEnabled:(BOOL)fp8;	// IMP=0x3240ee0c
- (void)setImagePadding:(struct CGSize)fp8;	// IMP=0x3240f188
- (void)setInfo:(id)fp8;	// IMP=0x32411348
- (void)setPosition:(unsigned int)fp8;	// IMP=0x3240f13c
- (void)setSelected:(BOOL)fp8;	// IMP=0x32411744
- (void)setShowDivider:(BOOL)fp8;	// IMP=0x3240eed4

@end

