/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UISectionTable;

@interface UISectionIndex : UIControl
{
    UISectionTable *_sectionTable;
    struct CGPoint _lastMousePoint;
}

+ (float)opaqueVisibleWidth;	// IMP=0x32407964
+ (float)visibleWidth;	// IMP=0x32407958
- (void)_scrollToClosestSectionAtPoint:(struct CGPoint)fp8;	// IMP=0x32407c98
- (id)_sectionTitles;	// IMP=0x32407938
- (id)_titleForPoint:(struct CGPoint)fp8 pastTop:(char *)fp16 pastBottom:(char *)fp20;	// IMP=0x32407b68
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;	// IMP=0x32407e04
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x32407e90
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x32407fa8
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;	// IMP=0x32407f14
- (id)initWithSectionTable:(id)fp8;	// IMP=0x32407a20
- (void)noteIndexTitlesDidChangeInSectionList:(id)fp8;	// IMP=0x32407de8

@end

