/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UITextLabel.h>

@class NSString;

@interface UITableCountView : UITextLabel
{
    NSString *_countString;
}

- (id)initWithFrame:(struct CGRect)fp8 withCountString:(id)fp24 withCount:(int)fp28;	// IMP=0x323d9a1c
- (void)setCount:(int)fp8;	// IMP=0x323d9b98
- (void)setCountString:(id)fp8 withCount:(int)fp12;	// IMP=0x323d9b3c

@end

