/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface UIThreePartImageView : UIView
{
    CDAnonymousStruct4 _slices;
    UIImage *_image;
}

- (void)dealloc;	// IMP=0x32411f9c
- (void)drawRect:(struct CGRect)fp8;	// IMP=0x3241205c
- (void)setImage:(id)fp8;	// IMP=0x32411ff4
- (void)setSlices:(CDAnonymousStruct4)fp8;	// IMP=0x3241201c

@end

