/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (Private)
- (struct CGPoint)_bottomConstrainedScrollPoint:(struct CGPoint)fp8 contentSize:(struct CGSize)fp16 cScale:(float)fp24 scale:(float)fp28;	// IMP=0x32439cd4
- (struct CGPoint)_scrollPointForBoundedRect:(struct CGRect)fp8 withBoundary:(struct CGRect)fp24 scale:(float)fp40;	// IMP=0x32439510
- (float)boundedScaleForFocusRect:(struct CGRect)fp8 deviceBoundaryRect:(struct CGRect)fp24;	// IMP=0x324397f4
@end

