/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (CALayerDelegate)
- (void)_layoutSublayersOfLayer:(id)fp8;	// IMP=0x323c7000
- (id)actionForLayer:(id)fp8 forKey:(id)fp12;	// IMP=0x323c83cc
- (void)drawLayer:(id)fp8 inContext:(struct CGContext *)fp12;	// IMP=0x323c822c
- (void)setValue:(id)fp8 forKey:(id)fp12;	// IMP=0x323c6f30
@end

