/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIResponder.h>

@class LKLayer, UIGestureInfo, UIViewTapInfo;

@interface UIView : UIResponder
{
    LKLayer         *_layer;
    UIViewTapInfo   *_tapInfo;
    UIGestureInfo   *_gestureInfo; 
    void            *_touchData;
    float           _charge;
    int             _tag;
    struct {
        unsigned int userInteractionDisabled:1;
        unsigned int implementsDrawRect:1;
        unsigned int implementsDidScroll:1;
        unsigned int implementsMouseTracking:1;
        unsigned int hasBackgroundColor:1;
        unsigned int isOpaque:1;
        unsigned int becomeFirstResponderWhenCapable:1;
        unsigned int interceptMouseEvent:1;
        unsigned int deallocating:1;
        unsigned int debugFlash:1;
        unsigned int debugSkippedSetNeedsDisplay:1;
        unsigned int debugScheduledDisplayIsRequired:1;
        unsigned int isInAWindow:1;
        unsigned int isAncestorOfFirstResponder:1;
        unsigned int dontAutoresizeSubviews:1;
        unsigned int autoresizeMask:6;
        unsigned int patternBackground:1;
        unsigned int fixedBackgroundPattern:1;
        unsigned int dontAnimate:1;
        unsigned int superLayerIsView:1;
        unsigned int layerKitPatternDrawing:1;
        unsigned int coreSurfaceImage:1;
        unsigned int multipleTouchEnabled:1;
        unsigned int reserved:4;
    } _viewFlags;

}

+ (Class)layerClass;	// IMP=0x323c3874
- (unsigned int)_becomeFirstResponderWhenPossible;	// IMP=0x323c3fc0
- (void)_clearBecomeFirstResponderWhenCapable;	// IMP=0x323c3fb0
- (void)_createLayerWithFrame:(struct CGRect)fp8;	// IMP=0x323c389c
- (BOOL)canHandleSwipes;	// IMP=0x323c4060
- (BOOL)cancelMouseTracking;	// IMP=0x323c404c
- (float)charge;	// IMP=0x323c3edc
- (void)dealloc;	// IMP=0x323c6400
- (id)init;	// IMP=0x323c3828
- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x323c3a14
- (BOOL)isEnabled;	// IMP=0x323c3e18
- (id)nextResponder;	// IMP=0x323c3f94
- (void)setCharge:(float)fp8;	// IMP=0x323c3e28
- (void)setEnabled:(BOOL)fp8;	// IMP=0x323c3d2c
- (void)setTapDelegate:(id)fp8;	// IMP=0x323c3ee4
- (void)startHeartbeat:(SEL)fp8 inRunLoopMode:(id)fp12;	// IMP=0x323c3fd4
- (void)stopHeartbeat:(SEL)fp8;	// IMP=0x323c4018
- (int)swipe:(int)fp8 withEvent:(struct __GSEvent *)fp12;	// IMP=0x323c4068
- (id)tapDelegate;	// IMP=0x323c3f84
- (void)setUserInteractionEnabled:(BOOL)fp8;

@end

