/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (Deprecated)
+ (void)setAnimationTransition:(int)fp8 forView:(id)fp12;	// IMP=0x323c615c
- (id)initWithSize:(struct CGSize)fp8;	// IMP=0x323c8768
- (void)setSize:(struct CGSize)fp8;	// IMP=0x323c7f1c
- (struct CGSize)size;	// IMP=0x323c6110
@end

