/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>
#import <QuartzCore/QuartzCore.h>

@interface UIView (Internal)
+ (BOOL)_invalidatesViewUponCreation;	// IMP=0x323c619c
+ (void)_setInvalidatesViewUponCreation:(BOOL)fp8;	// IMP=0x323c6188
+ (void)_setIsResponderAncestorOfFirstResponder:(BOOL)fp8 startingAtFirstResponder:(id)fp12;	// IMP=0x323c8a60
- (BOOL)_alwaysHandleInteractionEvents;	// IMP=0x323c637c
- (BOOL)_alwaysHandleScrollerMouseEvent;	// IMP=0x323c6374
- (BOOL)_canDrawContent;	// IMP=0x323c6364
- (BOOL)_canHandleStatusBarMouseEvents;	// IMP=0x323c6e94
- (BOOL)_cancelTapDelegateTracking;	// IMP=0x323c6e70
- (BOOL)_containedInAbsoluteResponderChain;	// IMP=0x323c6dac
- (void)_didMoveFromWindow:(id)fp8 toWindow:(id)fp12;	// IMP=0x323c6bdc
- (void)_didScroll;	// IMP=0x323c628c
- (id)_interceptMouseEvent:(struct __GSEvent *)fp8;	// IMP=0x323c6318
- (void)_invalidateLayerContents;	// IMP=0x323c62e0
- (void)_invalidateSubviewCache;	// IMP=0x323c6290
- (CALayer *)_layer;	// IMP=0x323c61fc
- (void)_mouseDown:(struct __GSEvent *)fp8;	// IMP=0x323c6dbc
- (void)_mouseDragged:(struct __GSEvent *)fp8;	// IMP=0x323c6df8
- (void)_mouseUp:(struct __GSEvent *)fp8;	// IMP=0x323c6e34
- (void)_renderSnapshotWithRect:(struct CGRect)fp8 inContext:(struct CGContext *)fp24;	// IMP=0x323c85c0
- (id)_scroller;	// IMP=0x323c6204
- (void)_setContentImage:(id)fp8;	// IMP=0x323c6e9c
- (void)_setContentsTransform:(struct CGAffineTransform)fp8;	// IMP=0x323c6edc
- (void)_setInterceptMouseEvent:(BOOL)fp8;	// IMP=0x323c6300
- (BOOL)_subclassImplementsDrawRect;	// IMP=0x323c61b0
- (id)_window;	// IMP=0x323c8e30
@end

