/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWebView.h>

@interface UIWebView (UIFormAssistantSessionDelegate)
- (void)formAssistant:(id)fp8 didStartAssistingFormControl:(id)fp12;	// IMP=0x3243610c
- (void)formAssistant:(id)fp8 didStopAssistingFormControl:(id)fp12;	// IMP=0x32436148
- (void)formAssistant:(id)fp8 willStartAssistingFormControl:(id)fp12;	// IMP=0x32435ca0
@end

