/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIDateTableCell.h>

@class NSDate, UITextLabel;

@interface UIWeekMonthDayTableCell : UIDateTableCell
{
    UITextLabel *_weekdayLabel;
    NSDate *_date;
}

- (struct CGColor *)_weekdayLabelColor;	// IMP=0x323b0b1c
- (id)date;	// IMP=0x323b0acc
- (void)dealloc;	// IMP=0x323b0a64
- (void)layoutSubviews;	// IMP=0x323b0c78
- (void)setBackgroundColor:(struct CGColor *)fp8;	// IMP=0x323b0b5c
- (void)setDate:(id)fp8;	// IMP=0x323b0ad4
- (void)setWeekdayString:(id)fp8;	// IMP=0x323b0dd0
- (void)updateHighlightColors;	// IMP=0x323b0bb8

@end

