/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWebView.h>

#import "WebFormDelegateProtocol.h"

@interface UIWebView (WebFormDelegate) <WebFormDelegate>
- (void)didFinishLoading:(id)fp8;	// IMP=0x32435c9c
- (void)formElementDidBlur:(id)fp8;	// IMP=0x32435bcc
- (void)formElementDidFocus:(id)fp8;	// IMP=0x32435aa0
- (void)frame:(id)fp8 sourceFrame:(id)fp12 willSubmitForm:(id)fp16 withValues:(id)fp20 submissionListener:(id)fp24;	// IMP=0x32435c7c
- (void)textDidChangeInTextArea:(id)fp8 inFrame:(id)fp12;	// IMP=0x32435a68
- (void)textDidChangeInTextField:(id)fp8 inFrame:(id)fp12;	// IMP=0x32435a40
- (BOOL)textField:(id)fp8 doCommandBySelector:(SEL)fp12 inFrame:(id)fp16;	// IMP=0x32435a90
- (BOOL)textField:(id)fp8 shouldHandleEvent:(struct __GSEvent *)fp12 inFrame:(id)fp16;	// IMP=0x32435a98
- (void)textFieldDidBeginEditing:(id)fp8 inFrame:(id)fp12;	// IMP=0x32435a38
- (void)textFieldDidEndEditing:(id)fp8 inFrame:(id)fp12;	// IMP=0x32435a3c
@end

