/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIHighlightView, UITextLabel;

@interface UIWebViewLabel : UIView
{
    UITextLabel *_label;
    UIHighlightView *_highlight;
}

- (id)initWithFrame:(struct CGRect)fp8;	// IMP=0x324aeb3c
- (void)setText:(id)fp8;	// IMP=0x324aef04
- (void)sizeToFit;	// IMP=0x324aedcc

@end

