/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWebPlugInView.h>

@interface UIWebPlugInView (Private)
- (void)_reshapeOnMainThread;	// IMP=0x3243e7ec
- (void)_viewDidMoveToWindowOnMainThread;	// IMP=0x3243e8c4
@end

