/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <UIKit/UIWebView.h>

@interface UIWebView (Forms)
- (void)_updateFormElementBoundaries;	// IMP=0x324352d8
- (id)formEditingDelegate;	// IMP=0x324353d4
- (BOOL)isFormEdited;	// IMP=0x32435420
- (void)scrollCaretToVisible:(id)fp8;	// IMP=0x32435434
- (void)setFormEditingDelegate:(id)fp8;	// IMP=0x324353b4
- (void)setZoomsFocusedFormControl:(BOOL)fp8;	// IMP=0x32435418
- (BOOL)webView:(id)fp8 shouldChangeSelectedDOMRange:(id)fp12 toDOMRange:(id)fp16 affinity:(int)fp20 stillSelecting:(BOOL)fp24;	// IMP=0x3243542c
- (BOOL)zoomsFocusedFormControl;	// IMP=0x324353f4
@end

