/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "WAKView.h"

@class UIView, UIWebView;

@interface UIWebPlugInView : WAKView
{
    UIWebView *_webView;
    UIView *_uiView;
    BOOL _isFullScreen;
}

- (void)dealloc;	// IMP=0x3243e398
- (id)initWithWebView:(id)fp8 plugInView:(id)fp12;	// IMP=0x3243e2b8
- (void)mouseDown:(struct __GSEvent *)fp8;	// IMP=0x3243e77c
- (void)mouseUp:(struct __GSEvent *)fp8;	// IMP=0x3243e7b4
- (id)objectForWebScript;	// IMP=0x3243e730
- (id)plugInView;	// IMP=0x3243e5e8
- (void)reshape;	// IMP=0x3243e5f0
- (void)setFrame:(struct CGRect)fp8;	// IMP=0x3243e3f4
- (void)setFrameSize:(struct CGSize)fp8;	// IMP=0x3243e4bc
- (void)viewDidMoveToWindow;	// IMP=0x3243e58c
- (void)webPlugInDestroy;	// IMP=0x3243e6e8
- (void)webPlugInInitialize;	// IMP=0x3243e610
- (void)webPlugInStart;	// IMP=0x3243e658
- (void)webPlugInStop;	// IMP=0x3243e6a0

@end

