/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class IMAPFetchResult, NSString;

@interface _IMAPFetchUnit : NSObject
{
    unsigned int uid;
    NSString *fetchItem;
    IMAPFetchResult *_expectedFetchResult;
}

- (void)_setupExpectedFetchResult;	// IMP=0x30bb6d01
- (id)createFailedFetchResponse;	// IMP=0x30bb6c01
- (void)dealloc;	// IMP=0x30bb6a91
- (BOOL)matchesFetchResponse:(id)fp8;	// IMP=0x30bb6ad5

@end

