/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageBody.h>

@class NSMutableData;

@interface _OutgoingMessageBody : MessageBody
{
    NSMutableData *rawData;
}

- (void)dealloc;	// IMP=0x30b6153b
- (id)mutableData;	// IMP=0x30b61575
- (id)rawData;	// IMP=0x30b615c1

@end

