/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@interface AOLAccount : IMAPAccount
{
}

+ (id)accountInfoValueForKey:(id)fp8 value:(id)fp12;	// IMP=0x30bc7de1
+ (id)defaultPathNameForAccountWithHostname:(id)fp8 username:(id)fp12;	// IMP=0x30bc7bed
+ (id)deliveryAccountHostname;	// IMP=0x30bc7ec9
+ (unsigned int)deliveryAccountPortNumber;	// IMP=0x30bc7f59
+ (BOOL)deliveryAccountUsesSSL;	// IMP=0x30bc7f09
+ (id)displayedAccountTypeString;	// IMP=0x30bc7c3d
+ (id)emailAddressHostPart;	// IMP=0x30bc7be1
+ (BOOL)isPredefinedAccountType;	// IMP=0x30bc7c49
- (id)_defaultSpecialMailboxNameForType:(int)fp8;	// IMP=0x30bc7c4d
- (id)deliveryAccount;	// IMP=0x30bc7fa5
- (id)emailAddresses;	// IMP=0x30bc7d1b
- (id)hostname;	// IMP=0x30bc7ca1
- (unsigned int)portNumber;	// IMP=0x30bc7ce3
- (void)setHostname:(id)fp8;	// IMP=0x30bc7ce1
- (void)setPortNumber:(unsigned int)fp8;	// IMP=0x30bc7d19
- (void)setUsername:(id)fp8;	// IMP=0x30bc7d89

@end

