/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/IMAPConnection.h>

@interface ExchangeConnection : IMAPConnection
{
}

- (id)_fetchArgumentForMessageSkeletonsWithHeaders:(id)fp8;	// IMP=0x30bc840d
- (id)_fetchArgumentForMessageUidsAndFlags;	// IMP=0x30bc8401
- (BOOL)_isFetchResponseValid:(id)fp8;	// IMP=0x30bc84b5

@end

