/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/BufferedMessageQueue.h>

@class IMAPConnection, LibraryIMAPStore;

@interface FetchResponseQueue : BufferedMessageQueue
{
    LibraryIMAPStore *_store;
    IMAPConnection *_connection;
    unsigned int _localUidNext;
    unsigned int _numNewUIDs;
    int newMessageCount;
}

- (BOOL)addItem:(id)fp8;	// IMP=0x30ba3e19
- (BOOL)handleItems:(id)fp8;	// IMP=0x30ba3db5
- (id)init;	// IMP=0x30ba3d79
- (unsigned int)sizeForItem:(id)fp8;	// IMP=0x30ba3db1

@end

