/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/LibraryStore.h>

@class IMAPCommandPipeline, IMAPDownloadCache, IMAPMailboxSyncEngine, NSString;

@interface LibraryIMAPStore : LibraryStore
{
    unsigned int _supportsCustomPermanentFlags:1;
    unsigned int _supportsJunkFlag:1;
    unsigned int _supportsDollarJunkFlag:1;
    unsigned int _supportsNotJunkFlag:1;
    unsigned int _supportsDollarNotJunkFlag:1;
    unsigned int _supportsForwardedFlag:1;
    unsigned int _supportsDollarForwardedFlag:1;
    unsigned int _updatingCache:1;
    unsigned int _updateMetadata:1;
    unsigned int _readyToDealloc:1;
    unsigned int _didSynchronizeOldMessages:1;
    unsigned int _recentsExist:1;
    unsigned int _settingServerCount:1;
    unsigned int _reserved:16;
    NSString *_mailboxName;
    IMAPDownloadCache *_downloadCache;
    IMAPCommandPipeline *_fetchPipeline;
    IMAPMailboxSyncEngine *_syncEngine;
    unsigned int _serverDeletedCount;
    unsigned int _serverUidNext;
    NSString *_selectedUID;
    NSString *_relativePath;
}

- (void)_addOfflineTransferMessages:(id)fp8;	// IMP=0x30ba5405
- (id)_cachedBodyForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30ba5ea9
- (id)_cachedHeaderDataForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30ba5f91
- (id)_cachedHeadersForMessage:(id)fp8 valueIfNotPresent:(id)fp12;	// IMP=0x30ba5f1d
- (BOOL)_changedFlagsForMessage:(id)fp8 fetchResponse:(id)fp12 newFlags:(unsigned int *)fp16;	// IMP=0x30ba9545
- (id)_createDataFromMimePart:(id)fp8 threshold:(unsigned int)fp12;	// IMP=0x30ba6119
- (id)_dataForMessage:(id)fp8 readHeadersOnly:(BOOL)fp12;	// IMP=0x30ba6005
- (int)_doAppend:(CDAnonymousStruct5 *)fp8;	// IMP=0x30baaba1
- (BOOL)_doUidCopy:(CDAnonymousStruct5 *)fp8 toStore:(id)fp12 newMessages:(id)fp16;	// IMP=0x30ba9a91
- (id)_fetchBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12;	// IMP=0x30ba6df5
- (id)_fetchBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12 partial:(char *)fp16;	// IMP=0x30ba8951
- (id)_fetchDataForMimePart:(id)fp8 keepInMemory:(BOOL)fp12 writeToDisk:(BOOL)fp16 range:(struct _NSRange)fp20 isComplete:(char *)fp28;	// IMP=0x30ba68e9
- (id)_fetchHeaderDataForMessage:(id)fp8;	// IMP=0x30ba6ef1
- (int)_fetchMessagesWithArguments:(id)fp8 idRange:(id)fp12 onConnection:(id)fp16 synchronize:(BOOL)fp20 limit:(unsigned int)fp24 topUIDToCompact:(unsigned int)fp28 topKnownUID:(unsigned int)fp32 success:(char *)fp36 examinedRange:(struct _NSRange *)fp40 fetchableUIDsFound:(unsigned int *)fp44 preserveUID:(int *)fp48;	// IMP=0x30ba8f61
- (void)_handleFlagsChangedForMessages:(id)fp8 oldFlagsByMessage:(id)fp12;	// IMP=0x30ba98a9
- (void)_invalidate;	// IMP=0x30ba49b5
- (void)_retrieveNewMessagesForCheckingNewMail:(BOOL)fp8;	// IMP=0x30ba7743
- (void)_setFlagsAndColorForMessages:(id)fp8;	// IMP=0x30ba7ba1
- (void)_setFlagsForMessages:(id)fp8 mask:(unsigned long)fp12;	// IMP=0x30ba7a15
- (void)_setFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;	// IMP=0x30ba95c1
- (void)_synchronouslySetFlags:(id)fp8 clearFlags:(id)fp12 forMessages:(id)fp16 originalChanges:(id)fp20;	// IMP=0x30ba57d1
- (id)_uidsForMessages:(id)fp8;	// IMP=0x30ba755d
- (id)addMessages:(id)fp8 newMessagesByOldMessage:(id)fp12;	// IMP=0x30ba9991
- (BOOL)allowsAppend;	// IMP=0x30ba53f9
- (int)appendMessages:(id)fp8 unsuccessfulOnes:(id)fp12 newMessageIDs:(id)fp16 newMessages:(id)fp20 flagsToSet:(id)fp24;	// IMP=0x30ba80bd
- (id)bodyDataForMessage:(id)fp8;	// IMP=0x30ba6e11
- (BOOL)canCompact;	// IMP=0x30baa409
- (BOOL)canRebuild;	// IMP=0x30ba4f4d
- (int)checkNewMail;	// IMP=0x30ba4f21
- (void)close;	// IMP=0x30ba7e6d
- (id)connection;	// IMP=0x30ba70e9
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;	// IMP=0x30ba7159
- (BOOL)connection:(id)fp8 shouldHandleUntaggedResponse:(id)fp12 forCommand:(CDAnonymousStruct7 *)fp16;	// IMP=0x30ba75ed
- (id)connectionCreateIfNeeded:(BOOL)fp8;	// IMP=0x30ba70cd
- (void)connectionDidDisconnect:(id)fp8;	// IMP=0x30ba7741
- (id)connectionWithOptions:(int)fp8;	// IMP=0x30ba702d
- (id)copyOfMessagesInRange:(struct _NSRange)fp8 options:(unsigned int)fp16;	// IMP=0x30ba783d
- (id)createDictionaryForLocalFlags:(unsigned long)fp8 serverFlags:(unsigned long)fp12 existingDictionary:(id)fp16;	// IMP=0x30ba56e9
- (id)dataForMimePart:(id)fp8;	// IMP=0x30ba8095
- (id)dataForMimePart:(id)fp8 inRange:(struct _NSRange)fp12;	// IMP=0x30ba6c25
- (id)dataForMimePart:(id)fp8 inRange:(struct _NSRange)fp12 isComplete:(char *)fp20 downloadIfNecessary:(BOOL)fp24 didDownload:(char *)fp28;	// IMP=0x30ba8db9
- (void)dealloc;	// IMP=0x30ba48a5
- (void)deleteMessagesOlderThanNumberOfDays:(int)fp8 compact:(BOOL)fp12;	// IMP=0x30ba5239
- (id)deletedMessages;	// IMP=0x30ba7889
- (void)doCompact;	// IMP=0x30ba5059
- (id)downloadCache;	// IMP=0x30ba7e1f
- (int)fetchNewMessagesAndSynchronizeOldMessages:(BOOL)fp8;	// IMP=0x30ba4d73
- (int)fetchNumMessages:(unsigned int)fp8 preservingUID:(id)fp12 beforeUID:(unsigned int)fp16 synchronize:(BOOL)fp20;	// IMP=0x30baa5d9
- (id)fetchPipeline;	// IMP=0x30ba7e19
- (int)fetchSynchronously;	// IMP=0x30ba4f39
- (void)focusedMessageDidChange:(id)fp8;	// IMP=0x30ba4b1d
- (void)forceResync;	// IMP=0x30ba7745
- (id)fullBodyDataForMessage:(id)fp8 andHeaderDataIfReadilyAvailable:(id *)fp12 isComplete:(char *)fp16 downloadIfNecessary:(BOOL)fp20;	// IMP=0x30ba8b79
- (BOOL)hasMoreMessages:(unsigned int)fp8;	// IMP=0x30ba7f0d
- (BOOL)hasValidCacheFileForMessage:(id)fp8;	// IMP=0x30ba779d
- (id)initWithMailboxUid:(id)fp8 readOnly:(BOOL)fp12;	// IMP=0x30ba4789
- (id)lockedConnection:(char *)fp8;	// IMP=0x30ba7101
- (id)mailboxName;	// IMP=0x30ba5025
- (void)messageFlagsDidChange:(id)fp8 flags:(id)fp12;	// IMP=0x30ba79c5
- (id)messageForRemoteID:(id)fp8;	// IMP=0x30ba7eb5
- (void)messagesWereAdded:(id)fp8 forIncrementalLoading:(BOOL)fp12;	// IMP=0x30ba7975
- (id)offlineCache;	// IMP=0x30ba7e25
- (id)offlineCacheIfOffline;	// IMP=0x30ba7e49
- (id)relativePath;	// IMP=0x30ba8041
- (void)removeAllLocalMessages;	// IMP=0x30ba4fa1
- (unsigned int)serverMessageCount;	// IMP=0x30ba801d
- (unsigned int)serverUnreadCount;	// IMP=0x30ba8029
- (void)setData:(id)fp8 forMimePart:(id)fp12 isComplete:(BOOL)fp16;	// IMP=0x30ba6c51
- (id)setFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;	// IMP=0x30ba5af5
- (BOOL)setPreferredEncoding:(unsigned long)fp8 forMessage:(id)fp12;	// IMP=0x30baa479
- (void)setServerMessageCount:(unsigned int)fp8;	// IMP=0x30ba7f1b
- (void)setUid:(unsigned long)fp8 forMessageWithTemporaryUid:(unsigned long)fp12;	// IMP=0x30baaa71
- (void)startSynchronization;	// IMP=0x30ba9525
- (int)syncMessagesInIMAPRange:(CDAnonymousStruct2)fp8 withConnection:(id)fp16 compactingExpungedMessagesToUid:(unsigned int)fp20;	// IMP=0x30ba8311
- (void)syncOlderMessages;	// IMP=0x30ba4d71
- (void)synchronize;	// IMP=0x30ba4e95
- (void)updateDeletedCount;	// IMP=0x30ba4bc1
- (id)willBeReleased;	// IMP=0x30ba4939
- (id)willSetFlagsFromDictionary:(id)fp8 forMessages:(id)fp12;	// IMP=0x30ba5e15

@end

