/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/MessageTextAttachment.h>

@class MimePart;

@interface MimeTextAttachment : MessageTextAttachment
{
    MimePart *_mimePart;
}

- (unsigned int)approximateSize;	// IMP=0x30b70ec1
- (void)dealloc;	// IMP=0x30b70c25
- (id)displayedMimePart;	// IMP=0x30b70cd9
- (id)fileWrapperForcingDownload:(BOOL)fp8;	// IMP=0x30b70e29
- (id)initWithMimePart:(id)fp8;	// IMP=0x30b70c61
- (id)initWithMimePart:(id)fp8 andFileWrapper:(id)fp12;	// IMP=0x30b70ca5
- (id)mimePart;	// IMP=0x30b70cd5
- (void)setFileWrapper:(id)fp8;	// IMP=0x30b70e91
- (void)setMimePart:(id)fp8;	// IMP=0x30b70dfd
- (BOOL)shouldDownloadAttachmentOnDisplay;	// IMP=0x30b70f11

@end

