/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSMutableDictionary, NSString, PartialNetworkData;

@interface MimePart : NSObject
{
    NSString *_type;
    NSString *_subtype;
    NSMutableDictionary *_bodyParameters;
    NSString *_contentTransferEncoding;
    NSMutableDictionary *_otherIvars;
    struct _NSRange _range;
    id _parentOrBody;
    MimePart *_nextPart;
    PartialNetworkData *_partialData;
    NSData *_fullData;
}

+ (void)initialize;	// IMP=0x30b65429
+ (BOOL)parseContentTypeHeader:(id)fp8 type:(id *)fp12 subtype:(id *)fp16;	// IMP=0x30b68f71
- (id)_partThatIsAttachment;	// IMP=0x30b660e5
- (void)_setDecryptedMessageBody:(id)fp8 isEncrypted:(BOOL)fp12 isSigned:(BOOL)fp16;	// IMP=0x30b69435
- (void)addSubpart:(id)fp8;	// IMP=0x30b6c719
- (id)alternativeAtIndex:(int)fp8;	// IMP=0x30b67131
- (unsigned int)approximateRawSize;	// IMP=0x30b6c06d
- (id)attachmentFilename;	// IMP=0x30b67579
- (id)attachments;	// IMP=0x30b65f75
- (id)availableBodyData;	// IMP=0x30b65ae1
- (id)availableHtmlContent;	// IMP=0x30b6660d
- (id)bodyData;	// IMP=0x30b65ac9
- (id)bodyDataForcingDownload:(BOOL)fp8;	// IMP=0x30b65a41
- (id)bodyDataToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12;	// IMP=0x30b65a91
- (id)bodyDataToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12 downloadIfNecessary:(BOOL)fp16;	// IMP=0x30b65a15
- (id)bodyParameterForKey:(id)fp8;	// IMP=0x30b656b1
- (id)bodyParameterKeys;	// IMP=0x30b656dd
- (void)clearCachedDescryptedMessageBody;	// IMP=0x30b693d1
- (void)configureFileWrapper:(id)fp8;	// IMP=0x30b66a0d
- (id)contentDescription;	// IMP=0x30b657a1
- (id)contentID;	// IMP=0x30b657c5
- (id)contentLocation;	// IMP=0x30b657e9
- (id)contentToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12 asHTML:(BOOL)fp16;	// IMP=0x30b665c5
- (id)contentToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12 downloadIfNecessary:(BOOL)fp16 asHTML:(BOOL)fp20;	// IMP=0x30b6a2b9
- (id)contentTransferEncoding;	// IMP=0x30b6570d
- (id)copyBodyDataToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12;	// IMP=0x30b65aad
- (id)copyBodyDataToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12 downloadIfNecessary:(BOOL)fp16;	// IMP=0x30b67ce1
- (void)dealloc;	// IMP=0x30b6ac41
- (id)decodedDataForData:(id)fp8;	// IMP=0x30b658e1
- (id)decryptedMessageBodyIsEncrypted:(char *)fp8 isSigned:(char *)fp12;	// IMP=0x30b673a1
- (id)description;	// IMP=0x30b6c6b9
- (id)disposition;	// IMP=0x30b65711
- (id)dispositionParameterForKey:(id)fp8;	// IMP=0x30b65735
- (id)dispositionParameterKeys;	// IMP=0x30b65775
- (id)fileWrapper;	// IMP=0x30b669f5
- (id)fileWrapperForcingDownload:(BOOL)fp8;	// IMP=0x30b667f1
- (id)firstChildPart;	// IMP=0x30b6585d
- (void)getNumberOfAttachments:(unsigned int *)fp8 isSigned:(char *)fp12 isEncrypted:(char *)fp16;	// IMP=0x30b65ee5
- (id)htmlContent;	// IMP=0x30b665e9
- (id)htmlContentToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12;	// IMP=0x30b665a9
- (id)htmlContentToOffset:(unsigned int)fp8 resultOffset:(unsigned int *)fp12 downloadIfNecessary:(BOOL)fp16;	// IMP=0x30b66585
- (id)init;	// IMP=0x30b6561d
- (BOOL)isAttachment;	// IMP=0x30b66199
- (BOOL)isHTML;	// IMP=0x30b6642d
- (BOOL)isReadableText;	// IMP=0x30b65fd5
- (BOOL)isRich;	// IMP=0x30b66311
- (id)languages;	// IMP=0x30b6580d
- (void)loadMoreHtmlContent;	// IMP=0x30b66665
- (id)mimeBody;	// IMP=0x30b65b1d
- (id)nextSiblingPart;	// IMP=0x30b6c9d9
- (int)numberOfAlternatives;	// IMP=0x30b67005
- (unsigned int)numberOfAttachments;	// IMP=0x30b65ec1
- (id)parentPart;	// IMP=0x30b65831
- (id)preservedHeaderValueForKey:(id)fp8;	// IMP=0x30b656f5
- (struct _NSRange)range;	// IMP=0x30b658d1
- (void)setBodyParameter:(id)fp8 forKey:(id)fp12;	// IMP=0x30b69319
- (void)setContentDescription:(id)fp8;	// IMP=0x30b69361
- (void)setContentID:(id)fp8;	// IMP=0x30b6937d
- (void)setContentLocation:(id)fp8;	// IMP=0x30b69399
- (void)setContentTransferEncoding:(id)fp8;	// IMP=0x30b69ebd
- (void)setDisposition:(id)fp8;	// IMP=0x30b69ecd
- (void)setDispositionParameter:(id)fp8 forKey:(id)fp12;	// IMP=0x30b69ef5
- (void)setLanguages:(id)fp8;	// IMP=0x30b693b5
- (void)setMimeBody:(id)fp8;	// IMP=0x30b65b91
- (void)setRange:(struct _NSRange)fp8;	// IMP=0x30b658db
- (void)setSubparts:(id)fp8;	// IMP=0x30b6c819
- (void)setSubtype:(id)fp8;	// IMP=0x30b69265
- (void)setType:(id)fp8;	// IMP=0x30b69255
- (id)signedData;	// IMP=0x30b672d5
- (id)startPart;	// IMP=0x30b66ec5
- (id)subpartAtIndex:(int)fp8;	// IMP=0x30b65899
- (id)subparts;	// IMP=0x30b6c939
- (id)subtype;	// IMP=0x30b6563d
- (unsigned long)textEncoding;	// IMP=0x30b67735
- (id)textHtmlPart;	// IMP=0x30b672f5
- (unsigned int)totalTextSize;	// IMP=0x30b666c1
- (id)type;	// IMP=0x30b6562d
- (BOOL)usesKnownSignatureProtocol;	// IMP=0x30b68e89

@end

