/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableString;

@interface MimeEnrichedReader : NSObject
{
    struct {
        unsigned short buffer[64];
        struct __CFString *theString;
        unsigned short *directBuffer;
        struct {
            int location;
            int length;
        } rangeToBuffer;
        int bufferedRangeStart;
        int bufferedRangeEnd;
    } _inputBuffer;
    int _currentIndex;
    int _inputLength;
    unsigned int _noFillLevel:30;
    unsigned int _eatOneNewline:1;
    unsigned int _insideComment:1;
    unsigned int _wantsPlainText:1;
    int _lastQuoteLevel;
    struct __CFArray *_commandStack;
    id _outputString;
    NSMutableString *_outputBuffer;
    struct __CFString *_prependHTML;
    struct __CFString *_postpendHTML;
    float _indentWidth;
}

+ (struct __CFCharacterSet *)parenSet;	// IMP=0x30b6d7fd
+ (struct __CFCharacterSet *)punctuationSet;	// IMP=0x30b6d7d9
- (void)appendNewLine:(id)fp8;	// IMP=0x30b6dba5
- (void)appendStringToBuffer:(id)fp8;	// IMP=0x30b6d8d5
- (void)beginCommand:(id)fp8;	// IMP=0x30b6da45
- (void)closeUpQuoting;	// IMP=0x30b6da01
- (void)convertEnrichedString:(id)fp8 intoOutputString:(id)fp12;	// IMP=0x30b6dd15
- (void)convertRichTextString:(id)fp8 intoOutputString:(id)fp12;	// IMP=0x30b6dbc1
- (id)currentFont;	// IMP=0x30b6ea65
- (void)dealloc;	// IMP=0x30b6d865
- (id)description;	// IMP=0x30b6de6d
- (void)endCommand:(id)fp8;	// IMP=0x30b6e9b1
- (void)handleNoParameterCommand:(const CDAnonymousStruct3 *)fp8;	// IMP=0x30b6e2e1
- (void)mismatchError:(id)fp8;	// IMP=0x30b6d841
- (void)nowWouldBeAGoodTimeToAppendToTheAttributedString;	// IMP=0x30b6ec25
- (void)parseParameterString:(id)fp8;	// IMP=0x30b6e74b
- (int)readTokenInto:(id *)fp8;	// IMP=0x30b6e3bd
- (void)resetStateWithString:(id)fp8 outputString:(id)fp12;	// IMP=0x30b6d939
- (void)setWantsHTML:(BOOL)fp8;	// IMP=0x30b6d821
- (void)setupFontStackEntry:(struct _CommandStackEntry *)fp8;	// IMP=0x30b6eabd

@end

