/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (LockingAdditions)
+ (void)clearLocks;	// IMP=0x30b9ab51
- (BOOL)isLocked;	// IMP=0x30b9ad29
- (void)lock;	// IMP=0x30b9aff1
- (void)lockWithPriority;	// IMP=0x30b9b011
- (BOOL)tryLock;	// IMP=0x30b9b2d9
- (BOOL)tryLockWithPriority;	// IMP=0x30b9b2fd
- (void)unlock;	// IMP=0x30b9abe1
- (void)yieldLock;	// IMP=0x30b9b031
@end

