/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/SASLAuthenticator.h>

@interface PlainAuthenticator : SASLAuthenticator
{
}

- (BOOL)justSentPlainTextPassword;	// IMP=0x30b9ff05
- (id)responseForServerData:(id)fp8;	// IMP=0x30b9fe0d
- (id)saslName;	// IMP=0x30b9fe01

@end

