/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface POP3Fetcher : NSObject
{
}

+ (int)_fetchWithAccount:(id)fp8 intoQueue:(id)fp12 newMessages:(unsigned int)fp16 oldMessages:(unsigned int)fp20 preservingUID:(id)fp24 withStore:(id)fp28;	// IMP=0x30bbe0b1
+ (int)fetchWithAccount:(id)fp8 newMessages:(unsigned int)fp12 oldMessages:(unsigned int)fp16 preservingUID:(id)fp20 withStore:(id)fp24;	// IMP=0x30bbec89

@end

