/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/WebAttachmentSource.h>

@interface WebAttachmentSource (Mail)
- (int)priority;	// IMP=0x30b72a0b
@end

