/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/WebAttachmentSource.h>

@class MimeBody, MimePart, NSData, NSDictionary, NSMutableDictionary;

@interface WebMessageDocument : WebAttachmentSource
{
    NSDictionary *_partsByURL;
    NSDictionary *_partsByFilename;
    NSMutableDictionary *_attachmentsByURL;
    MimeBody *_mimeBody;
    MimePart *_htmlPart;
    NSData *_htmlData;
    unsigned int _preferredCharset;
    unsigned int _downloadRemoteURLs:1;
    unsigned int _containsRemoteContent:1;
    BOOL _messageIsFromEntourage;
}

- (void)appendHTMLData:(id)fp8;	// IMP=0x30b732c7
- (id)attachmentForURL:(id)fp8;	// IMP=0x30b72f81
- (id)attachmentsInDocument;	// IMP=0x30b73079
- (BOOL)containsRemoteContent;	// IMP=0x30b732b1
- (void)dealloc;	// IMP=0x30b72a11
- (BOOL)downloadRemoteURLs;	// IMP=0x30b73217
- (id)fileWrapper;	// IMP=0x30b73195
- (id)htmlData;	// IMP=0x30b73191
- (id)init;	// IMP=0x30b72a75
- (id)initWithMimeBody:(id)fp8;	// IMP=0x30b72aa9
- (id)initWithMimePart:(id)fp8;	// IMP=0x30b72b05
- (id)initWithMimePart:(id)fp8 htmlData:(id)fp12 encoding:(unsigned long)fp16;	// IMP=0x30b72ba1
- (BOOL)messageIsFromEntourage;	// IMP=0x30b732c1
- (id)mimeBody;	// IMP=0x30b73155
- (id)mimePart;	// IMP=0x30b73159
- (id)mimePartForURL:(id)fp8;	// IMP=0x30b72e59
- (id)preferredCharacterSet;	// IMP=0x30b73161
- (void)setContainsRemoteContent:(BOOL)fp8;	// IMP=0x30b73223
- (void)setDownloadRemoteURLs:(BOOL)fp8;	// IMP=0x30b73201
- (void)setMessageIsFromEntourage:(BOOL)fp8;	// IMP=0x30b732bb
- (void)setPreferredEncoding:(unsigned long)fp8;	// IMP=0x30b7315d

@end

