/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Message/AuthScheme.h>

@interface XYMCOOKIEAuthScheme : AuthScheme
{
}

- (id)authenticatorForAccount:(id)fp8 connection:(id)fp12;	// IMP=0x30bc6299
- (id)name;	// IMP=0x30bc631d
- (BOOL)requiresPassword;	// IMP=0x30bc6329

@end

