/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <QuartzCore/CAPropertyAnimation.h>

@interface CABasicAnimation : CAPropertyAnimation {}

- (id)byValue;
- (id)fromValue;
- (id)toValue;

@end

@interface CABasicAnimation (CAAnimationPrivate)

- (BOOL)roundsToInteger;

@end
