/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <QuartzCore/CAContext.h>

@interface CAContextImpl : CAContext {}

- (unsigned int)_clientPort;	
- (unsigned int)contextId;	
- (unsigned int)createSlot;	
- (void)dealloc;	
- (void)deleteSlot:(unsigned int)fp8;	
- (id)initRemoteWithOptions:(id)fp8;	
- (id)initWithOptions:(id)fp8;	
- (void)invalidate;	
- (id)layer;	
- (float)level;	
- (void)orderAbove:(unsigned int)fp8;	
- (void)orderBelow:(unsigned int)fp8;	
- (void)setFence:(unsigned int)fp8 count:(unsigned int)fp12;	
- (void)setLayer:(id)fp8;	
- (void)setLevel:(float)fp8;	
- (void)setObject:(id)fp8 forSlot:(unsigned int)fp12;	
- (BOOL)valid;	

@end
